[Docs]Update dev.md to Chinese
WasmEdge/WasmEdge pull request #1042
Opened 2022-01-22 17:02 UTC by infdahai

Signed-off-by: cluster <clusternlh@gmail.com>

2022-01-24 06:50 UTC, hydai requested changes

2022-01-24 06:50 UTC, hydai commented on docs/book/zh/src/dev.md
> +WebAssembly是一种为多种语言服务的托管运行时，包括 C/C++, Rust, Go,Swift, Kotlin, AssemblyScript, Grain and even JavaScript and Python.
英文跟中文字之間應該有一個半形空格，如 `WebAssembly 是`.

2022-01-24 06:50 UTC, hydai commented on docs/book/zh/src/dev.md
> +* 对于编译型语言(例如C和Rust), WasmEdge WebAssembly 提供了一个安全、可靠、隔离和容器化的运行时，
使用中文時，應用全形符號，如 `，` 而非 `,`

2022-01-24 06:50 UTC, hydai commented on docs/book/zh/src/dev.md
> +而非Native Client.
同理 `。` 而非 `.`

2022-01-24 07:49 UTC, infdahai commented on docs/book/zh/src/dev.md
> +而非Native Client.
好的，晚点我会修改并提交更多的内容。

2022-01-25 11:04 UTC, alabulei1 commented on docs/book/zh/src/dev/go.md
> +
这里应该只是说，在安装 TinyGo 之前，请确保已经在机器上安装了 Go。 Go already installed  的 link 只是说明 go 的安装文档

2022-01-25 11:06 UTC, alabulei1 commented on docs/book/zh/src/dev/go.md
> +你将在同一目录下一个名为 `hello.wasm` 文件。这是一个 WebAssembly 字节码文件。
你将在同一目录看见，少了 see。

2022-01-25 11:12 UTC, alabulei1 commented on docs/book/zh/src/dev/js.md
> +* [网络套接字](js/networking.md) 展示了使用 WasmEdge 网络扩展和提供的 JavaScript API 去构建 HTTP 客户端和服务端程序。
1. Socket 应该不翻译，网络 socket
2. 展示了如何使用 WasmEdge 网络扩展和及其提供的 JavaScript API

2022-01-25 11:15 UTC, alabulei1 commented on docs/book/zh/src/dev/python.md
> +
启用 `freeze-stdlib` 功能可以在二进制文件中使用 Python 标准库。 这样更通顺一些?

2022-01-25 11:45 UTC, alabulei1 commented
Hi @infdahai 
Thanks for your contribution. Much appreciated. 
You did a lot of work. I need some time to take a look at your code. Will come back soon.

2022-01-25 11:55 UTC, infdahai commented on docs/book/zh/src/dev/go.md
> +
这里我更改成
```md
你需要在安装 TinyGo 之前已经在你的机器上安装过 [Go](https://go.dev/doc/install)
```

2022-01-25 11:57 UTC, infdahai commented on docs/book/zh/src/dev/go.md
> +> 并访问命令行参数和 `env` 变量。
已修改到同一行上。

2022-01-25 12:04 UTC, infdahai commented on docs/book/zh/src/dev/js.md
> +* [网络套接字](js/networking.md) 展示了使用 WasmEdge 网络扩展和提供的 JavaScript API 去构建 HTTP 客户端和服务端程序。
已修改

2022-01-25 12:04 UTC, infdahai commented on docs/book/zh/src/dev/go.md
> +你将在同一目录下一个名为 `hello.wasm` 文件。这是一个 WebAssembly 字节码文件。
补上了。

2022-01-25 12:05 UTC, infdahai commented on docs/book/zh/src/dev/python.md
> +
已修改，这里口胡了。

2022-01-25 12:19 UTC, infdahai commented
Ok, I will fix some errors basis on reviews.

2022-01-25 15:40 UTC, alabulei1 commented
@infdahai  Thanks for your contribution too. I finished my review. Just need to make some mirror adjustments.

2022-02-10 10:14 UTC, alabulei1 commented
@infdahai  Happy New Year! Do you have time to revise those feedback recently?

2022-02-11 07:54 UTC, infdahai commented
@alabulei1 I fix conflicts and hope you check again.

2022-02-19 17:20 UTC, alabulei1 commented on docs/book/zh/src/dev/rust.md
> +Rust 是 WebAssembly 生态系统中位居“一等公民”的编程语言之一。 WebAssembly 全部的 WasmEdge 扩展都为开发者提供 Rust APIs。在本篇中，我们将展示如何编译你的 Rust 应用到 wasm 字节码并在 WasmEdge 运行时上运行。
@infdahai  从这里开始的 comment 没有调整哈，请看一下，谢谢。

2022-03-01 05:56 UTC, infdahai commented
Ok, I will fix these problems.

2022-05-24 03:39 UTC, alabulei1 commented
@infdahai We really want to merge your PR first. Could you solve my comments and fix the conflicts?

2022-05-26 15:44 UTC, infdahai commented
OK, I will fix these.

2022-05-27 08:24 UTC, infdahai commented
Please check again. I fix some conficts based on those previous changes.

2022-05-28 03:49 UTC, alabulei1 reviewed
Hi, @infdahai  Thanks for your work. I have left some comments, please check out.

Also, I'm wondering if you need to delete the dev/rust, dev/go, and dev/python, because #1483, #1482, and #1402 have been merged. Let me know what do you think. Thanks.

2022-05-28 03:49 UTC, alabulei1 commented on docs/book/zh/src/dev/js.md
> +第三点， WasmEdge 是 [一种 OCI 兼容的容器](../kubernetes.md)。它默认安全，支持资源隔离，并且可以通过容器管理工具在单个 k8s 集群中与 Linux 容器上并行。
是 [一种 OCI 兼容的容器] 不用空格哈

2022-05-28 03:49 UTC, alabulei1 commented on docs/book/zh/src/dev/js.md
> +最后， v8 攻击面广泛，因此需要付出 [大量努力](https://blog.cloudflare.com/mitigating-spectre-and-other-security-threats-the-cloudflare-workers-security-model/) 才能使其安全运行在公共云环境上。众所周知，[许多 JavaScript 安全问题由 JIT 引起](https://
付出 [大量努力] 中文前后不用空格

公共云改成公有云吧

2022-05-29 04:27 UTC, closed without merging