[Docs] Fix the markdown errors in reference book.
WasmEdge/WasmEdge pull request #1054
Opened 2022-01-26 12:49 UTC by q82419

Signed-off-by: YiYing He <yiying@secondstate.io>

2022-01-26 13:16 UTC, juntao commented
May I ask the tool you used to reformat those md source files? Thanks!

2022-01-26 21:36 UTC, q82419 commented
> May I ask the tool you used to reformat those md source files? Thanks!

I only overview the files through the VSCode with the [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) plugin.

2022-01-28 09:18 UTC, hydai requested changes

2022-01-28 10:12 UTC, hydai approved these changes

2022-01-28 10:12 UTC, merged