[Docs] Translate dev/js/npm.md to zh finished
WasmEdge/WasmEdge pull request #1118
Opened 2022-01-30 03:37 UTC by r-asou

Signed-off-by: r-asou <aar@webassembly-cn.com>

2022-03-08 06:15 UTC, hydai requested changes

2022-03-08 06:15 UTC, hydai commented on docs/book/zh/src/dev/js/npm.md
> +执行下方的NPM命令将 [npm_main.js](https://github.com/second-state/wasmedge-quickjs/blob/main/example_js/simple_common_js_demo/npm_main.js) 示例程序构建为 `dist/npm_main.mjs`。
中英文間要空格

2022-03-08 06:15 UTC, hydai commented on docs/book/zh/src/dev/js/npm.md
> +下方展示的是如何在WasmEdge CLI中执行上方我们生成的JS文件。
中英文間要空格

2022-03-08 06:15 UTC, hydai commented on docs/book/zh/src/dev/rust.md
> +在学习这节内容前，你需要安装 [Rust](https://www.rust-lang.org/tools/install) 以及 [WasmEdge](../start/install.md)。同时，你也需要在Rust工具链中安装 `wasm32-wasi` 。命令如下所示：
中英文間要空格

2022-03-08 06:15 UTC, hydai commented on docs/book/zh/src/dev/rust.md
> +[add示例](https://github.com/second-state/wasm-learning/tree/master/cli/add) 是一个可以通过[WasmEdge CLI](../start/cli.md)以reactor模式执行的 Rust library 函数。
中英文間要空格

2022-03-08 06:15 UTC, hydai commented on docs/book/zh/src/dev/rust.md
> +当然，在大多数情况下，你们不会通过传入CLI参数来调用函数。相反，你们可能会需要使用 [WasmEdge提供的那些编程语言对应的SDK](../../embed.md) 来调用函数。传入参数，然后就能得到返回结果。下方展示的这些SDK案例就是告诉你们如何传入复杂参数并获取返回值。
中英文間要空格

2022-06-20 03:19 UTC, alabulei1 commented
Thanks for your contribution. This PR stuck here for a long time and behind lots of commits. Since #1567   has finished, so we will close your PR.

2022-06-20 03:19 UTC, closed without merging