[Docs] Translate dev/js/ssr.md to zh
WasmEdge/WasmEdge pull request #1127
Opened 2022-01-31 06:13 UTC by Megrax

Signed-off-by: Megrax <geronimooo@foxmail.com>

2022-02-01 10:00 UTC, alabulei1 commented on docs/book/zh/src/dev/js/ssr.md
> +本示例的源代码可以在 GitHub 仓库的 [example_js/react_ssr](https://github.com/second-state/wasmedge-quickjs/tree/main/example_js/react_ssr) 文件夹中找到。它展示了如何在 WasmEdge 中运行着的 JavaScript 应用程序里，编排 HTML 模板并将其渲染成 HTML 字符串。
一个讨论。它展示了 WasmEdge 运行的 JavaScript 应用程序里是如何···，这样会不会好一点？

2022-02-01 10:05 UTC, alabulei1 reviewed
Thank you! Excellent work!

2022-02-01 10:05 UTC, alabulei1 commented on docs/book/zh/src/dev/js/ssr.md
> +目录中的 [rollup.config.js](https://github.com/second-state/wasmedge-quickjs/blob/main/example_js/react_ssr/rollup.config.js) 文件和 [package.json](https://github.com/second-state/wasmedge-quickjs/blob/main
产物 --> 输出？

2022-02-01 10:05 UTC, alabulei1 commented on docs/book/zh/src/dev/js/ssr.md
> +目录中的 [rollup.config.js](https://github.com/second-state/wasmedge-quickjs/blob/main/example_js/react_ssr_stream/rollup.config.js) 文件和 [package.json](https://github.com/second-state/wasmedge-quickjs/bl
产物 --> 输出

2022-02-01 10:05 UTC, alabulei1 commented on docs/book/zh/src/dev/js/ssr.md
> +本示例的源代码可以在 GitHub 仓库的 [example_js/react_ssr_stream](https://github.com/second-state/wasmedge-quickjs/tree/main/example_js/react_ssr_stream) 文件夹中找到。它展示了如何在 WasmEdge 中运行着的 JavaScript 应用程序里，流式地把 HTML 模板
最后一句同 静态渲染。

2022-02-01 11:26 UTC, Megrax commented on docs/book/zh/src/dev/js/ssr.md
> +本示例的源代码可以在 GitHub 仓库的 [example_js/react_ssr](https://github.com/second-state/wasmedge-quickjs/tree/main/example_js/react_ssr) 文件夹中找到。它展示了如何在 WasmEdge 中运行着的 JavaScript 应用程序里，编排 HTML 模板并将其渲染成 HTML 字符串。
它展示了运行于 WasmEdge 的 JavaScript 应用程序，是如何编排 HTML 模板并将其渲染成 HTML 字符串的。

要不改成这样？

2022-02-01 11:29 UTC, Megrax commented on docs/book/zh/src/dev/js/ssr.md
> +目录中的 [rollup.config.js](https://github.com/second-state/wasmedge-quickjs/blob/main/example_js/react_ssr/rollup.config.js) 文件和 [package.json](https://github.com/second-state/wasmedge-quickjs/blob/main
构建产物会输出到……里，这样如何？

2022-02-02 03:24 UTC, alabulei1 commented on docs/book/zh/src/dev/js/ssr.md
> +本示例的源代码可以在 GitHub 仓库的 [example_js/react_ssr](https://github.com/second-state/wasmedge-quickjs/tree/main/example_js/react_ssr) 文件夹中找到。它展示了如何在 WasmEdge 中运行着的 JavaScript 应用程序里，编排 HTML 模板并将其渲染成 HTML 字符串。
赞

2022-02-02 03:24 UTC, alabulei1 commented on docs/book/zh/src/dev/js/ssr.md
> +目录中的 [rollup.config.js](https://github.com/second-state/wasmedge-quickjs/blob/main/example_js/react_ssr/rollup.config.js) 文件和 [package.json](https://github.com/second-state/wasmedge-quickjs/blob/main
OK

2022-02-02 05:32 UTC, Megrax commented
@alabulei1 Suggested changes have been applied!

2022-02-02 05:40 UTC, alabulei1 commented
LGTM. @hydai  could you help merge this PR? Thanks.

2022-02-06 14:11 UTC, hydai requested changes

2022-02-06 14:11 UTC, hydai commented on docs/book/zh/src/dev/js/ssr.md
> +结果如下所示。该服务首先返回一个HTML页面，里面包含一个空的内层部分（即 `loading` 部分）。然后在 2s 后返回内层部分的 HTML 内容，以及将它显示出来的 JavaScript 代码。
HTML 前後需要有空格

2022-02-06 14:31 UTC, hydai approved these changes

2022-02-06 14:32 UTC, merged