fix syntax
WasmEdge/WasmEdge pull request #1141
Opened 2022-02-02 06:42 UTC by pasicopan

Signed-off-by: pasicopan <pasico@163.com>

2022-02-02 13:03 UTC, alabulei1 commented
LGTM! @hydai  Could you please merge this PR?

2022-02-06 14:12 UTC, hydai requested changes

2022-02-06 14:12 UTC, hydai commented on docs/book/zh/src/dev/js/networking.md
> +QuickJS WasmEdge Runtime 支持 WasmEdge 的[网络 sockets 拓展](https://github.com/second-state/wasmedge_wasi_socket)， 所以JavaScript 程序也可以在网络上建立HTTP 连接。此文将向你展示相关的 [HTTP 客户端](https://github.com/second-state/wasm
JavaScript 跟中文字之間需要有空格

2022-02-06 14:12 UTC, hydai commented on docs/book/zh/src/dev/js/networking.md
> +WasmEdge 的 `wasi_net` 包为 JavaScript 应用提供了一种自适应的动态网络栈。在很多高级用法中，我们基于这个包，设计了很多抽象良好的API。在下一章节，我们会带着具体的常见应用，向你展示如何处理 HTTP 请求。在 [React 服务器渲染文章](ssr.md)中，我们还将会讨论一下如何基于这种异步网络的 API 来创建一个 React 服务器渲染功能。
API 與中文字間需要有空格

2022-02-06 14:12 UTC, hydai commented on docs/book/zh/src/dev/js/networking.md
> +`server_start()` 方法会启动一个监听 8000 端口的服务。当请求进来，会被传给 `handle_client()` 方法来处理。当请求是合法的HTTP 请求，对应的 handler 方法会调用 `handle_req()` 来解析对应的字段，组装新的 HTTP 应答，然后异步把应答数据发送回去。这意味着当应用发送完数据，又能继续处理下一个进来的请求了。
HTTP 與中文字之間需要有空格

2022-02-07 05:52 UTC, pasicopan commented
@hydai 谢谢提醒，已经修改好了，麻烦检查。

2022-02-07 05:58 UTC, hydai approved these changes

2022-02-07 06:00 UTC, merged