translate the kubernetes/cri/crio.md to zh
WasmEdge/WasmEdge pull request #1144
Opened 2022-02-02 14:13 UTC by villanel

Signed-off-by: villanel <56783950+villanel@users.noreply.github.com>
#1072

2022-02-03 16:39 UTC, alabulei1 reviewed
Great! Thanks for your contribution!

2022-02-03 16:39 UTC, alabulei1 commented on docs/book/zh/src/kubernetes/cri/crio.md
> +这需要添加到两个配置文件来完成的。
可以把 的 去掉？

2022-02-03 16:39 UTC, alabulei1 commented on docs/book/zh/src/kubernetes/cri/crio.md
> +接下来，我们需要创建两个简单的配置文件，指定CRI-O 应该如何在 sandbox 中运行这个 WebAssembly 镜像。 我们已经有了那两个文件 [container_wasi.json](https://github.com/second-state/wasmedge-containers-examples/blob/main/crio/container_wasi.json) 和 [s
改成我们已经有 XXX 和 XXX 这两个文件？

2022-02-03 16:39 UTC, alabulei1 commented on docs/book/zh/src/kubernetes/cri/crio.md
> +# 创建 POD。输出示例将会不同。
输出会与示例不同？

2022-02-03 16:39 UTC, alabulei1 commented on docs/book/zh/src/kubernetes/cri/crio.md
> +# 创建容器实例。输出将会示例不同。
会-- > 与？

2022-02-03 16:39 UTC, alabulei1 commented on docs/book/zh/src/kubernetes/cri/crio.md
> +接下来，我们需要创建两个简单的配置文件，指定CRI-O 应该如何在 sandbox 中运行这个 WebAssembly 镜像。 我们已经有了那两个文件  [container_http_server.json](https://raw.githubusercontent.com/second-state/wasmedge-containers-examples/main/crio/http_se
我们已经有 XXX 和 XXX 两个文件，同上

2022-02-03 16:39 UTC, alabulei1 commented on docs/book/zh/src/kubernetes/cri/crio.md
> +# 创建 POD。输出示例将会不同。
输出与示例

2022-02-03 16:39 UTC, alabulei1 commented on docs/book/zh/src/kubernetes/cri/crio.md
> +# 创建容器实例。输出将会示例不同。
会-->与

2022-02-03 16:39 UTC, alabulei1 commented on docs/book/zh/src/kubernetes/cri/crio.md
> +# 检查容器的日志以查看 HTTP 服务器正在侦听端口为1234。
侦听 --> 监听？

2022-02-03 16:39 UTC, alabulei1 commented on docs/book/zh/src/kubernetes/cri/crio.md
> +现在你可以使用 CRI-O 使用指定的配置创建一个 pod 和一个容器。
这里我有一点点疑问，明天回复，谢谢！

2022-02-04 02:47 UTC, alabulei1 reviewed
@villanel Great! Thank you for your contribution

2022-02-04 02:47 UTC, alabulei1 commented on docs/book/zh/src/kubernetes/cri/crio.md
> +现在你可以使用 CRI-O 使用指定的配置创建一个 pod 和一个容器。
现在你可以用 CRI-O 创建 pod 和容器。只需用本文的配置选项即可。 这样感觉通顺一些？

2022-02-04 03:36 UTC, villanel commented
@alabulei1  Thank you for your reply, I have fixed it.

2022-02-04 08:33 UTC, alabulei1 commented on docs/book/zh/src/kubernetes/cri/crio.md
> +# 创建 POD。输出示例将会不同。
这里好像没改过来？

2022-02-05 09:54 UTC, alabulei1 commented
LGTM! @hydai  Could you help merge this PR?

2022-02-06 15:48 UTC, hydai requested changes

2022-02-06 15:48 UTC, hydai commented on docs/book/zh/src/kubernetes/cri/crio.md
> +>在运行下一步之前，请确保你已经构建并安装好了[支持 `WasmEdge`的 `crun`二进制文件](../container/crun.md)。
`WasmEdge` 後面跟中文字間要有空白， `crun` 也是

2022-02-06 15:48 UTC, hydai commented on docs/book/zh/src/kubernetes/cri/crio.md
> +`crun` 运行时在`/etc/crio/crio.conf.d/01-crio-runc.conf` 文件中定义，按下面的内容修改此文件。
`/etc/...` 的前面跟中文字應該有空白

2022-02-06 15:48 UTC, hydai commented on docs/book/zh/src/kubernetes/cri/crio.md
> +接下来，我们需要创建两个简单的配置文件，指定CRI-O 应该如何在 sandbox 中运行这个 WebAssembly 镜像。 我们已经有 [container_wasi.json](https://github.com/second-state/wasmedge-containers-examples/blob/main/crio/container_wasi.json) 和 [sandbox
`CRI-O` 的前面跟中文字應該有空白

2022-02-06 15:48 UTC, hydai commented on docs/book/zh/src/kubernetes/cri/crio.md
> +接下来，你可尝试在 [Kubernetes](../../kubernetes/kubernetes.md)中运行这个应用!
`[Kubernetes]` 的後面跟中文字應該有空白

2022-02-06 15:48 UTC, hydai commented on docs/book/zh/src/kubernetes/cri/crio.md
> +接下来，我们需要创建两个简单的配置文件，指定CRI-O 应该如何在 sandbox 中运行这个 WebAssembly 镜像。 我们已经有 [container_http_server.json](https://raw.githubusercontent.com/second-state/wasmedge-containers-examples/main/crio/http_server/co
`CRI-O` 的前面跟中文字應該有空白
`[sandbox_config.json]...` 的後面跟中文字應該有空白

2022-02-06 15:48 UTC, hydai commented on docs/book/zh/src/kubernetes/cri/crio.md
> +> HTTP 服务端示例和 WASI 简单示例使用的`sandbox_config.json` 文件是相同的。 但另一个 `container_*.json` 文件是特定的，因为它包含应用程序的 Docker Hub 链接。
`sandbox_config.json` 的前面跟中文字應該有空白

2022-02-06 15:48 UTC, hydai commented on docs/book/zh/src/kubernetes/cri/crio.md
> +# 检查容器的日志以查看 HTTP 服务器正在监听端口为1234。
`1234` 數字跟中文字間應有空白

2022-02-06 15:48 UTC, hydai commented on docs/book/zh/src/kubernetes/cri/crio.md
> +接下来，你可尝试在 [Kubernetes](../../kubernetes/kubernetes.md)中运行这个应用!
`[Kubernetes]...` 的後面跟中文字應該有空白

2022-02-09 07:29 UTC, hydai approved these changes

2022-02-09 07:30 UTC, merged