[Docs] Translate embed/node.md to zh
WasmEdge/WasmEdge pull request #1152
Opened 2022-02-05 15:07 UTC by Vinson-Ben

Signed-off-by: Vinson <muffinxb@163.com>

2022-02-05 16:01 UTC, alabulei1 reviewed
Thank you for your contribution!

2022-02-05 16:01 UTC, alabulei1 commented on docs/book/zh/src/embed/node.md
> +最简单的启动方式就是使用 Docker 来搭建开发环境。只需要[克隆这个模板工程](https://github.com/second-state/wasmedge-nodejs-starter/)到你的电脑，然后运行如下 Docker 命令：
克隆这个模板 就可以了

2022-02-05 16:01 UTC, alabulei1 commented on docs/book/zh/src/embed/node.md
> +> WasmEdge Runtime 需要最新版本的 `libstdc++`。 Ubuntu 20.04 LTS 已经有最新的库了。 如果你使用的是比较老的 Linux 发行版中，[有一些选项需要升级](/articles/ubuntu-req-ssvm-20200715/)。
这里也是英文原文有些问题，有一些选项需要升级，链接的是 https://www.secondstate.io/articles/ubuntu-req-ssvm-20200715/

2022-02-08 16:12 UTC, alabulei1 reviewed
Great! You only need to revise a small word.

2022-02-08 16:12 UTC, alabulei1 commented on docs/book/zh/src/embed/node.md
> +# 安装 Node.js and npm
and 没有翻译

2022-02-08 16:12 UTC, alabulei1 commented on docs/book/zh/src/embed/node.md
> +> WasmEdge Runtime 需要最新版本的 `libstdc++`。 Ubuntu 20.04 LTS 已经有最新的库了。 如果你使用的是比较老的 Linux 发行版中，有一些选项需要升级，链接的是[https://www.secondstate.io/articles/ubuntu-req-ssvm-20200715/](https://www.secondstate.io/arti
改成 [更详细的信息在这儿](https://www.secondstate.io/articles/ubuntu-req-ssvm-20200715/) 吧

2022-02-09 11:22 UTC, alabulei1 commented
LGTM!

@hydai  Could you help merge this PR?

2022-02-09 11:28 UTC, hydai requested changes

2022-02-09 11:28 UTC, hydai commented on docs/book/zh/src/embed/node.md
> +# 安装 Node.js and npm
`and` 應該翻譯為 `與`

2022-02-09 11:28 UTC, hydai commented on docs/book/zh/src/embed/node.md
> +> WasmEdge Runtime 需要最新版本的 `libstdc++`。 Ubuntu 20.04 LTS 已经有最新的库了。 如果你使用的是比较老的 Linux 发行版中，有一些选项需要升级，链接的是[https://www.secondstate.io/articles/ubuntu-req-ssvm-20200715/](https://www.secondstate.io/arti
這個也沒修正

2022-02-09 11:41 UTC, Vinson-Ben commented on docs/book/zh/src/embed/node.md
> +# 安装 Node.js and npm
> `and` 應該翻譯為 `與`

这里翻译成 `和` 可以不？

2022-02-09 11:41 UTC, hydai commented on docs/book/zh/src/embed/node.md
> +# 安装 Node.js and npm
也可以

2022-02-09 11:41 UTC, Vinson-Ben commented on docs/book/zh/src/embed/node.md
> +> WasmEdge Runtime 需要最新版本的 `libstdc++`。 Ubuntu 20.04 LTS 已经有最新的库了。 如果你使用的是比较老的 Linux 发行版中，有一些选项需要升级，链接的是[https://www.secondstate.io/articles/ubuntu-req-ssvm-20200715/](https://www.secondstate.io/arti
done

2022-02-10 15:30 UTC, alabulei1 commented
@hydai I think the PR is ready to merge. Thanks.

2022-02-11 00:42 UTC, hydai approved these changes

2022-02-11 00:43 UTC, merged