[Doc] Translate kubernetes-containerd.md to zh. Fix #1099
WasmEdge/WasmEdge pull request #1194
Opened 2022-02-10 03:45 UTC by Bevisy

* [Docs] Translate kubernetes-containerd.md to zh.

Signed-off-by: Binbin Zhang <binbin36520@gmail.com>

2022-02-10 06:28 UTC, Bevisy commented
PTAL @alabulei1

2022-02-13 08:09 UTC, alabulei1 reviewed
Thanks! please check out my feedback!

2022-02-13 08:09 UTC, alabulei1 commented on docs/book/zh/src/kubernetes/kubernetes/kubernetes-containerd.md
> +我们将假设你已经 [安装并配置了containerd](../cri/containerd.md)，以便与 WasmEdge 容器镜像一起工作。
10和11 是一行

2022-02-13 08:09 UTC, alabulei1 commented on docs/book/zh/src/kubernetes/kubernetes/kubernetes-containerd.md
> +从终端窗口运行以下命令。
15 和 16 也是一行。从终端窗口运行以下命令，为本地开发设置了 Kubernetes。

2022-02-13 08:09 UTC, alabulei1 commented on docs/book/zh/src/kubernetes/kubernetes/kubernetes-containerd.md
> +由于我们在`kubectl run`命令中使用了`hostNetwork`，HTTP 服务器镜像运行在本地网络上，IP 地址是`127.0.0.1`。
代码块前后空一格。

2022-02-13 08:09 UTC, alabulei1 commented on docs/book/zh/src/kubernetes/kubernetes/kubernetes-containerd.md
> +现在，你可以使用`curl`命令来访问 HTTP 服务。
代码块前后空一格

2022-02-14 02:52 UTC, Bevisy commented on docs/book/zh/src/kubernetes/kubernetes/kubernetes-containerd.md
> +我们将假设你已经 [安装并配置了containerd](../cri/containerd.md)，以便与 WasmEdge 容器镜像一起工作。
Thanks, fixed now

2022-02-14 03:26 UTC, Bevisy commented
> 

Thanks for your review, all the problems pointed out above have been fixed. PTAL

2022-02-16 15:42 UTC, hydai requested changes

2022-02-16 15:42 UTC, hydai commented on docs/book/zh/src/kubernetes/kubernetes/kubernetes-containerd.md
> +在本节的其余部分，我们将详细解释这些步骤。我们将假设你已经 [安装并配置了containerd](../cri/containerd.md)，以便与 WasmEdge 容器镜像一起工作。
`已经 [安装并配置了containerd]` -> `已经[安装并配置了 containerd]`

2022-02-17 02:34 UTC, Bevisy commented on docs/book/zh/src/kubernetes/kubernetes/kubernetes-containerd.md
> +在本节的其余部分，我们将详细解释这些步骤。我们将假设你已经 [安装并配置了containerd](../cri/containerd.md)，以便与 WasmEdge 容器镜像一起工作。
Fixed. Thanks

2022-02-19 17:10 UTC, alabulei1 commented
@hydai  I think it's ready to merge this PR.

2022-02-21 08:28 UTC, hydai approved these changes

2022-02-21 08:29 UTC, merged