[Docs] Translate embed/go/ref.md to zh. (#1092)
WasmEdge/WasmEdge pull request #1198
Opened 2022-02-10 07:35 UTC by swartz-k

fix #1092 

Signed-off-by: swartz-k <9215868@gmail.com>

2022-02-16 16:06 UTC, alabulei1 commented
@swartz-k  Thanks for your contribution! You really did a lot of work. I couldn't load the file now. Could you check out my comments firstly?

2022-02-20 14:10 UTC, swartz-k commented
> @swartz-k Thanks for your contribution! You really did a lot of work. I couldn't load the file now. Could you check out my comments firstly?

Rebased lateset commit!

2022-02-21 16:53 UTC, alabulei1 commented
@swartz-k  I will check out tomorrow.

2022-02-22 13:36 UTC, alabulei1 reviewed
@swartz-k Thanks for your contribution. Please check out my comments.

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +在 WasmEdge 中运行 WebAssembly 函数的 [Golang源码](https://github.com/second-state/WasmEdge-go-examples/blob/master/go_BindgenFuncs/bindgen_funcs.go) 如下。`ExecuteBindgen()` 函数调用 WebAssembly 函数并在 `wasm-bindgen`
Golang  后面空一格。

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +        // 尽可能优化小代码大小，而不会触发显着的编译时间增量或执行时间减慢。
这里没改哈

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +        // 尽可能优化小代码大小。
这里也没改哈

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +这个例子使用了 [fibonacci.wasm](../tools/wasmedge/examples/fibonacci.wasm)，对应的 WAT 文件在 [fibonacci.wat](../tools/wasmedge/examples/fibonacci.wat) .
. 应该是 。 不用空一格

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +### 主机模块注册
主机还是不翻译？

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +[host 函数](https://webassembly.github.io/spec/core/exec/runtime.html#syntax-hostfunc) 是 WebAssembly 之外的函数，并作为导入传递给 WASM 模块。 在 WasmEdge-go 中，host 函数被组合成宿主模块作为带有模块名称的 `ImportObject` 对象。详情请参考 [WasmEdge R
主机改成 Host，还是不翻译？

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +       ```去
这里应该是 go 吧

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +    ```去
这里应该是 go

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +### 主机函数
Host 不翻译？

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +[主机函数](https://webassembly.github.io/spec/core/exec/runtime.html#syntax-hostfunc) 是 WebAssembly 之外的函数，并作为导入传递给 WASM 模块。
Host 不翻译？

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +    添加 2 个 `i32` 值的 `add` 主机函数示例：
Host 应该不翻译？

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +1. 主机功能分配
Host 不翻译？

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +2. 导入object对象
object 应该去掉

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +    // 创建一个表实例并将其添加到导出名称为“table”的导入对象中。
table 前后空一格

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +        // 创建模块名称为“extern”的导入对象。
“extern” 前后空一格

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +        // 创建一个函数实例并将其添加到导出名称为“func-add”的导入对象中。
“func-add” 空一格

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +    $去构建
去构建应该是 go build

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +    // 宿主函数体定义。
host 不翻译

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +        // 要设置到主机函数中的附加数据。
host 不翻译

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +        var 数据 int32 = 0
这里是代码，不用改翻译

数据 data

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +        // 创建模块名称为“extern”的导入对象。
“extern” 前后空一格

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +        // 创建一个函数实例并将其添加到导出名称为“func-add”的导入对象中。
“func-add” 前后空一格

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +在本部分中，我们将介绍 WasmEdge AOT 编译器和 Go 中的选项。
这一行和下面的两行不应该断行，是一行。

2022-02-22 13:36 UTC, alabulei1 commented on docs/book/zh/src/embed/go/ref.md
> +详情请参考 [AOT 编译器选项配置](#Configurations)。
[AOT 编译器选项配置](#Configurations) 如果括号里的英文修改了，那括号里应该是中文。

2022-02-27 14:42 UTC, alabulei1 commented
LGTM.

@swartz-k  thanks for your contribution.

@hydai  Could you help merge this PR?

2022-03-08 06:19 UTC, hydai requested changes
There are some problems from the previous feedback are not fixed. Please check the unresolved parts and fix them.

2022-03-08 06:39 UTC, swartz-k commented
> There are some problems from the previous feedback are not fixed. Please check the unresolved parts and fix them.

I had fix. But cannot find solved button. Please check it.

2022-03-08 06:50 UTC, hydai requested changes

2022-03-08 06:50 UTC, hydai commented on docs/book/zh/src/embed/go/ref.md
> +    // 创建存储对象。store 是 WASM 运行时结构的核心。
這個沒處理

2022-03-08 06:50 UTC, hydai commented on docs/book/zh/src/embed/go/ref.md
> +    // 不需要。
這個沒處理

2022-03-08 06:50 UTC, hydai commented on docs/book/zh/src/embed/go/ref.md
> +    // 并且通过了验证。
這個沒處理

2022-03-08 06:50 UTC, hydai commented on docs/book/zh/src/embed/go/ref.md
> +        // 注册时实例化。
這個沒處理

2022-03-08 06:50 UTC, hydai commented on docs/book/zh/src/embed/go/ref.md
> +        // 使用模块名称“mod”将 WASM 模块从文件注册到 VM。
這個沒處理

2022-03-08 06:50 UTC, hydai commented on docs/book/zh/src/embed/go/ref.md
> +	  pagesize := conf.GetMaxMemoryPage()
縮排錯了

2022-03-08 06:50 UTC, hydai commented on docs/book/zh/src/embed/go/ref.md
> +   WasmEdge 支持打开或关闭 WebAssembly proposals。
這個沒處理

2022-03-08 07:37 UTC, swartz-k commented
[docs/book/zh/src/embed/go/ref.md](https://github.com/WasmEdge/WasmEdge/pull/1198/files/5493f5ea4b39371c2e6e40908c4857da15df9a96#diff-64955e120ccd4eed3eb4a094695acd65bbbd8a3211554f1eabd404aaf56e9a24)

```
1. 配置

   WasmEdge 支持打开或关闭 WebAssembly proposals。

```

Sorry. I don't get how to deal with it.

2022-03-08 08:07 UTC, hydai commented
<img width="1192" alt="截圖 2022-03-08 at 16 06 41@2x" src="https://user-images.githubusercontent.com/2776756/157193577-dd2331ee-edf4-4c06-9c7c-f0c860441362.png">
Looks like the review system is not shown the details?

2022-03-08 08:09 UTC, swartz-k commented
> <img alt="截圖 2022-03-08 at 16 06 41@2x" width="1192" src="https://user-images.githubusercontent.com/2776756/157193577-dd2331ee-edf4-4c06-9c7c-f0c860441362.png">
> 
> Looks like the review system is not shown the details?

Right. I fix them. Thanks~

2022-05-23 10:21 UTC, alabulei1 commented
@hydai I think we could merge this PR now. All the comments have been solved.

2022-05-29 04:19 UTC, hydai commented
> @hydai I think we could merge this PR now. All the comments have been solved.

Got it. Sorry for missing this PR.

2022-05-29 04:19 UTC, hydai approved these changes

2022-05-29 04:20 UTC, merged