[WIP][Docs] Translate embed/go/memory.md to zh
WasmEdge/WasmEdge pull request #1199
Opened 2022-02-10 07:41 UTC by Bevisy

translate embed/go/memory.md to zh

Fix #1091

Signed-off-by: Binbin Zhang <binbin36520@gmail.com>

2022-02-10 08:15 UTC, Bevisy commented
PTAL @alabulei1 @MileyFu

2022-02-13 08:52 UTC, alabulei1 reviewed
Thanks for your contribution! There are two things we should take care of.
1. Add a space between code blocks.
2. Translate the noes in the code blocks.

2022-02-13 08:52 UTC, alabulei1 commented on docs/book/zh/src/embed/go/memory.md
> +此类复杂的调用参数和返回值包括字符串和字节数组等动态内存结构。
3 4 5 都是一行。

2022-02-13 08:52 UTC, alabulei1 commented on docs/book/zh/src/embed/go/memory.md
> +> 在 WebAssembly 中向 Rust 函数传递和返回复杂值的另一种方法是使用`wasm-bindgen`编译器工具。你可以[在这里了解更多](bindgen.md).
代码块前后空格

2022-02-13 08:52 UTC, alabulei1 commented on docs/book/zh/src/embed/go/memory.md
> +[Go SDK 应用程序](https://github.com/second-state/WasmEdge-go-examples/blob/master/go_MemoryGreet/greet_memory.go)必须从 WasmEdge 虚拟机中调用`allocate`以获得一个指向字符串参数的指针。
61 62 63 都是一行，然后代码块前后空格

2022-02-13 08:52 UTC, alabulei1 commented on docs/book/zh/src/embed/go/memory.md
> +> 编译 WebAssembly 程序需要`main()`为空，才能正确设置 WASI。
代码块前后空格

2022-02-13 08:52 UTC, alabulei1 commented on docs/book/zh/src/embed/go/memory.md
> +  // Allocate memory for the subject, and get a pointer to it.
这些注释也翻译一下吧

2022-02-13 08:52 UTC, alabulei1 commented on docs/book/zh/src/embed/go/memory.md
> +[Go SDK 应用程序](https://github.com/second-state/WasmEdge-go-examples/blob/master/go_MemoryGreetTinyGo/greet_memory.go)必须从 WasmEdge 虚拟机中调用`malloc`以获得一个指向字符串参数的指针。
205 206 207 应该是一行吧，代码块要空格哈

2022-02-13 08:52 UTC, alabulei1 commented on docs/book/zh/src/embed/go/memory.md
> +  // Allocate memory for the subject, and get a pointer to it.
注释也翻译一下

2022-02-13 08:52 UTC, alabulei1 commented on docs/book/zh/src/embed/go/memory.md
> +函数 "fibArray "接收一个数组作为调用参数，并将其填入
这应该都是一行

2022-02-13 08:52 UTC, alabulei1 commented on docs/book/zh/src/embed/go/memory.md
> +函数 "fibArray "接收一个数组作为调用参数，并将其填入
fibArray 这里应该是代码块吧

2022-02-14 03:22 UTC, Bevisy commented
> Thanks for your contribution! There are two things we should take care of.
> 
> 1. Add a space between code blocks.
> 2. Translate the noes in the code blocks.

@alabulei1 Thanks for your review, I have reworked the translation according to the review comments, and added all the code comments to the translation.

2022-02-19 17:05 UTC, alabulei1 commented
@Bevisy  LGTM! Only one place needs to be changed. Please check out.

2022-02-22 09:42 UTC, Bevisy commented
> @Bevisy LGTM! Only one place needs to be changed. Please check out.

@alabulei1 Thanks, but can you mark where there are still changes to be made?
<!-- (Because I wanted to try a longer translation, I picked up this translation task in the translation task list.) -->

2022-02-22 13:07 UTC, alabulei1 commented
> > @Bevisy LGTM! Only one place needs to be changed. Please check out.
> 
> @alabulei1 Thanks, but can you mark where there are still changes to be made?

@Bevisy Sure. 第246行，英文字母前后空一格

2022-02-22 13:40 UTC, Bevisy commented
> > > @Bevisy LGTM! Only one place needs to be changed. Please check out.
> > 
> > 
> > @alabulei1 Thanks, but can you mark where there are still changes to be made?
> 
> @Bevisy Sure. 第246行，英文字母前后空一格

Sorry actually forgot the `NULL` word in the comment, has been fixed now, thanks a lot.

2022-02-22 13:50 UTC, alabulei1 commented
> > > > @Bevisy LGTM! Only one place needs to be changed. Please check out.
> > > 
> > > 
> > > @alabulei1 Thanks, but can you mark where there are still changes to be made?
> > 
> > 
> > @Bevisy Sure. 第246行，英文字母前后空一格
> 
> Sorry actually forgot the `NULL` word in the comment, it's fixed now. Thanks a lot.

@Bevisy please also add a space between `NULL` in lines 237, 104, 95. Sorry for missing.

2022-02-22 13:54 UTC, Bevisy commented
> > > > > @Bevisy LGTM! Only one place needs to be changed. Please check out.
> > > > 
> > > > 
> > > > @alabulei1 Thanks, but can you mark where there are still changes to be made?
> > > 
> > > 
> > > @Bevisy Sure. 第246行，英文字母前后空一格
> > 
> > 
> > Sorry actually forgot the `NULL` word in the comment, it's fixed now. Thanks a lot.
> 
> @Bevisy please also add a space between `NULL` in lines 237, 104, 95. Sorry for missing them.

Done 😄

2022-02-23 09:23 UTC, Bevisy commented
@alabulei1 重新修改了标点符号，将部分句号“。”修改成冒号“：”，分别为 line 3、50、140等共13处，规范标点符号使用。
参考：https://teachinghand.com/chinese-punctuation-guide/。

PTAL @hydai

2022-02-24 14:39 UTC, alabulei1 commented
LGTM! @Bevisy Thanks for your contribution.

@hydai  Could you help merge this PR?

2022-02-24 16:43 UTC, hydai requested changes

2022-02-24 16:43 UTC, hydai commented on docs/book/zh/src/embed/go/memory.md
> +[Go SDK 应用程序](https://github.com/second-state/WasmEdge-go-examples/blob/master/go_AccessMemory/run.go)必须从 WasmEdge 虚拟机中调用 `allocate` ，以获得一个指向数组的指针。然后它将调用Rust中的`fib_array()`函数并传入指针。在函数返回后，Go应用程序将使用 Wa
中英文間應有空格隔開

2022-02-25 02:09 UTC, Bevisy commented on docs/book/zh/src/embed/go/memory.md
> +[Go SDK 应用程序](https://github.com/second-state/WasmEdge-go-examples/blob/master/go_AccessMemory/run.go)必须从 WasmEdge 虚拟机中调用 `allocate` ，以获得一个指向数组的指针。然后它将调用Rust中的`fib_array()`函数并传入指针。在函数返回后，Go应用程序将使用 Wa
Thanks, fixed now.

2022-02-28 02:37 UTC, Bevisy commented
If there is nothing else that needs to be modified, I hope to be able to merge it as soon as possible, thank you! @hydai

2022-03-08 06:22 UTC, hydai approved these changes

2022-03-08 06:23 UTC, merged