add blog: WasmEdge + OpenYurt
WasmEdge/WasmEdge pull request #1210
Opened 2022-02-10 10:15 UTC by JcJinChen

add en blog : Wasmedge + OpenYurt

2022-02-10 10:17 UTC, hydai requested changes

2022-02-10 10:17 UTC, hydai commented on docs/book/en/src/kubernetes/kubernetes/openyurt.md
> +|        | OS/kernel                            | 私网IP/公网IP                |
`私网IP/公网IP` should be translated to english

2022-02-10 11:01 UTC, JcJinChen commented on docs/book/en/src/kubernetes/kubernetes/openyurt.md
> +|        | OS/kernel                            | 私网IP/公网IP                |
OK, i will fix it.

2022-02-13 06:33 UTC, JcJinChen commented
@hydai I have updated this pr. Please review it.

2022-02-13 07:43 UTC, hydai requested changes
中英文之間應該要使用空格隔開，例如：`檢查 pod 的狀態`

2022-02-15 10:35 UTC, hydai requested changes

2022-02-15 10:35 UTC, hydai commented on docs/book/zh/src/kubernetes/kubernetes/openyurt.md
> +在这篇文章中，我们将介绍如何在 [OpenYurt](https://github.com/openyurtio/openyurt)  边缘计算框架下，使用containerd去运行一个简单的WasmEdge的demo。
中英文之前都要加空白

2022-02-15 10:35 UTC, hydai commented on docs/book/zh/src/kubernetes/kubernetes/openyurt.md
> +这个kubernetes集群转化为OpenYurt集群；
Ditto.

2022-02-15 10:35 UTC, hydai commented on docs/book/zh/src/kubernetes/kubernetes/openyurt.md
> +因为我们使用`yurtctl convert`命令将K8s集群转化成OpenYurt集群，因此我们应该首先搭建一个 kubernetes 集群。当然， OpenYurt 也提供了一个简单的方法， `yurtctl init/join` 可以允许我们不搭建 kubernetes 集群，直接创建一个 OpenYurt 集群出来。
Ditto.

2022-02-15 10:35 UTC, hydai commented on docs/book/zh/src/kubernetes/kubernetes/openyurt.md
> +更多关于 `yurtctl convert/revert` 的介绍可以参考文章[Conversion between OpenYurt and Kubernetes:`yurtctl convert/revert`](https://openyurt.io/docs/installation/yurtctl-convert-revert) ，
Ditto.

2022-02-15 10:35 UTC, hydai commented on docs/book/zh/src/kubernetes/kubernetes/openyurt.md
> +使用 WasmEdge 提供的[安装脚本](https://wasmedge.org/book/en/start/install.html) 在你的边缘节点上安装WasmEdge。
Ditto.

2022-02-15 10:35 UTC, hydai commented on docs/book/zh/src/kubernetes/kubernetes/openyurt.md
> +下面，我们将介绍一种快速搭建OpenYurt集群的方法，你只需要在OpenYurt体验中心注册一个账户，就可以拥有一个OpenYurt集群。如果你想接入一个边缘节点到你创建的OpenYurt集群中，
Ditto.

2022-02-15 10:35 UTC, hydai commented on docs/book/zh/src/kubernetes/kubernetes/openyurt.md
> +根据提示使用 `yurtctl join` 命令即可。更多关于OpenYurt体验中心的介绍，可以参考[文章](https://github.com/openyurtio/openyurt/releases/tag/v0.6.0)
Ditto.

2022-02-15 10:35 UTC, hydai commented on docs/book/zh/src/kubernetes/kubernetes/openyurt.md
> +在验证 OpenYurt 上运行 WasmEdge 应用的时候，我们参考了之前关于[kubernetes的验证](https://wasmedge.org/book/en/kubernetes/kubernetes.html) ，
Ditto.

2022-02-15 10:35 UTC, hydai commented on docs/book/zh/src/kubernetes/kubernetes/openyurt.md
> + WebAssembly 的容器镜像感兴趣，可以阅读[WasmEdge Book](https://wasmedge.org/book/en/kubernetes/demo/wasi.html)
Ditto.

2022-02-15 11:02 UTC, JcJinChen commented
@hydai thanks for your feedback. I have fixed these typos.Please check out again.

2022-02-15 11:03 UTC, hydai approved these changes
LGTM. Thanks for your contribution

2022-02-15 11:05 UTC, merged