[Misc] Replace `std::unordered_map` of enum and string to `DenseMap` or `SpareMap`
WasmEdge/WasmEdge pull request #1250
Opened 2022-02-17 08:59 UTC by ibmibmibm

Use `std::array` to store mapping for compact and fast lookup

2022-02-17 10:22 UTC, hydai requested changes

2022-02-17 10:22 UTC, hydai commented on include/common/dense_enum_map.h
> +  using const_iterator = Iterator;
Should this be `const Iterator`?

2022-02-17 12:33 UTC, q82419 commented
The `common/enum_configure.h`, `common/enum_errcode.h`, and `common/enum_types.h` are headers which also exported for API use.
In these case, if we want to use the `DenseMap` or `ShareMap`, we should package the header together, or the building will fail if developers use C++ to link our WasmEdge C API library.

2022-02-18 03:13 UTC, ibmibmibm commented on include/common/dense_enum_map.h
> +  using const_iterator = Iterator;
Changed to `ConstIterator`.

2022-02-18 03:16 UTC, hydai requested changes

2022-02-18 03:16 UTC, hydai commented on lib/api/CMakeLists.txt
> +  ${CMAKE_CURRENT_BINARY_DIR}/../../include/api/wasmedge/spare_enum_map.h.h
Why `.h.h`?

2022-02-18 06:29 UTC, ibmibmibm commented on lib/api/CMakeLists.txt
> +  ${CMAKE_CURRENT_BINARY_DIR}/../../include/api/wasmedge/spare_enum_map.h.h
Fixed.

2022-02-21 08:34 UTC, hydai approved these changes

2022-02-21 08:40 UTC, merged