[Docs] book/zh/src/embed/rust.md
WasmEdge/WasmEdge pull request #1287
Opened 2022-02-26 02:50 UTC by Kodalien

Signed-off-by: kodalien <kkodalien@gmail.com>

2022-02-28 02:15 UTC, alabulei1 commented
LGTM! Thanks for your contribution. @Kodalien 

@hydai Could you help merge this PR? Thanks.

2022-03-01 06:59 UTC, hydai requested changes

2022-03-01 06:59 UTC, hydai commented on docs/book/zh/src/embed/rust.md
> +WasmEdge Rust SDK 涉及两个 Rust crate [wasmedge-sys](https://crates.io/crates/wasmedge-sys) 和 [wasmedge-rs](https://crates.io/crates/wasmedge- sdk），它们根据不同的原则和不同的目的设计。 wasmedge-sys crate 定义了一组低级 Rust API，
連結有誤，多了空格：`https://crates.io/crates/wasmedge- sdk`

2022-03-01 06:59 UTC, hydai commented on docs/book/zh/src/embed/rust.md
> +WasmEdge Rust SDK 涉及两个 Rust crate [wasmedge-sys](https://crates.io/crates/wasmedge-sys) 和 [wasmedge-rs](https://crates.io/crates/wasmedge- sdk），它们根据不同的原则和不同的目的设计。 wasmedge-sys crate 定义了一组低级 Rust API，
`低級` -> `底層`

2022-03-01 06:59 UTC, hydai commented on docs/book/zh/src/embed/rust.md
> +* [wasmedge-sys](https://crates.io/crates/wasmedge-sys) crate 定义了一组底层 Rust API，其仅仅是对 WasmEdge C API 进行封装，以提供相应的安全接口。 [wasmedge-sys](https://crates.io/crates/wasmedge-sys) 更适合作为基础库，为面向应用的更高层Rust库提供服务。
Rust 前後要加空白

2022-03-08 06:24 UTC, hydai approved these changes

2022-03-08 06:25 UTC, merged