[Rust] Refactored the build script for publishing
WasmEdge/WasmEdge pull request #1296
Opened 2022-03-03 13:03 UTC by apepkuss

This PR is to refactor the build script and the Cargo.toml file for building and publishing docs on docs.rs.

2022-03-03 15:19 UTC, apepkuss commented
Hi @hydai, could you please help review this PR? Thanks a lot!

2022-03-03 15:22 UTC, hydai requested changes

2022-03-03 15:22 UTC, hydai commented on bindings/rust/wasmedge-sys/README.md
> +The [wasmedge-sys](https://crates.io/crates/wasmedge-sys) crate defines a group of low-level Rust APIs, which simply wrap WasmEdge C APIs and provide the safe counterparts. It it recommended that the
Please check the grammar.

2022-03-04 14:02 UTC, hydai approved these changes

2022-03-04 15:21 UTC, merged