Refactor the store and the module instance.
WasmEdge/WasmEdge pull request #1365
Opened 2022-03-23 17:52 UTC by q82419

- [v] Move the ownership of the instances from the store manager to the module instance.
- [v] Merge the import object into the module instance.
- [v] Invoke functions by the function instance instead of by function name in executor.
- [v] Refactor the WasmEdge C API.
- [ ] Update the tests.
- [ ] Add the `Upgrade to 0.10.0` guideline.
- [ ] Update the C API document.
- [ ] Update the rust binding.

2022-03-24 02:15 UTC, apepkuss commented
> Details

@q82419 Thanks for the reminder. I checked the number of the refactored C-APIs, and it would be better to launch a separate PR to migrate rust bindings after merging this PR. Currently, the failed binding-rust workflows can be ignored.

2022-03-24 02:25 UTC, apepkuss commented
Is it possible to expose the following two APIs?
- Statistics.clear()
- StoreManager.reset()

In addition, I noticed that in the current design `Executor` provides the APIs for registering `ASTModule` and `ImportObject`. Is it possible to move the registering APIs from `Executor` to `Store`? So that in the scenario, like multiple threading, we can only `move` or `share` a store between threads. I'm not very sure if the idea is appropriate or not in real practice.

2022-03-24 06:08 UTC, q82419 commented
> Is it possible to expose the following two APIs?
> 
> * Statistics.clear()
> * StoreManager.reset()
> 
> In addition, I noticed that in the current design `Executor` provides the APIs for registering `ASTModule` and `ImportObject`. Is it possible to move the registering APIs from `Executor` to `Store`? So that in the scenario, like multiple threading, we can only `move` or `share` a store between threads. I'm not very sure if the idea is appropriate or not in real practice.

For the statistics: ok, I'll expose later.
For the store manager: in the current PR, the ownership is moved into the module instance, developers should keep and handle the module instance by themselves. The store manager only record the module exporting for linking when instantiation. I think it's not necessary to implement the reset function. By the way, it's better to remove the export info in the store manager when a named module being destroyed. I'll update for this.

It's not appropriate to move the registering APIs from the `Executor` to `Store`. The `Store` means the object to handle the instances for searching and module linking, and the `Executor` is the object to instantiate and register WASM modules.

2022-03-24 07:15 UTC, apepkuss commented
> > Is it possible to expose the following two APIs?
> > 
> > * Statistics.clear()
> > * StoreManager.reset()
> > 
> > In addition, I noticed that in the current design `Executor` provides the APIs for registering `ASTModule` and `ImportObject`. Is it possible to move the registering APIs from `Executor` to `Store`? So that in the scenario, like multiple threading, we can only `move` or `share` a store between threads. I'm not very sure if the idea is appropriate or not in real practice.
> 
> For the statistics: ok, I'll expose later. For the store manager: in the current PR, the ownership is moved into the module instance, developers should keep and handle the module instance by themselves. The store manager only record the module exporting for linking when instantiation. I think it's not necessary to implement the reset function. By the way, it's better to remove the export info in the store manager when a named module being destroyed. I'll update for this.
> 
> It's not appropriate to move the registering APIs from the `Executor` to `Store`. The `Store` means the object to handle the instances for searching and module linking, and the `Executor` is the object to instantiate and register WASM modules.

@q82419 Thanks for the explanation.

2022-04-11 06:20 UTC, ibmibmibm requested changes

2022-04-11 06:23 UTC, ibmibmibm requested changes

2022-04-11 06:23 UTC, ibmibmibm commented on include/runtime/instance/module.h
> +  using StoreCallback = void(StoreManager *Store, const ModuleInstance *Mod);
`noexcept`

2022-04-11 06:23 UTC, ibmibmibm commented on include/runtime/instance/module.h
> +      Pair.second(Pair.first, this);
`assuming(Pair.second);`

2022-04-11 06:28 UTC, ibmibmibm requested changes

2022-04-11 06:28 UTC, ibmibmibm commented on include/runtime/storemgr.h
> +                             const Instance::ModuleInstance *Inst) {
`noexcept`

2022-04-11 09:28 UTC, q82419 commented on include/runtime/storemgr.h
> +                             const Instance::ModuleInstance *Inst) {
added.

2022-04-12 04:17 UTC, apepkuss commented
Hi @q82419

Here is a scenario that the current design of `Vm` could fail to cover. The scenario is 

1. Create a host function and a `Table` instance; then, store the reference to the host function at some index of the table instance.
2. Create a `ModuleInstance` instance, and add the table instance (created in step 1) into the module instance. 
3. Create a `Vm` instance, then register the module instance (created in step 2).

After the steps above, we can get the internal store of the vm instance, and then get the table instance via the returned store, and then get the function reference to the host function via the table instance, but how to call the host function via the function reference?

2022-04-12 08:05 UTC, apepkuss commented
@q82419 Thanks for the reply! I'll append the explanation for the scenario in the API doc. Thanks again!

2022-04-18 04:53 UTC, ibmibmibm requested changes

2022-04-18 04:53 UTC, ibmibmibm commented on include/runtime/instance/module.h
> +                   std::unique_ptr<Instance::FunctionInstance> &Func) {
should use `&&`, and merge with next function.

2022-04-18 04:53 UTC, ibmibmibm commented on lib/executor/executor.cpp
> +    return std::move(*Res);
`return Res;`

2022-04-18 04:53 UTC, ibmibmibm commented on lib/executor/executor.cpp
> +    return std::move(*Res);
`return Res;`

2022-04-18 04:53 UTC, ibmibmibm commented on lib/executor/instantiate/global.cpp
> +    Runtime::Instance::GlobalInstance *GlobInst =
`const auto Index = ModInst.getGlobalNum() - 1;`

2022-04-18 04:59 UTC, ibmibmibm requested changes

2022-04-18 04:59 UTC, ibmibmibm commented on lib/executor/instantiate/module.cpp
> +  if (auto Res = instantiate(StoreMgr, *ModInst.get(), ImportSec); !Res) {
why not `*ModInst`?

2022-04-18 04:59 UTC, ibmibmibm commented on test/api/APIUnitTest.cpp
> +WasmEdge_ASTModuleContext *loadModule
`[[maybe_unused]] WasmEdge_ASTModuleContext *loadModule(...)`

2022-04-18 08:57 UTC, q82419 commented on test/api/APIUnitTest.cpp
> +WasmEdge_ASTModuleContext *loadModule
Removed.

2022-04-18 08:57 UTC, q82419 commented on lib/executor/instantiate/module.cpp
> +  if (auto Res = instantiate(StoreMgr, *ModInst.get(), ImportSec); !Res) {
Fixed.

2022-04-18 08:58 UTC, q82419 commented on lib/executor/executor.cpp
> +    return std::move(*Res);
Fixed.

2022-04-18 08:58 UTC, q82419 commented on lib/executor/instantiate/global.cpp
> +    Runtime::Instance::GlobalInstance *GlobInst =
Updated.

2022-04-18 23:31 UTC, ibmibmibm approved these changes

2022-04-21 02:44 UTC, merged