[Rust SDK] wasmedge-sdk v0.1.0
WasmEdge/WasmEdge pull request #1453
Opened 2022-05-15 14:06 UTC by apepkuss

In this PR `wasmedge-sdk` comes with `v0.1.0`.

2022-05-16 01:45 UTC, apepkuss commented
@hydai Please help review this PR, thanks a lot!

2022-05-16 01:49 UTC, apepkuss commented
@hydai 
One more thing, this PR should be merged after the core 0.10.0 and the sys 0.7.0 are officially released, as `wasmedge-sdk` in this PR has to refine the `wasmedge-sys` dep in its `Cargo.toml`.

2022-05-19 15:15 UTC, hydai requested changes

2022-05-19 15:45 UTC, apepkuss commented on bindings/rust/wasmedge-sdk/src/vm.rs
> +// use crate::{
Accepted. Thanks a lot!

2022-05-19 15:52 UTC, apepkuss commented on bindings/rust/wasmedge-sdk/README.md
> +The [wasmedge-sdk](https://crates.io/crates/wasmedge-sdk) crate defines a group of high-level Rust APIs, which are used to build up business applications.
The motivation for adding this link is just to provide a one-click jump for the readers to direct them to the crate page on crates.io, where the readers can find the necessary information like how to import the crate into their projects and where the API reference is. Thanks a lot!

2022-05-19 17:54 UTC, hydai requested changes

2022-05-19 17:54 UTC, hydai commented on bindings/rust/wasmedge-sdk/src/config.rs
> +    runtim_config: Option<RuntimeConfigOptions>,
`runtime`

2022-05-19 17:54 UTC, hydai commented on bindings/rust/wasmedge-sdk/src/module.rs
> +                // module: &self,
Redundant comment.

2022-05-19 17:54 UTC, hydai commented on bindings/rust/wasmedge-sdk/src/module.rs
> +                // module: &self,
Ditto.

2022-05-20 01:51 UTC, apepkuss commented on bindings/rust/wasmedge-sdk/src/config.rs
> +    runtim_config: Option<RuntimeConfigOptions>,
Accepted. Thanks!

2022-05-20 01:52 UTC, apepkuss commented on bindings/rust/wasmedge-sdk/src/module.rs
> +                // module: &self,
Accepted. Thanks!

2022-05-20 01:52 UTC, apepkuss commented on bindings/rust/wasmedge-sdk/src/module.rs
> +                // module: &self,
Accepted. Thanks!

2022-05-20 09:09 UTC, hydai approved these changes

2022-05-20 12:53 UTC, merged

2022-05-20 14:17 UTC, apepkuss commented
@hydai Thanks for the review!