Using WasmEdge C_API and Thread Proposal to Accelerate Compute-Intensive Workload
WasmEdge/WasmEdge pull request #1499
Opened 2022-05-26 08:01 UTC by eee4017

2022-05-26 10:11 UTC, hydai requested changes

2022-05-26 10:11 UTC, hydai commented on examples/capi/WasmEdge-Mandelbrot-Example/Makefile
> +	clang-12 -O3 --no-standard-libraries --target=wasm32 -c -o $@ $^
Do we need a specific version of clang?

2022-05-26 10:11 UTC, hydai commented on examples/capi/WasmEdge-Mandelbrot-Example/main.cc
> +#include <wasmedge/wasmedge.h>
Please follow the same coding style.

2022-05-31 07:22 UTC, q82419 commented
Please rebase to the updated `proposal/threads`. Thanks.

2022-06-14 04:42 UTC, closed without merging

2022-06-14 04:44 UTC, hydai commented
Hi @eee4017 
Please raise another PR to the master directly. We have merged the threads proposal into master.