[Rust] Support async C-APIs.
WasmEdge/WasmEdge pull request #1512
Opened 2022-05-31 15:40 UTC by apepkuss

In this PR, the following async C-APIs are supported in `wasmedge-sys`:

- WasmEdge_AsyncCancel
- WasmEdge_AsyncDelete
- WasmEdge_AsyncGet
- WasmEdge_AsyncGetReturnsLength
- WasmEdge_AsyncWait
- WasmEdge_AsyncWaitFor
- WasmEdge_VMAsyncExecute
- WasmEdge_VMAsyncExecuteRegistered
- WasmEdge_VMAsyncRunWasmFromASTModule
- WasmEdge_VMAsyncRunWasmFromBuffer
- WasmEdge_VMAsyncRunWasmFromFile

The version of `wasmedge-sys` comes to `v.0.7.1`.

2022-06-07 07:17 UTC, hydai requested changes

2022-06-07 07:21 UTC, apepkuss commented on bindings/rust/wasmedge-sys/examples/vm_run_registered_func_async.rs
> +    let ok = async_result.wait_for(900);
Accepted. Will fix the comment. Thanks a lot!

2022-06-07 07:26 UTC, hydai commented on bindings/rust/wasmedge-sys/src/vm.rs
> +        std::thread::sleep(std::time::Duration::from_millis(100));
Because I found there are several `long` in the comments, however, every `long` is not the same haha.

2022-06-08 05:21 UTC, hydai approved these changes

2022-06-08 16:17 UTC, merged

2022-06-09 07:09 UTC, apepkuss commented
@hydai Thanks for the review.