[Rust] Fixed a bug related to wasi module initialization
WasmEdge/WasmEdge pull request #1609
Opened 2022-06-29 15:31 UTC by apepkuss

This PR fixed #1580.

2022-06-29 15:31 UTC, apepkuss commented
Hi @hydai, could you please help review this PR? Thanks a lot!

2022-06-29 16:38 UTC, hydai commented
The failure on macos is related to #1610.

2022-06-30 02:32 UTC, hydai requested changes

2022-06-30 02:32 UTC, hydai commented on bindings/rust/wasmedge-sys/src/instance/module.rs
> +        // let preopens_len = preopens.len();
Should we remove these comment?

2022-06-30 02:32 UTC, hydai commented on bindings/rust/wasmedge-sys/src/instance/module.rs
> +        // let cmds_len = cmds.len();
Ditto.

2022-06-30 02:41 UTC, apepkuss commented on bindings/rust/wasmedge-sys/examples/wasi_print_env.rs
> +    // let envs = vec!["hello=world", "ENV2=VAL2"];
Accepted. Thanks!

2022-06-30 02:42 UTC, apepkuss commented on bindings/rust/wasmedge-sys/src/instance/module.rs
> +        // let preopens_len = preopens.len();
Accepted. Thanks!

2022-06-30 02:43 UTC, apepkuss commented on bindings/rust/wasmedge-sys/src/instance/module.rs
> +        // let cmds_len = cmds.len();
Accepted. Thanks!

2022-06-30 02:58 UTC, hydai commented
Since I merged the #1602 first, please resolve the conflicts.

2022-06-30 03:08 UTC, apepkuss commented
> Since I merged the #1602 first, please resolve the conflicts.

Rebased on the latest master branch. Thanks!

2022-06-30 03:25 UTC, hydai approved these changes

2022-06-30 05:16 UTC, merged

2022-06-30 05:33 UTC, apepkuss commented
@hydai Thanks for the review!