[WIP] [Docker] Release DockerSlim images
WasmEdge/WasmEdge pull request #1627
Opened 2022-07-06 09:10 UTC by dm4

- Build release images using DockerSlim 
- Push release images to DockerHub
- Tested on my own fork: https://github.com/dm4/WasmEdge/actions/runs/2621583921

2022-07-08 08:12 UTC, hydai requested changes

2022-07-08 08:21 UTC, dm4 commented on utils/docker/Dockerfile.release
> +    curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -p /usr/local -e all -v $VERSION
Okay, I'll try to use:
```
on:
  release:
    types: [published]
```
to trigger another workflow to build release images.

2022-07-08 09:49 UTC, dm4 commented on utils/docker/Dockerfile.release
> +    curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -p /usr/local -e all -v $VERSION
Add new workflow `.github/workflows/release-published.yml` triggered by release published events.

2022-07-11 07:30 UTC, hydai approved these changes

2022-07-11 09:34 UTC, merged