Fix uninitialized variable warning
WasmEdge/WasmEdge pull request #1642
Opened 2022-07-12 09:36 UTC by RichardAH

Hi WasmEdge team

We're building WasmEdge statically inside another existing build system and this system is using `-Werror=uninitialized`.  As a result we're getting an error at the two lines fixed by this commit. We could hot patch in the build engine but better to PR this. Thanks! 😇

2022-07-12 09:42 UTC, hydai requested changes

2022-07-12 09:42 UTC, RichardAH commented on lib/aot/compiler.cpp
> +        uint64_t Index{0};
Sure I will change it now :)

2022-07-12 09:49 UTC, hydai submitted a review, later dismissed
Good catch! Thanks.

2022-07-12 09:50 UTC, hydai commented
I missed the DCO check. Could you please sign your commit with DCO: https://www.secondstate.io/articles/dco/

2022-07-13 05:17 UTC, hydai approved these changes

2022-07-13 05:17 UTC, merged

2022-07-13 05:18 UTC, hydai commented
Thanks!