[Rust] Supported CallingFrame and User-defined Error Code
WasmEdge/WasmEdge pull request #1787
Opened 2022-08-24 02:28 UTC by apepkuss

Rust bindings introduced a new design to support CallingFrame and user-defined error code in this PR.

The relevant issues are

- #1730 
- #1758

2022-08-24 04:17 UTC, apepkuss commented
Hi @hydai

The `binding-rust/Windows` workflow here failed, but I tried it again on my side, and it worked correctly (see the snapshot below). Could we ignore the failure? In addition, `wasmedge-sdk-release` and `wasmedge-sys-release` workflows failed as the dependencies are not published on `crates.io`. Thanks a lot!

<img width="830" alt="image" src="https://user-images.githubusercontent.com/4726889/186327264-7dcaff2f-57b3-41bb-b13f-85003e40a24c.png">

2022-08-26 07:04 UTC, L-jasmine commented
https://github.com/WasmEdge/WasmEdge/pull/1783

2022-08-26 07:12 UTC, hydai commented
@apepkuss 
Just a few questions:
1. You can remove the `Test WasmEdge part` in the rust workflow. If the `WasmEdge unit test` failed, that is not related to the rust binding.
2. The `wasmedge_c` is renamed to `wasmedge`, due to #1783 .
3. Should we use a related path in the development environment? And if we want to release it, then use a tag. Not sure if this is a best practice of the rust development process.

2022-08-26 07:12 UTC, apepkuss commented
> #1783
> 
> Change the name of C API library from `libwasmedge_c.so` to `libwasmedge.so`.
> 
> So `build.rs` need update.

Thanks for the reminder. Will refactor `build.rs` and support the change in this PR. Thanks!

2022-08-26 07:15 UTC, hydai commented
Hold on. I found the error message of the `rust-*-release` is:
```
  failed to select a version for the requirement `wasmedge-types = "^0.2.1"`
  candidate versions found which didn't match: 0.2.0, 0.1.3, 0.1.2, ...
```

Oops, do we forget to release some existed versions?

2022-08-26 07:24 UTC, apepkuss commented
> Hold on. I found the error message of the `rust-*-release` is:
> 
> ```
>   failed to select a version for the requirement `wasmedge-types = "^0.2.1"`
>   candidate versions found which didn't match: 0.2.0, 0.1.3, 0.1.2, ...
> ```
> 
> Oops, do we forget to release some existed versions?

It's the correct error message. When the release workflows conduct `cargo publish --dry-run`, they will search their dependencies on `crates.io`, but for that moment, the dependencies of the correct versions (`wasmedge-sys` and `wasmedge-types`) are still not published onto `crates.io`. So the error message tells us this info. We can ignore it now.

2022-08-26 10:21 UTC, hydai commented
Hi @apepkuss 
Just another change: #1801 
After considering the previous naming style, I change the CAPI name of `WasmEdge_CompilerCompileFromArray` to `WasmEdge_CompilerCompileFromBuffer`. 

So there should be one more thing that needs to update. Thanks.

2022-08-26 13:31 UTC, apepkuss commented
@hydai The changes in #1801 have been supported in this PR. BTW, the new `inventory` workflow works correctly, many thanks for the help!

2022-08-29 15:08 UTC, hydai requested changes

2022-08-29 15:44 UTC, apepkuss commented on .github/workflows/rust-wasmedge-types-release.yml
> +      - name: Dry run wasmedge-types crate
I'll add a branch trigger so that there are two triggers: one for performing the `dry-run` command, one for publishing crate.

2022-08-29 15:45 UTC, hydai commented on .github/workflows/rust-wasmedge-types-release.yml
> +      - name: Dry run wasmedge-types crate
But you don't set the `if` condition, it just runs before the `publish` one.

2022-08-29 16:03 UTC, hydai approved these changes

2022-08-29 17:43 UTC, merged

2022-08-30 02:31 UTC, apepkuss commented
@hydai Thanks for the review!