Zhou/refinehttpsreq
WasmEdge/WasmEdge pull request #1802
Opened 2022-08-26 14:46 UTC by 2019zhou

https://github.com/WasmEdge/WasmEdge/issues/1763
https://github.com/WasmEdge/WasmEdge/issues/1768
https://github.com/WasmEdge/WasmEdge/issues/1788

2022-08-26 15:09 UTC, hydai commented
Just a tip: Use `git-clang-format` to fix the format issue automatically. :-)

2022-08-29 13:06 UTC, hydai requested changes

2022-09-01 04:28 UTC, hydai requested changes

2022-09-01 04:28 UTC, hydai commented on plugins/wasmedge_httpsreq/httpsreqfunc.cpp
> +  const char *Host = MemInst->getPointer<char *>(HostPtr);
`<char *>` -> `<const char *>`

2022-09-01 04:28 UTC, hydai commented on plugins/wasmedge_httpsreq/httpsreqfunc.cpp
> +  const char *Body = MemInst->getPointer<char *>(BodyPtr);
`<char *>` -> `<const char *>`

2022-09-01 04:28 UTC, hydai commented on plugins/wasmedge_httpsreq/httpsreqfunc.cpp
> +    spdlog::error("{}", strerror(Err));
The output format is not the same as the previous ones.

2022-09-01 04:34 UTC, 2019zhou commented
done

2022-09-01 04:36 UTC, hydai requested changes

2022-09-01 04:36 UTC, hydai commented on plugins/wasmedge_httpsreq/httpsreqfunc.cpp
> +    spdlog::error("[WasmEdge Httpsreq] {}", gai_strerror(Err));
You remind me that we should use `WasmEdge` not `Wasmedge` in other places. Please check it again.

2022-09-01 05:25 UTC, hydai approved these changes
LGTM. @q82419 PTAL

2022-09-01 07:31 UTC, q82419 approved these changes

2022-09-01 07:39 UTC, merged

2022-09-01 07:40 UTC, hydai commented
@q82419 Since most issues are fixed, should we add the `httpsreq` to the pre-built plugin list?