[Examples]: Add wasi-crypto example.
WasmEdge/WasmEdge pull request #1817
Opened 2022-09-03 15:01 UTC by MediosZ

Solve #1680 
Signed-off-by: Tricster <mediosrity@gmail.com>

2022-09-07 14:13 UTC, hydai requested changes
This PR should have a README to tell how to build, how to execute, and what's the expected output of this example.

2022-09-08 00:17 UTC, MediosZ commented
Ok, I will try to add one.

2022-09-08 04:40 UTC, hydai requested changes
Because this example only showed some signature-related functions, I suggest that the name should change to wasi-crypto-signature for better meaning.

2022-09-08 04:40 UTC, hydai commented on examples/plugin/wasi-crypto/README.md
> +This example should run successfully and print out the signatures.
Is the output the same every time? If so, please post the execution output for users to check if the result is exactly matched.

2022-09-08 09:35 UTC, MediosZ commented
I change the name of this example to `wasi-crypto-signature`. This is ok cause I only have signature related examples.
I believe we can have a different repo for `wasi-crypto` rust bindings like `wasmedge_wasi_socket`, this will be useful for developers who want to use `wasi-crypto` in rust and WasmEdge.

2022-09-12 17:05 UTC, hydai approved these changes
LGTM

2022-09-19 14:33 UTC, merged