WIP: load module in component isn't trivial
WasmEdge/WasmEdge pull request #1822
Opened 2022-09-05 09:07 UTC by dannypsnl

Signed-off-by: Lîm Tsú-thuàn <dannypsnl@secondstate.io>

2022-09-06 10:52 UTC, hydai approved these changes
LGTM. @q82419 PTAL

2022-09-06 19:30 UTC, q82419 requested changes
In `include/common/configure.h`:

In the constructor of the `Configure` class, we only add the proposals which are already merged into the WASM spec. Please remove the component-model proposal here.

2022-09-07 06:26 UTC, dannypsnl commented
@q82419 I would remove it in `proposal/component-model` branch

2022-09-08 04:12 UTC, q82419 approved these changes

2022-09-08 04:49 UTC, merged