Change log to release 0.8.0.
WasmEdge/WasmEdge pull request #191
Opened 2021-05-05 17:28 UTC by q82419

2021-05-05 17:29 UTC, q82419 commented
Need to add the shared library into `cpack`.

2021-05-06 10:25 UTC, hydai requested changes

2021-05-06 10:25 UTC, hydai commented on Changelog.md
> +
Since we make several breaking changes in this release. We should have a `Breaking Changes:` section to specify these changes.

2021-05-11 08:04 UTC, hydai approved these changes

2021-05-11 08:04 UTC, merged