[Misc] Move mmap calls to separate library
WasmEdge/WasmEdge pull request #194
Opened 2021-05-07 10:55 UTC by ibmibmibm

2021-05-10 13:49 UTC, q82419 requested changes
I think the `system/allocator.h` can be moved into `common/allocator.h`.
And the `system/config.h.in` can be merged into `common/config.h.in`.
And the `wasmedgeSystem` can be merged into `wasmedgeCommon`.

2021-05-12 22:26 UTC, ibmibmibm commented
> 
> 
> I think the `system/allocator.h` can be moved into `common/allocator.h`.
> And the `system/config.h.in` can be merged into `common/config.h.in`.
> And the `wasmedgeSystem` can be merged into `wasmedgeCommon`.
I don't think I should, because these class is for different operating system environment, and the header file is for private use only.

2021-05-13 06:02 UTC, hydai submitted a review, later dismissed
I think the allocator should have a standalone component `System`. This is not related to the `Common` component.

2021-05-13 06:21 UTC, hydai approved these changes

2021-05-13 06:22 UTC, merged