[WASI]: Make epoll edge triggered.
WasmEdge/WasmEdge pull request #1975
Opened 2022-10-17 03:56 UTC by MediosZ

Addressing #1974 
Signed-off-by: Tricster <mediosrity@gmail.com>

2022-11-01 02:31 UTC, hydai requested changes

2022-11-01 02:31 UTC, hydai commented on include/host/wasi/inode.h
> +  explicit constexpr FdHolder(int Fd, bool cleanup = true) noexcept
The first character of the variables should be upper cases.

2022-11-01 02:31 UTC, hydai commented on include/host/wasi/inode.h
> +  bool cleanup = true;
Ditto.

2022-11-01 02:31 UTC, hydai commented on include/host/wasi/environ.h
> +  auto evepoller =
Ditto.

2022-11-01 02:31 UTC, hydai commented on lib/host/wasi/inode-linux.cpp
> +  auto events = EPollEvent.events;
Ditto.

2022-11-01 02:31 UTC, hydai commented on lib/host/wasi/inode-linux.cpp
> +  auto events = EPollEvent.events;
Ditto.

2022-11-01 02:31 UTC, hydai commented on lib/host/wasi/inode-linux.cpp
> +  for (auto pair : Registration) {
Ditto.

2022-11-01 02:31 UTC, hydai commented on lib/host/wasi/inode-linux.cpp
> +  for (auto fd : Difference) {
Ditto.

2022-11-01 03:10 UTC, hydai approved these changes

2022-11-01 03:50 UTC, merged

2022-11-04 08:34 UTC, q82419 commented
Close #1974