[Rust] Implemented new APIs for Memory and Config.
WasmEdge/WasmEdge pull request #1985
Opened 2022-10-18 09:24 UTC by apepkuss

In this PR, new APIs are introduced into `Memory` and `Config`. In addition, the `bindings-rust` workflow is refactored.

2022-10-18 09:41 UTC, hydai requested changes

2022-10-18 09:41 UTC, hydai commented on .github/workflows/bindings-rust.yml
> +    name: Ubuntu-20.04 && Ubuntu-22.04
I think you can use `Ubuntu` only.

2022-10-18 11:16 UTC, apepkuss commented on .github/workflows/bindings-rust.yml
> +    name: Ubuntu-20.04 && Ubuntu-22.04
Accepted. Will refactor it. Thanks!

2022-10-19 02:36 UTC, apepkuss commented
@hydai The review issue has been fixed. Please help review the revision. Thanks!

2022-10-19 07:08 UTC, hydai approved these changes

2022-10-19 09:09 UTC, hydai approved these changes

2022-10-19 10:34 UTC, merged

2022-10-19 10:34 UTC, apepkuss commented
@hydai Thanks for the review!