[Package] Add the header and shared library of SSVM C API into the output package
WasmEdge/WasmEdge pull request #199
Opened 2021-05-11 08:00 UTC by hydai

2021-05-11 08:10 UTC, q82419 requested changes

2021-05-11 19:47 UTC, q82419 requested changes

2021-05-11 19:47 UTC, q82419 commented on lib/api/CMakeLists.txt
> +  DESTINATION ${CMAKE_INSTALL_LIBDIR}
`LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}`
`PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}`

2021-05-12 15:39 UTC, ibmibmibm approved these changes

2021-05-13 04:32 UTC, q82419 approved these changes

2021-05-13 04:32 UTC, merged