[WIP][OSPP][Java SDK] Java SDK Async API
WasmEdge/WasmEdge pull request #1990
Opened 2022-10-19 01:09 UTC by yyy1000

I have finished the Async API code, doc, and unit tests.
It also includes the Java SDK code rebased changes from [kenvi](https://github.com/kenvifire/WasmEdge).
The roadmap is in [Kenvi's PR](https://github.com/WasmEdge/WasmEdge/pull/435)

2022-10-25 05:28 UTC, hydai commented
Hi @yyy1000 
We already merged @kenvifire 's PR. Please rebase to the latest master.

2022-10-25 08:45 UTC, dannypsnl commented
The PR of Java SDK gets merged, would you mind rebasing on the new changes? I would start reviewing this PR recently.

2022-10-25 11:19 UTC, yyy1000 commented
> I would start reviewing this PR recently, and can I close #1873?

Yes, you can close it.

2022-10-26 01:54 UTC, yyy1000 commented
> Hi @yyy1000 We already merged @kenvifire 's PR. Please rebase to the latest master.

Hi, @kenvifire and I have rebased the latest master, you can continue to review this PR. Maybe you can merge before the end of this month (to meet the deadline for this activity) and I will continue to contribute to this Java SDK. 😀

2022-10-26 08:37 UTC, hydai commented
Hi @yyy1000 I believe the rebase is totally wrong. There are so many duplicated commits. Because we squashed the commits in the previous PR, you may need to move your commits on the current master.

2022-10-27 14:59 UTC, kenvifire commented
@hydai 

> Hi @yyy1000 I believe the rebase is totally wrong. There are so many duplicated commits. Because we squashed the commits in the previous PR, you may need to move your commits on the current master.

My bad, I didn't notice that you squashed the commits. Removed duplicates now, please take a look. Thanks.

2022-10-28 02:35 UTC, kenvifire commented
By the way, I turned off macOS test in this MR. It's been flaky recently on CI and never happens on my Mac, and I'll continue investigating it.

2022-10-28 04:45 UTC, dannypsnl requested changes

2022-10-28 04:45 UTC, dannypsnl commented on bindings/java/wasmedge-jni/lib/WasmEdgeVM.c
>  }
misc: eof

2022-10-28 04:48 UTC, dannypsnl commented
@kenvifire Would you like to provide your macOS machine information? Like system version & CPU.

Another thing is we have the head format for `*.c/cpp`, would you mind adding them?
```
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2019-2022 Second State INC
```

2022-10-28 05:38 UTC, kenvifire commented
> @kenvifire Would you like to provide your macOS machine information? Like system version & CPU.
> 
> 
> 
> Another thing is we have the head format for `*.c/cpp`, would you mind adding them?
> 
> ```
> 
> // SPDX-License-Identifier: Apache-2.0
> 
> // SPDX-FileCopyrightText: 2019-2022 Second State INC
> 
> ```

I can create a separate pull request for this. However, yyy1000 is doing this feature under an open source activity and the deadline is this Sunday. Would you mind merge this PR
first?

2022-10-28 07:14 UTC, hydai commented
Sure, I think we can merge it first and fix these minor issues later.

2022-10-28 08:25 UTC, hydai approved these changes

2022-10-28 08:27 UTC, merged