feat: support read sn and read s33
WasmEdge/WasmEdge pull request #2030
Opened 2022-10-30 18:39 UTC by little-willy

In our current code of file manager, we have two method, `readS32` and `readS64`, which both read a variable length integer from the file. Actually, they seems to share the same read logic as described in [sN](https://webassembly.github.io/spec/core/binary/values.html#binary-int). Besides, as proposed in #2029, we may support reading `s33`, which also share the same read logic. 

Therefore, in this PR, I support reading `sN` as described in [sN](https://webassembly.github.io/spec/core/binary/values.html#binary-int), where N becomes a static constant template variable, and enables static usage check to ensure correctness. `readS32`, `readS64` and `readS33` are simply specialization of `readSN`.

2022-10-30 20:18 UTC, juntao commented
Hi @little-willy 

Thank you for your contribution!

CNCF requires its projects to have DCO signatures for all contributions. Do you mind fixing the DCO on your commits? Thank you!

https://www.secondstate.io/articles/dco/

2022-11-04 07:50 UTC, q82419 requested changes
Can you help to fix the loading of block type [here](https://github.com/WasmEdge/WasmEdge/blob/master/lib/loader/ast/instruction.cpp#L188)?

Thanks!

2022-11-04 07:50 UTC, q82419 commented on lib/loader/filemgr.cpp
> +  // succeeded reading offset will be at the start of `Name`.
This line is not necessary to be changed.

2022-11-04 07:50 UTC, q82419 commented on lib/loader/filemgr.cpp
> +// "include/loader/filemgr.h".
This line is not necessary to be changed.

2022-11-04 07:54 UTC, q82419 requested changes

2022-11-04 07:54 UTC, q82419 commented on lib/loader/filemgr.cpp
> +    if (auto Res = readByte(); unlikely(!Res)) {
Please use the `testRead(1)` and `Byte = Data[Pos++]` mechanism as the origin code.
This is for printing the correct error message of the loading offset when error occurs.

2022-11-06 10:01 UTC, little-willy commented
@q82419 Thanks for reviewing. I have fixed the comment and added unit tests for `readS33`. PTAL.

> Can you help to fix the loading of block type [here](https://github.com/WasmEdge/WasmEdge/blob/master/lib/loader/ast/instruction.cpp#L188)?

Can I include this fix in a later PR that will fix #2029 totally and merge this PR first?

2022-11-06 20:27 UTC, q82419 approved these changes

2022-11-06 20:28 UTC, q82419 commented
> @q82419 Thanks for reviewing. I have fixed the comment and added unit tests for `readS33`. PTAL.
> 
> > Can you help to fix the loading of block type [here](https://github.com/WasmEdge/WasmEdge/blob/master/lib/loader/ast/instruction.cpp#L188)?
> 
> Can I include this fix in a later PR that will fix #2029 totally and merge this PR first?

Sure.
Thanks for your contribution!

2022-11-07 06:42 UTC, merged