[WASI-NN] Integrate the OpenVINO runtime
WasmEdge/WasmEdge pull request #2094
Opened 2022-11-17 11:44 UTC by spencergotowork

Support WasmEdge build integrates OpenVINO.
1. ubuntu build & ci
2. manylinux2014 build  & ci 
3. macos build & ci (there was a problem running the test, cause related problem is WIP)

Plugin loading issues(#2070 ) on macos occur during testing, but wasm files can be executed. windows is also having problems with plugin loading errors. And the code running on windows causes more problems, I am fixing it and plan to publish it on other PR.
The C++ section of this code has been modified in order to compile.

Reference 
[For Linux platforms](https://github.com/WasmEdge/WasmEdge/pull/1988)

2022-11-17 15:25 UTC, hydai requested changes

2022-11-17 15:25 UTC, hydai commented on .github/workflows/build-extensions.yml
> +          # - name: WASI-Crypto
If you want to comment out something, you must leave the reason in the comments.

2022-11-17 15:25 UTC, hydai commented on .github/workflows/build-extensions.yml
> +          ls -l tools/wasmedge/wasmedge
Why do you need to list the content of the folder `tools/wasmedge/wasmedge`?

2022-11-17 15:25 UTC, hydai commented on CMakeLists.txt
> +if(WASMEDGE_BUILD_PLUGINS AND WASMEDGE_BUILD_SHARED_LIB)
Why do you change the ordering of the plugins?

2022-11-17 15:25 UTC, hydai commented on plugins/wasi_nn/wasinnfunc.cpp
> +    *GraphId = uint32_t(Env.NNGraph.size() - 1);
Use `static_cast` instead.

2022-11-17 15:25 UTC, hydai commented on plugins/wasi_nn/wasinnfunc.cpp
> +    *Context = uint32_t(Env.NNContext.size() - 1);
Ditto.

2022-11-17 15:25 UTC, hydai commented on test/plugins/wasi_nn/CMakeLists.txt
> +  PUBLIC
Why do you change this to `PUBLIC`?

2022-11-17 15:25 UTC, hydai commented on utils/wasi-nn/install-openvino.sh
> +  # export PATH=$PATH:/opt/python/cp38-cp38/bin
Why does this comment out?

2022-11-21 06:04 UTC, q82419 commented
Please fix your sign-off to pass the DCO.

2022-11-21 09:19 UTC, hydai commented
@spencergotowork 
That's because you are trying to contain others' commits. Could you please use `rebase` instead of `merge` to avoid this issue?

2023-06-14 12:40 UTC, hydai commented
Hi @spencergotowork 
Sorry for the delay response. I didn't notice this PR because it keeps draft status.
Do you still want to update this with rebasing to the latest master?

2023-06-14 12:50 UTC, hydai commented
That will be awesome. Please let me know if you need any help.

2024-05-22 08:25 UTC, q82419 commented
WASI-NN plugin and the CI have changed a lot.
Close this and please create another PR for the changes.

2024-05-22 08:25 UTC, closed without merging