refactor: use optional ValType for validator VType
WasmEdge/WasmEdge pull request #2097
Opened 2022-11-19 16:19 UTC by little-willy

Our current `VType` in the validator  is almost the same as the ValType, except that we use `VType::Unknown` to mark the unreachable type. In this PR, we remove the enum class definition of `VType`, and replace it with a `typedef std::optional<ValType>` so that the `ValType` can be reused. When `VType` has no value, it means the original `VType::Unknown`.

fix #2096. part of #2081

2022-11-24 07:03 UTC, q82419 requested changes

2022-11-24 14:02 UTC, little-willy commented on lib/validator/formchecker.cpp
> +              // Have to check is `ValType::Unknown` occured for the case of
Fixed. Thanks for pointing out.

2022-11-25 11:48 UTC, q82419 approved these changes

2022-11-28 12:18 UTC, little-willy commented
@q82419 Can we get this PR merged?

2022-11-29 11:19 UTC, merged