feat: support loading the instructions extended from the function references proposal
WasmEdge/WasmEdge pull request #2125
Opened 2022-11-28 12:06 UTC by little-willy

after #2124

2023-04-13 11:22 UTC, q82419 requested changes

2023-04-13 11:22 UTC, q82419 commented on lib/loader/ast/instruction.cpp
> +             Code == OpCode::Return_call_ref) {
Not to add the `Return_call_ref` in this condition.
The `Return_call_ref` case will be blocked in this statement and always not run into the condition below.

2023-04-13 11:22 UTC, q82419 commented on lib/loader/ast/instruction.cpp
> +    }
You can add the `tail-call` condition for the `Return_call_ref` OpCode.

2023-04-17 03:22 UTC, q82419 commented
Hi @little-willy ,
Can you help to update this PR? Thanks.

2023-04-17 19:58 UTC, little-willy commented
@q82419 Comments are addressed. PTAL

2023-04-18 04:47 UTC, q82419 commented
> @q82419 Comments are addressed. PTAL

The Loader test failed. Please fix it. Thanks.

2023-04-19 20:41 UTC, little-willy commented
> The Loader test failed. Please fix it. Thanks.

@q82419 It seems that the test fails in some platforms while succeeds in others. Do you have any idea what causes this failure?

2023-04-19 22:32 UTC, little-willy commented
@q82419 I have fixed the unit test. It is caused by not checking the reference type proposal when we load heap type. But this bug seems to be independent to platforms and should fail in all platforms. Do you know why the CI can succeed in some platforms?

2023-04-23 13:04 UTC, q82419 commented
> @q82419 I have fixed the unit test. It is caused by not checking the reference type proposal when we load heap type. But this bug seems to be independent to platforms and should fail in all platforms. Do you know why the CI can succeed in some platforms?

The Windows and MacOS CI are set as continue-on-failed for tests because the WASI will fail on these platforms.
For the previous error, you can find that the same tests failed on these platforms with the log.
Therefore we should guarantee the linux platforms should pass the CI.

2023-04-26 10:48 UTC, q82419 approved these changes

2023-04-26 10:49 UTC, merged