[Test] Make plugin test load the plugin's shared library
WasmEdge/WasmEdge pull request #2128
Opened 2022-11-28 20:44 UTC by harry900831

It just a draft now.

It may fix #2070, #2043.

2022-12-15 06:18 UTC, hydai commented
@ibmibmibm @q82419 
PTAL. It looks like we should provide default visibility on some functions. Is this workaround OK? Or do we have any other choices?

2022-12-19 20:58 UTC, ibmibmibm approved these changes

2022-12-22 05:52 UTC, q82419 requested changes
Because of removing the linking `wasmedgePlugin*` targets of the `wasmedge*Tests`, you should add the target dependencies in cmake.

2023-05-08 23:01 UTC, q82419 commented
Replaced by #2480.

2023-05-08 23:01 UTC, closed without merging