[Java][Refactor] Add constants, refactor Java API
WasmEdge/WasmEdge pull request #2139
Opened 2022-11-30 23:24 UTC by kenvifire

- Add constants
    - Replace JNI method names and signatures with macros
    - Replace error messages with macros
- Refactor Java API
    - `WasmEdgeExternRef` -> `ExternRef`
    - `WasmEdgeI32Value` -> `I32Value`
    - `WasmEdgeF32Value` -> `F32Value`
    - `WasmEdgeI64Value` -> `I64Value`
    - `WasmEdgeF64Value` -> `F64Value`
    - `WasmEdgeValue` -> `Value`
    - `WasmEdgeMutability` -> `Mutability`
- .gitignore
   - exclude generated JNI headers
- build.gradler
   - clean jni headers in clean task

2022-12-01 16:24 UTC, dannypsnl requested changes

2022-12-01 16:24 UTC, dannypsnl commented on bindings/java/wasmedge-java/wasmedge-jni/lib/constants.h
> +#endif
All looks good, once you resolve this eof then I think PR is ready

2022-12-02 01:39 UTC, dannypsnl approved these changes

2022-12-02 06:10 UTC, kenvifire commented
@hydai Ready to merge.

2022-12-02 06:12 UTC, merged