refactor: reduce the use of VType in validator
WasmEdge/WasmEdge pull request #2150
Opened 2022-12-03 11:52 UTC by little-willy

In https://github.com/WasmEdge/WasmEdge/pull/2097, we turn `VType` in validator into `Optional<ValType>`, and use `None` as the original `VType::Unknown`, which was used as unreachable type. After further examine the code the validator, most usage of `VType` make no difference to using `ValType`. In this PR, we further reduce the usage of `VType`. Currently, the `VType` is only stored in the `ValStack` of `FormChecker`. All other usages have been turned into `ValType`.

This PR is after https://github.com/WasmEdge/WasmEdge/pull/2099.

2023-05-02 06:49 UTC, q82419 commented
Please fix the DCO.

2023-05-02 07:20 UTC, q82419 requested changes
Great.
Please apply the clang-format for the lint.

2023-05-03 02:46 UTC, little-willy commented
@q82419 The all CI on linux fail because of a strange compile error. Do you have any idea?
```
../test/plugins/unittest/testplugin.c: In function 'CreateTestModule':
[102](https://github.com/WasmEdge/WasmEdge/actions/runs/4867096359/jobs/8679346254?pr=2150#step:5:103)
../test/plugins/unittest/testplugin.c:45:8: error: 'WasmEdge_ValType' defined as wrong kind of tag
[103](https://github.com/WasmEdge/WasmEdge/actions/runs/4867096359/jobs/8679346254?pr=2150#step:5:104)
   45 |   enum WasmEdge_ValType ParamTypes[2], ReturnTypes[1];
[104](https://github.com/WasmEdge/WasmEdge/actions/runs/4867096359/jobs/8679346254?pr=2150#step:5:105)
      |        ^~~~~~~~~~~~~~~~
[105](https://github.com/WasmEdge/WasmEdge/actions/runs/4867096359/jobs/8679346254?pr=2150#step:5:106)
../test/plugins/unittest/testplugin.c:45:25: error: array type has incomplete element type 'enum WasmEdge_ValType'
[106](https://github.com/WasmEdge/WasmEdge/actions/runs/4867096359/jobs/8679346254?pr=2150#step:5:107)
   45 |   enum WasmEdge_ValType ParamTypes[2], ReturnTypes[1];
[107](https://github.com/WasmEdge/WasmEdge/actions/runs/4867096359/jobs/8679346254?pr=2150#step:5:108)
      |                         ^~~~~~~~~~
[108](https://github.com/WasmEdge/WasmEdge/actions/runs/4867096359/jobs/8679346254?pr=2150#step:5:109)
../test/plugins/unittest/testplugin.c:45:40: error: array type has incomplete element type 'enum WasmEdge_ValType'
[109](https://github.com/WasmEdge/WasmEdge/actions/runs/4867096359/jobs/8679346254?pr=2150#step:5:110)
   45 |   enum WasmEdge_ValType ParamTypes[2], ReturnTypes[1];
[110](https://github.com/WasmEdge/WasmEdge/actions/runs/4867096359/jobs/8679346254?pr=2150#step:5:111)
      |                                        ^~~~~~~~~~~
[111](https://github.com/WasmEdge/WasmEdge/actions/runs/4867096359/jobs/8679346254?pr=2150#step:5:112)
../test/plugins/unittest/testplugin.c:46:19: error: 'WasmEdge_ValType_I32' undeclared (first use in this function); did you mean 'WasmEdge_ValTypeIsI32'?
[112](https://github.com/WasmEdge/WasmEdge/actions/runs/4867096359/jobs/8679346254?pr=2150#step:5:113)
   46 |   ParamTypes[0] = WasmEdge_ValType_I32;
[113](https://github.com/WasmEdge/WasmEdge/actions/runs/4867096359/jobs/8679346254?pr=2150#step:5:114)
      |                   ^~~~~~~~~~~~~~~~~~~~
[114](https://github.com/WasmEdge/WasmEdge/actions/runs/4867096359/jobs/8679346254?pr=2150#step:5:115)
      |                   WasmEdge_ValTypeIsI32
[115](https://github.com/WasmEdge/WasmEdge/actions/runs/4867096359/jobs/8679346254?pr=2150#step:5:116)
../test/plugins/unittest/testplugin.c:46:19: note: each undeclared identifier is reported only once for each function it appears in
[116](https://github.com/WasmEdge/WasmEdge/actions/runs/4867096359/jobs/8679346254?pr=2150#step:5:117)
../test/plugins/unittest/testplugin.c:45:40: error: unused variable 'ReturnTypes' [-Werror=unused-variable]
[117](https://github.com/WasmEdge/WasmEdge/actions/runs/4867096359/jobs/8679346254?pr=2150#step:5:118)
   45 |   enum WasmEdge_ValType ParamTypes[2], ReturnTypes[1];
[118](https://github.com/WasmEdge/WasmEdge/actions/runs/4867096359/jobs/8679346254?pr=2150#step:5:119)
      |                                        ^~~~~~~~~~~
[119](https://github.com/WasmEdge/WasmEdge/actions/runs/4867096359/jobs/8679346254?pr=2150#step:5:120)
../test/plugins/unittest/testplugin.c:45:25: error: unused variable 'ParamTypes' [-Werror=unused-variable]
[120](https://github.com/WasmEdge/WasmEdge/actions/runs/4867096359/jobs/8679346254?pr=2150#step:5:121)
   45 |   enum WasmEdge_ValType ParamTypes[2], ReturnTypes[1];
[121](https://github.com/WasmEdge/WasmEdge/actions/runs/4867096359/jobs/8679346254?pr=2150#step:5:122)
      |                         ^~~~~~~~~~
```

2023-05-03 09:01 UTC, q82419 commented
@little-willy  Some tests lost the modification. I've fix it and updated. Thanks.

2023-05-03 19:47 UTC, little-willy commented
@q82419 I just noticed that in the latest 3 merged PRs, the author of commits generated by GitHub(something like `xxx@users.noreply.github.com>`) is not consistent with the sign-off author, and will cause the DCO check to fail.

I just tried resetting the author and email of the latest 3 merged commits and it is in this branch https://github.com/little-willy/WasmEdge/tree/func-ref-fix-author. Can you help force push the commit of `little-willy:func-ref-fix-author` to the main `proposal/func-ref` to fix the author inconsistency?

2023-05-04 06:04 UTC, q82419 approved these changes

2023-05-04 06:04 UTC, merged