feat: support loading table extended from function reference
WasmEdge/WasmEdge pull request #2151
Opened 2022-12-05 04:01 UTC by little-willy

After #2125.

2023-04-12 02:41 UTC, alabulei1 commented
flows summarize

2023-04-12 02:44 UTC, alabulei1 commented
Hello, I am a [serverless review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/). Here are my reviews of code commits in this PR.

------

Overall, the patches involve a mix of changes related to refactoring, formatting, bug fixes, support for new types, and additions of new functions. The potential issues and errors include: the introduction of a new optional type that could introduce new issues if not handled properly, the possibility of breaking compatibility with existing code depending on the changes being made, and the removal of helper functions that could cause issues down the line. 

The most important findings include: the introduction of heap types and the deprecation of previous type definitions, which will require thorough testing and may impact external interfaces or dependencies, and the addition of a new function without a clear description or testing. Additionally, it is important to thoroughly review the changes in each patch, even for those with minor modifications, to ensure that they do not introduce any regressions or conflicts.

## Details

### Commit 1
The patch includes refactoring of the FormChecker class in the Validator namespace to use an optional ValType for validator VType. The key changes are the replacement of the `enum class VType` with `typedef std::optional<ValType> VType` and the update of the respective functions to use this new type: `ASTToVType`, `isNumType`, `isRefType`, `FormChecker`, `VTypeToAST`, `checkInstr`, `popType`, `popTypes`, `pushType`, and `StackTrans`. 

An important finding is that `VType` is now an optional, and this could introduce new issues if it's not handled properly. Also, the patch is quite large, with over 300 deletions and 370 insertions, so it is essential to review the changes carefully to ensure that the code still works as intended.

### Commit 2
The patch changes the formatting of the code to conform to clang-format. It appears to make changes to whitespace and line breaks. There are no changes in the functionality of the code. 

The changes appear to be safe and should not cause any problems.

### Commit 3
This patch contains a number of changes throughout the codebase, centered around the `ValType` type which has been refactored into `FullValType`. 

One potential issue is that this patch contains changes to a significant number of files, so the scope of the changes should be carefully considered. Additionally, changes to types could result in knock-on effects in other parts of the codebase, so a thorough review of any dependent code should be undertaken. 

Finally, there are some changes to the format of the code, such as the addition of whitespace and indentation, which could result in conflicts when merging.

### Commit 4
This patch seems to be modifying six different source code files. The changes include adding line breaks, indentation, and spaces to improve the code's readability. The patch also adds a few `noexcept` annotations along with some parameters indentation. 

There don't seem to be any potential problems with these changes. However, as a reviewer it's always important to check the first and last lines of the patch to determine if there are any conflicts or errors with the file modifications.

### Commit 5
This patch contains two changes in two different files:

In bindings/rust/wasmedge-sys/src/types.rs:
- The Debug implementation for WasmValue now uses Rust's block formatting syntax instead of method chaining for better readability.

In lib/api/wasmedge.cpp:
- A new field is added to the returned WasmEdge_FullValType struct, which is initialized with an empty WasmEdge_ValTypeExt struct.

There do not seem to be any potential problems in this patch.

### Commit 6
This patch adds a new CAPI, "WasmEdge_GlobalTypeGetFullValType", to the "wasmedge.h" header file. This CAPI retrieves the full extended value type from a global type. The patch does not mention any potential problems.

### Commit 7
The patch introduces changes to multiple files in the project that replace the use of `ValType` with `FullValType` and `RefType` with `FullRefType`. `FullValType` includes an additional field `WasmEdge_ValTypeExt`, while `FullRefType` extends `RefType` with an `Ext` field. The `ValType` and `RefType` fields are now accessed through functions. 

One potential problem is that the changes may break compatibility with existing code that relies on the previous versions of `ValType` and `RefType`. Additionally, the patch does not include any unit tests to ensure that the updated code functions as expected.

### Commit 8
This patch contains changes to two files: "enum_types.h" and "helper.cpp". The purpose of the changes is to fix a problem with the Windows CI build. 

In "enum_types.h", the `WasmEdge_ValTypeExt` union is modified to include a new field `TypeIdx`. This change could potentially introduce bugs if the new field is not used correctly in the codebase.

In "helper.cpp", there is a minor change of using `Types[I].asCStruct()` instead of `static_cast<WasmEdge_ValType>(Types[I])`. This change seems trivial and should not cause any issues.

Overall, the changes in this patch seem relatively small and targeted towards fixing a known issue. However, it is important to test the changes thoroughly to ensure that they do not introduce any new problems or regressions.

### Commit 9
Key Changes:
- The function `loadFullValType` now has an additional input parameter `TypeCode`.
- The two helper functions `checkValTypeProposals` and `checkRefTypeProposals` have been removed.
- The function `loadFullRefType` now performs checks for valid reference types.

Potential Problems:
- The removal of `checkValTypeProposals` and `checkRefTypeProposals` may cause issues down the line when loading values and references.
- The changes made to `loadFullValType` could potentially introduce new bugs due to the addition of the `TypeCode` parameter.
- It is unclear whether any other parts of the code rely on the removed helper functions, so their removal may cause unforeseen issues.

### Commit 10
The patch aims to make the Windows CI (Continuous Integration) happy by making some changes to the `lib/loader/ast/instruction.cpp` file. The changes consist of modifying the way the `Expect<void>` function is called, which is related to handling errors during the code execution. Specifically, the `loadFullValType()` function call was modified to use a variable `TypeRes` to store the result which is then used in the `setBlockType()` method call. Additionally, some formatting changes were made in the `loadInstruction()` method.

The potential problem with this patch is that it is not clear what issue the Windows CI was facing, and whether these changes are the correct solution or not. Moreover, it is unclear if other platforms might be affected by these changes, and if the proposed code modifications will cause any negative impacts elsewhere. Additionally, there should be some explanation of why this change is necessary, and how it impacts the overall system.

### Commit 11
The patch introduces changes in several files that add support for new types to the WasmEdge virtual machine. The most significant changes involve the introduction of heap types and the deprecation of the previous RefType and ValType definitions. The patch also includes changes to the enum_types.h header file and related files to implement these changes. 

It is difficult to identify potential problems without more context on the requirements/specifications of the system, but it is important to ensure that these changes are thoroughly tested and do not introduce any backwards compatibility issues. Additionally, it may be necessary to update any external interfaces or dependencies that rely on the previous ValType and RefType definitions.

### Commit 12
This patch changes a comment in the `FormChecker` class in `formchecker.cpp`. The comment is modified to correctly describe a check being  [...]

2023-04-13 11:35 UTC, q82419 requested changes
I think the design of the AST should like this:

The section of `Table` : vector of `TableSegment`.
The content of `TableSegment`: `TableType` + `Expression` (can be empty).
The `Expression` of `TableSegment` provide the initialization of the table instance when instantiation.
With this design, the `TableInstance` will not necessary to be changed and capable with the old definitions.

2023-04-13 11:35 UTC, q82419 commented on include/ast/type.h
> +class Table {
For this object which contains the expression and type, you should add it in the `Segment`, such as the `GlobalSegment` and `ElementSegment`.

2023-04-25 19:46 UTC, little-willy commented
@q82419 I have addressed the comments and turn the original `Table` into `TableSegment`. PTAL.

2023-04-26 10:52 UTC, q82419 approved these changes

2023-04-26 10:52 UTC, merged