[Docs] Add installer guide
WasmEdge/WasmEdge pull request #2223
Opened 2023-01-17 02:34 UTC by hydai

Replace #2207

2023-01-18 03:54 UTC, q82419 requested changes

2023-01-18 03:54 UTC, q82419 commented on docs/book/en/src/contribute/installer.md
> +### Specify Installed Version
Specify the version of WasmEdge to install

2023-01-18 03:54 UTC, q82419 commented on docs/book/en/src/contribute/installer.md
> +* Note - If the path does not exist it is created.
If the path not exists, the folder will be created.

2023-01-18 03:54 UTC, q82419 commented on docs/book/en/src/contribute/installer.md
> +* Note - In case if an invalid or non existing version is suppliead the installer exits with an error.
In the case of supplied an invalid or nonexistent version, the installer exists with an error.

2023-01-18 03:54 UTC, q82419 commented on docs/book/en/src/contribute/installer.md
> +### Install Path
Installation path

2023-01-18 03:54 UTC, q82419 commented on docs/book/en/src/contribute/installer.md
> +### Uninstall existed version
Uninstallation

2023-01-18 03:54 UTC, q82419 commented on docs/book/en/src/contribute/installer.md
> +* Note - It's value is same as that of wasmedge version if not specified.
the same as the WasmEdge version

2023-01-18 03:54 UTC, q82419 commented on docs/book/en/src/contribute/installer.md
> +* Note - It's value is same as that of wasmedge version if not specified.
the same as the WasmEdge version

2023-01-18 03:54 UTC, q82419 commented on docs/book/en/src/contribute/installer.md
> +* Note - It's value is same as that of wasmedge version if not specified.
the same as the WasmEdge version

2023-01-18 03:54 UTC, q82419 commented on docs/book/en/src/contribute/installer.md
> +* Note - It's value is same as that of wasmedge version if not specified.
the same as the WasmEdge version

2023-01-18 03:54 UTC, q82419 commented on docs/book/en/src/contribute/installer.md
> +#### Image Extensions Dependencies Version
Remove this column.
image-deps has been removed from installer due to deprecating 0.8.2.

2023-01-18 03:54 UTC, q82419 commented on docs/book/en/src/contribute/installer.md
> +* Note - It's value is same as that of wasmedge version if not specified.
the same as the WasmEdge version

2023-01-18 20:01 UTC, hydai commented
All comments are fixed.

2023-01-19 08:43 UTC, q82419 approved these changes

2023-01-29 22:46 UTC, merged