Mock the plug-in modules and refactor the VM context API.
WasmEdge/WasmEdge pull request #2287
Opened 2023-02-14 18:52 UTC by q82419

2023-02-16 20:43 UTC, q82419 commented
@apepkuss Please notice this PR that the API changes. Thanks.

2023-02-17 02:00 UTC, apepkuss commented
@q82419 Thank you for letting me know about the changes. I checked the changes on `vm.rs` and found that only the API names are updated but no semantics get changed, right? Thanks!

2023-02-17 04:48 UTC, q82419 commented
> @q82419 Thank you for letting me know about the changes. I checked the changes on `vm.rs` and found that only the API names are updated but no semantics get changed, right? Thanks!

Yes, only the name changes.
But for the `ModuleInstance`, several API deleted and replaced by the `Plugin` APIs.

2023-02-17 04:55 UTC, apepkuss commented
> > @q82419 Thank you for letting me know about the changes. I checked the changes on `vm.rs` and found that only the API names are updated but no semantics get changed, right? Thanks!
> 
> Yes, only the name changes. But for the `ModuleInstance`, several API deleted and replaced by the `Plugin` APIs. I'll update the release note and C API docs these days. You can check that then.

Got it. Thanks a lot!

2023-02-17 12:07 UTC, q82419 commented
Hi @kenvifire ,

Would you want to help to update the Java SDK for the API changes after this PR being merged?
Thanks!

2023-02-19 05:29 UTC, kenvifire commented
> Hi @kenvifire ,
> 
> Would you want to help to update the Java SDK for the API changes after this PR being merged? Thanks!

Sure.

2023-02-21 09:27 UTC, hydai requested changes

2023-02-21 09:27 UTC, hydai commented on include/host/mock/wasi_crypto_func.h
> +    return 1U;
Please use a constant error code to replace this magic number.

2023-02-21 09:27 UTC, hydai commented on bindings/java/wasmedge-java/wasmedge-jni/lib/WasmEdgeVM.c
> +  WasmEdge_ModuleInstanceContext *imp = WasmEdge_VMGetPreRegisteredModule(
This rename is not necessary; please undo this.

2023-02-21 09:27 UTC, hydai commented on include/host/mock/wasi_nn_func.h
> +    return 1U;
Use constant error code.

2023-02-21 09:27 UTC, hydai commented on lib/vm/vm.cpp
> +    // Skip WasmEdge_Process, WasmEdge_HttpsReq, wasi_nn, and wasi_crypto.
extract an external function for this section.

2023-02-21 17:54 UTC, hydai approved these changes

2023-02-22 02:08 UTC, apepkuss commented
@q82419 Please ignore the failures caused by the workflows related to Rust SDK. I'll fix them in another PR. Thanks!

2023-02-22 19:31 UTC, merged