[WIP][Rust] Implement new Vm
WasmEdge/WasmEdge pull request #2301
Opened 2023-02-20 01:55 UTC by apepkuss

In this PR, a new `Vm` is introduced to replace the original one in `wasmedge-sdk`. The new `Vm` has no dependency on the low-level objects defined in `wasmedge-sys` but simply depends on other high-level objects in `wasmedge-sdk`. To reduce the cost of the maintenance, in addition, the low-level `Vm` defined in `wasmedge-sys` is removed.

2023-02-23 13:09 UTC, apepkuss commented
@hydai Could you please help review this PR? In addition, this PR should be merged prior to #2307. Thanks a lot!

2023-02-24 10:15 UTC, hydai requested changes

2023-02-24 11:02 UTC, apepkuss commented on bindings/rust/wasmedge-sys/src/executor.rs
> +            registered: true,
Yes, this is the expected setting. The original `false` is inappropriate. Thanks!

2023-02-24 11:03 UTC, hydai approved these changes

2023-02-24 11:05 UTC, apepkuss commented
@hydai Thanks for the review!

2023-02-24 13:07 UTC, merged