[Docs] Update documents for unified tool
WasmEdge/WasmEdge pull request #2378
Opened 2023-03-24 11:52 UTC by michael1017

1. Since we reserve `wasmedgec` tool at this time, I did not remove `wasmedgec` in the installation documents. Besides, I added notes to remind user that `wasmedgec` is equal to `wasmedge compile` and we decide to deprecate `wasmedgec` in the future.

2. Since `wasmedgec` is equal to `wasmedge compile`, I replace `wasmedgec` to `wasmedge compile` in user guides and examples.

2023-05-25 07:05 UTC, hydai commented
Hi @michael1017 
The main PR is merged. Please rebase your remaining PRs, thanks!

2023-05-26 05:00 UTC, hydai requested changes

2023-05-26 12:09 UTC, hydai approved these changes

2023-05-26 12:10 UTC, hydai approved these changes

2023-05-26 12:19 UTC, merged

2023-05-28 03:07 UTC, alabulei1 commented
The old book will be deprecated. We should update this content to WasmEdge/docs.