CMake: quote WASMEDGE_LLVM_LINK_LIBS_NAME variable in order to fix arm64-osx AOT build
WasmEdge/WasmEdge pull request #2443
Opened 2023-04-25 18:22 UTC by Pospelove

This PR upstreams [vcpkg-specific patch](https://github.com/microsoft/vcpkg/commit/701bcf3017ced0eae4dfadeb827d26cebb583479#diff-e7d5505610e56fc4b780d02e61cc7b3242fccf2e8d34b022dfebb1c309edc560) by @autoantwort

The original patch fixes building WasmEdge for arm64-osx target when "aot" (Build with the Ahead-of-Time compiler supporting) feature is enabled

2023-04-25 18:23 UTC, alabulei1 commented
Hello, I am a [serverless review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/). Here are my reviews of code commits in this PR.

------

### [Commit 8d23b1f1eaf258f276a9c287f713ab1a1f002685](https://github.com/WasmEdge/WasmEdge/pull/2443/commits/8d23b1f1eaf258f276a9c287f713ab1a1f002685)
The patch updates the Helper.cmake file by quoting the `WASMEDGE_LLVM_LINK_LIBS_NAME` variable in order to fix an AOT build issue on arm64-osx. Specifically, the patch adds double quotes around the `${WASMEDGE_LLVM_LINK_LIBS_NAME}` variable in the `string(REPLACE...)`, `string(REGEX REPLACE...)`, and `string(REPLACE...)` commands, and sets the variable to the quoted value. This change intends to handle spaces and special characters in the variable contents correctly.

There are no potential problems with this patch, and it seems like a reasonable fix for the AOT build issue. The changes are simple, clear, and appropriately documented.

2023-04-25 20:54 UTC, q82419 requested changes

2023-04-25 21:40 UTC, Pospelove commented on cmake/Helper.cmake
> +  string(REPLACE " " "\;" WASMEDGE_LLVM_LINK_LIBS_NAME "${WASMEDGE_LLVM_LINK_LIBS_NAME}")
@q82419  this way?

2023-04-26 01:22 UTC, ibmibmibm approved these changes

2023-04-26 08:19 UTC, q82419 approved these changes

2023-04-26 08:20 UTC, merged