[Windows] propagate CMAKE_MSVC_RUNTIME_LIBRARY to the libwasmedge
WasmEdge/WasmEdge pull request #2476
Opened 2023-05-06 07:27 UTC by hydai

2023-05-06 07:27 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2023-05-06 07:27 UTC, hydai commented
Replace #2475

2023-05-08 22:03 UTC, q82419 approved these changes

2023-05-08 22:04 UTC, q82419 requested changes
No ctest on Windows?

2023-05-10 19:31 UTC, q82419 approved these changes

2023-05-10 19:31 UTC, merged