[Misc] Fix debug log empty messages
WasmEdge/WasmEdge pull request #2551
Opened 2023-06-02 00:42 UTC by XingZYu

As mentioned in [discussion#2548](https://github.com/WasmEdge/WasmEdge/discussions/2548)

2023-06-02 00:42 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2023-06-02 02:20 UTC, hydai requested changes

2023-06-02 02:20 UTC, hydai commented on lib/vm/vm.cpp
> +  spdlog::debug("Plugin: {} , module name: {} not found. Mock instead.", PName,
The end should be `"sv`.

2023-06-06 14:43 UTC, hydai commented
Please fix the lint issue.

2023-06-07 00:35 UTC, q82419 approved these changes

2023-06-07 00:35 UTC, q82419 requested changes
Please apply the clang-format.

2023-06-07 04:47 UTC, hydai approved these changes

2023-06-07 21:33 UTC, q82419 approved these changes

2023-06-07 21:34 UTC, merged