[TEST] Enable test when boost not found.
WasmEdge/WasmEdge pull request #2560
Opened 2023-06-04 03:39 UTC by MediosZ

When boost is not installed, it will be built from the source. But setting `set(BUILD_TESTING OFF)` will disable all subsequent tests.  This can be observed in Fedora CI and WIndows CI.
So we need a better way to disable the boost tests.

2023-06-04 03:39 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2023-06-04 04:37 UTC, MediosZ commented
Actually, I don't get why adding `set(BUILD_TESTING OFF)` there. Since the unit tests inside boost are not executed by default during `FetchContent_MakeAvailable`.
Maybe it would be better just to delete [that line](https://github.com/WasmEdge/WasmEdge/blob/e0e6dcc6847595ddf3cb152836c7b89578d1da1c/CMakeLists.txt#L56).

2023-06-05 18:04 UTC, hydai requested changes

2023-06-05 18:04 UTC, hydai commented on CMakeLists.txt
> +  set(BUILD_TESTING ON)
How about disabling this here and enabling it again after the boost part?

2023-06-05 18:06 UTC, hydai commented
> Actually, I don't get why adding `set(BUILD_TESTING OFF)` there. Since the unit tests inside boost are not executed by default during `FetchContent_MakeAvailable`. Maybe it would be better just to delete [that line](https://github.com/WasmEdge/WasmEdge/blob/e0e6dcc6847595ddf3cb152836c7b89578d1da1c/CMakeLists.txt#L56).

Oh, so the Fetch and build from source will not run the test part inside boost. If so, then we can remove it.

2023-06-09 17:16 UTC, hydai approved these changes

2023-06-09 17:58 UTC, merged