[WASI]: Unify the write and the read function.
WasmEdge/WasmEdge pull request #2643
Opened 2023-07-03 12:55 UTC by MediosZ

This PR trys to unify the read and write function to address the issue when using epoll.
The current implementation causes epoll being triggered endlessly.

2023-07-03 12:55 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2023-07-05 11:28 UTC, hydai commented
Hi @MediosZ 
I got a little bit confused. Since there are only two functions, `read` and `write` in WASI spec, I don't think providing a new function and combining both functions is a good idea. This issue is triggered by modifying the `READ` or `WRITE` every time. However, we can change the behavior to the following.

Case 1. If it's new, just apply `READ` or `WRITE`.
Case 2. It already has `READ` or `WRITE`, then we modify it.

2023-07-06 07:43 UTC, MediosZ commented
I feels like it's hard to cover all the cases with these two functions.

Let's say we have registered `READ` and `WRITE` in the first call.
And in the second call, we receive only the `READ` subscription only, which means only the `read` function will be invoked and we can not determine if the `write` function will be invoked.
In this case, we should not modify the `epoll` since the `READ` doesn't change. As a result, the `WRITE` will not be deregistered as the `write` function will not be invoked.

That's why I was think of unify these two functions as that's how epoll works.

2023-07-18 08:34 UTC, hydai requested changes

2023-07-18 08:34 UTC, hydai commented on include/host/wasi/vinode.h
> +  void process(std::shared_ptr<VINode> Fd [[maybe_unused]],
Why do we need so many `[[maybe_unused]]` attributes here?

2023-07-18 08:34 UTC, hydai commented on include/host/wasi/vinode.h
> +    auto TempReadFlag = ReadFlag;
`Temp` is so confusing. Please use a precise name.

2023-07-18 08:34 UTC, hydai commented on lib/host/wasi/inode-linux.cpp
> +      EPollEvent.events |= EPOLLOUT;
Why not:

```
      EPollEvent.events = EPOLLIN | EPOLLOUT;
```

2023-07-18 08:34 UTC, hydai commented on lib/host/wasi/inode-linux.cpp
> +        //
Redundant comments.

2023-07-18 08:34 UTC, hydai commented on lib/host/wasi/inode-linux.cpp
> +
Redundant empty line.

2023-07-18 08:34 UTC, hydai commented on lib/host/wasi/inode-linux.cpp
> +
Redundant empty line.

2023-07-18 08:34 UTC, hydai commented on lib/host/wasi/inode-linux.cpp
> +        //
Unknown comments.

2023-07-18 08:34 UTC, hydai commented on lib/host/wasi/inode-linux.cpp
> +            (WriteFlag && OldIter->second.WriteEvent == nullptr)) {
In the current condition (`ReadFlag = true && WriteFlag = false`), this statement needs to be stripped.

2023-07-18 08:34 UTC, hydai commented on lib/host/wasi/inode-linux.cpp
> +
Redundant empty line

2023-07-18 08:34 UTC, hydai commented on lib/host/wasi/inode-linux.cpp
> +            (WriteFlag && OldIter->second.WriteEvent == nullptr)) {
Please simplify the statement in the current condition (`ReadFlag = false && WriteFlag = true`).

2023-07-18 08:34 UTC, hydai commented on lib/host/wasi/wasifunc.cpp
> +          SubInfo Info = {.ReadFlag = true,
Don't use this pattern. It's not in the C++17 standard. It's c99 standard, and will be shipped in C++20 (ref: https://www.cppstories.com/2021/designated-init-cpp20/)

2023-07-18 08:34 UTC, hydai commented on lib/host/wasi/wasifunc.cpp
> +        // Poller.read(WasiFd, Trigger, WasiUserData);
Why comment this out?

2023-07-18 08:34 UTC, hydai commented on lib/host/wasi/wasifunc.cpp
> +          SubInfo Info = {.ReadFlag = false,
Ditto.

2023-07-18 08:34 UTC, hydai commented on lib/host/wasi/wasifunc.cpp
> +        // Poller.write(WasiFd, Trigger, WasiUserData);
Ditto.

2024-06-24 12:31 UTC, hydai commented
This PR is already out of date. I'm closing it. Please feel free to rebase and create a new one for it.

2024-06-24 12:31 UTC, closed without merging