[CI] Separate the specific plugins by archetectures.
WasmEdge/WasmEdge pull request #2653
Opened 2023-07-07 06:28 UTC by q82419

2023-07-07 06:28 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2023-07-07 06:28 UTC, q82419 commented
Maybe replace #2614 ?

2023-07-07 09:51 UTC, hydai requested changes

2023-07-07 09:51 UTC, hydai commented on .github/workflows/build-extensions.yml
> +      build_options_both: -DWASMEDGE_PLUGIN_WASI_NN_BACKEND=TensorFlowLite
Using the name `manylinux2014_all` is better. We may support more architecture in the future, but `both` is inaccurate.

2023-07-13 09:55 UTC, hydai approved these changes

2023-07-13 14:15 UTC, merged