[CI] try nix build in CI workflow
WasmEdge/WasmEdge pull request #2674
Opened 2023-07-21 07:25 UTC by dannypsnl

2023-07-21 07:25 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2023-07-24 16:01 UTC, hydai requested changes
Could we run unit tests together?

2023-07-24 16:01 UTC, hydai commented on .github/workflows/build_for_nix.yml
> +    - uses: actions/cache@v2
We should use v3

2023-07-25 05:12 UTC, dannypsnl commented
@hydai That would have to modify `flake.nix`, should we do that in this PR?

2023-07-25 05:24 UTC, hydai commented
We can have another one to do this.

2023-07-25 05:48 UTC, dannypsnl commented
@hydai I create a tracker for that #2679

2023-07-25 06:23 UTC, hydai commented
The CI failed :-(

2023-07-25 07:27 UTC, hydai approved these changes
LGTM

2023-07-25 07:28 UTC, merged