[Proposal] Implement the typed-function references proposal.
WasmEdge/WasmEdge pull request #2691
Opened 2023-07-26 23:10 UTC by q82419

2023-07-26 23:10 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2023-08-23 05:56 UTC, q82419 commented
@apepkuss  You can refer to the API header for the changes. I'll notice you once the docs ready. Thanks.

2023-08-23 06:28 UTC, apepkuss commented
@q82419 Thanks for the reminder. I'll check the changes.

2023-11-29 09:47 UTC, ibmibmibm requested changes

2023-11-29 09:47 UTC, ibmibmibm commented on lib/executor/helper.cpp
> +    bool NullableMatch = Exp.isNullableRefType() || !Got.isNullableRefType();
```c++
if (!Exp.isNullableRefType() && Got.isNullableRefType()) {
 return false;
}
```

2023-11-29 09:47 UTC, ibmibmibm commented on lib/loader/serialize/serial_type.cpp
> +    if (!Conf.hasProposal(Proposal::FunctionReferences)) {
unlikely

2023-11-29 09:47 UTC, ibmibmibm commented on lib/validator/formchecker.cpp
> +    bool NullableMatch = Exp.isNullableRefType() || !Got.isNullableRefType();
```c++
if (!Exp.isNullableRefType() && Got.isNullableRefType()) {
  return false;
}
```

2023-11-29 09:47 UTC, ibmibmibm commented on lib/validator/formchecker.cpp
> +      if (!(**Res).isRefType()) {
`!(*Res)->isRefType()`

2023-12-11 13:07 UTC, ibmibmibm approved these changes

2023-12-13 01:54 UTC, merged