[Plugin] opecvmini `rectangle`
WasmEdge/WasmEdge pull request #2705
Opened 2023-07-31 03:53 UTC by dannypsnl

This function can draw rectangle on picture buffer.

TODO:
- [ ] customize color

2023-07-31 03:53 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2023-08-03 13:54 UTC, hydai requested changes

2023-08-03 13:54 UTC, hydai commented on plugins/wasmedge_opencvmini/opencvmini_func.cpp
> +  cv::Point top_left(top, left);
Wrong naming style.

2023-08-06 13:20 UTC, 1awesomeJ commented
Lots of amazing features on this repository:
1. Juntao giving detailed review- Thank you so much for the initiative. It's super helpful for us beginners. Thank you for coming up with it.
2. codecov bot- helping us easily see test coverage
3. Merging getting block when there are pending requested changes.
It's all awesome.

I'm an aspiring LFX mentee on the project "add matrix operations for opencvmini", and these will be quite helpful in helping get started with making contributions.

2023-08-06 13:25 UTC, dannypsnl commented
@1awesomeJ Please don’t make irrelevant comment in PR, don’t apologize, I will hide your and this comment. You can create discussion for this kind of content.

2023-08-06 13:43 UTC, ibmibmibm approved these changes

2023-08-07 14:51 UTC, hydai approved these changes
LGTM

2023-08-07 17:08 UTC, merged