[Plugin] add wasmedge_rustls_plugin
WasmEdge/WasmEdge pull request #2762
Opened 2023-08-28 13:43 UTC by L-jasmine

2023-08-28 13:43 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2023-08-28 16:03 UTC, hydai requested changes
1. Please add the option in CMakeLists.txt: https://github.com/WasmEdge/WasmEdge/blob/master/CMakeLists.txt#L72
2. Please add a workflow for building this plugin to ensure the building process works.

2023-09-02 09:36 UTC, hydai requested changes

2023-09-02 09:36 UTC, hydai commented on plugins/wasmedge_rustls/CMakeLists.txt
> +if(CMAKE_BUILD_TYPE STREQUAL "Debug")
Missing license lines.

2023-09-04 00:47 UTC, hydai approved these changes

2023-09-04 00:48 UTC, merged