[WASI-NN] Update ggml
WasmEdge/WasmEdge pull request #2805
Opened 2023-09-13 08:42 UTC by dm4

- Update ggml library
- Use gguf model for tests
- Enable `LLAMA_BLAS` by default

2023-09-14 01:56 UTC, hydai requested changes

2023-09-14 07:51 UTC, hydai requested changes

2023-09-14 07:51 UTC, hydai commented on LICENSE.spdx
> -PackageDownloadLocation: git://github.com/ggerganov/llama.cpp.git@da39a3ee5e6b4b0d3255bfef95601890afd80709
The `PackageFileName` should be updated at the same time.

2023-09-14 09:00 UTC, hydai commented
Is it possible to know if the OpenBLAS is set correctly?

2023-09-14 09:47 UTC, dm4 commented
> Is it possible to know if the OpenBLAS is set correctly?

In cmake configure log:
```
-- BLAS found, Libraries: /usr/lib/x86_64-linux-gnu/libopenblas.so
```

or check the plugin binary dependency:
```
$ ldd ~/.wasmedge/plugin/libwasmedgePluginWasiNN.so | grep openblas
        libopenblas.so.0 => /lib/x86_64-linux-gnu/libopenblas.so.0 (0x00007f749cf88000)
```

2023-09-21 06:31 UTC, dm4 commented
Continue at the new PR #2831

2023-09-21 06:31 UTC, closed without merging