Serialize completion
WasmEdge/WasmEdge pull request #2819
Opened 2023-09-18 08:16 UTC by q82419

2023-09-18 08:16 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2023-11-21 10:14 UTC, ibmibmibm requested changes

2023-11-21 10:14 UTC, ibmibmibm commented on include/loader/serialize.h
> +    const uint8_t *Ptr = reinterpret_cast<const uint8_t *>(&Num);
check current endian, swap bytes on big endian.

2023-11-29 09:56 UTC, ibmibmibm requested changes

2023-11-29 09:56 UTC, ibmibmibm commented on lib/loader/serialize/serial_module.cpp
> +  auto Comp = [](auto &A) { return A->getStartOffset(); };
Move `Comp` into lambda function inside `std::sort`.

2023-12-01 08:43 UTC, ibmibmibm submitted a review, later dismissed

2023-12-11 08:37 UTC, ibmibmibm approved these changes

2023-12-11 09:18 UTC, merged