[AOT] Create custom section for aot binary format
WasmEdge/WasmEdge pull request #295
Opened 2021-07-18 17:30 UTC by ibmibmibm

* Add test for custom section version
* Changes in aot format:
  - Remove init function
  - Remove types/codes array
  - Add intrinsic variable

2021-09-18 12:46 UTC, hydai submitted a review, later dismissed

2021-09-18 12:46 UTC, hydai commented
LGTM, please rebase to the latest master

2021-09-29 05:27 UTC, q82419 requested changes

2021-09-29 05:27 UTC, q82419 commented on lib/ast/section.cpp
> +#if WASMEDGE_OS_LINUX
Should include `common/defines.h` in this file.

2021-09-29 05:27 UTC, q82419 commented on lib/system/allocator.cpp
> +bool Allocator::set_chunk_readable_writable(uint8_t *Pointer,
Please fix for clang-format.

2021-10-01 04:24 UTC, q82419 approved these changes

2021-10-01 04:24 UTC, merged