[Proposal] component model (loading part)
WasmEdge/WasmEdge pull request #3036
Opened 2023-11-15 08:23 UTC by dannypsnl

- [x] custom section
- [ ] core:module
- [ ] core:instance
- [ ] core:type
- [ ] component
- [ ] instance
- [ ] alias
- [ ] type
- [ ] canon
- [ ] start
- [ ] import
- [ ] export

#2943 loading

2023-11-15 08:23 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2023-11-15 09:36 UTC, dannypsnl commented on lib/loader/ast/component.cpp
> +      // for now.
Seems the trouble is starting from `include/ast/section.h`, not here

2023-11-15 09:46 UTC, dannypsnl commented on include/ast/section.h
> +
The fix cannot be seemed as correct

1. `Span` is not provided here.
2. Now we have to ensure `Component *` didn't get misused.

2023-11-15 09:47 UTC, dannypsnl commented on include/loader/loader.h
> +  std::vector<Byte> ComponentVersion = {0x0d, 0x00, 0x01, 0x00};
This will with a final change when component model is "complete"

2023-11-28 05:58 UTC, dannypsnl commented
`IWYU checker / macOS` failed since it failed to install python 3.11....

2023-11-28 06:14 UTC, hydai commented
> `IWYU checker / macOS` failed since it failed to install python 3.11....

Should we remove all possible `2to3*`?

2023-11-28 06:42 UTC, dannypsnl commented
That's triggered by llvm17, can we control that?

2023-11-28 06:57 UTC, hydai commented
> That's triggered by llvm17, can we control that?

Nope. So I guess we have to remove the 2-to-3, which is installed by other pre-shipped packages to make the llvm install correctly.

2023-11-29 06:17 UTC, dannypsnl commented on include/ast/component/sort.h
> +};
reuse same class for SortIndex and CoreSortIndex

The problem here is in alias section, we want to load both; but in instance section, distinction can help us form better type, this is place that we might need higher type.

2023-11-29 06:17 UTC, dannypsnl commented on include/ast/module.h
> +};
Here, unlike nested component, we no need to wrap module again (no recursive definition)

2023-11-29 06:37 UTC, dannypsnl commented on include/ast/component/sort.h
> +};
A potential solution here is using `std::variant`

2023-12-11 09:33 UTC, dannypsnl commented on lib/loader/filemgr.cpp
> +
note, better just remove it

2023-12-11 09:33 UTC, dannypsnl commented on lib/loader/ast/type.cpp
>    }
recover this

2023-12-14 03:24 UTC, q82419 requested changes
1. Add the `Component` in `AST` namespace.
2. Rebase onto the master branch.

2023-12-14 03:24 UTC, q82419 commented on lib/loader/ast/component.cpp
> +      if (Ver != ModuleVersion) {
unikely()

2023-12-14 03:24 UTC, q82419 commented on lib/loader/ast/component.cpp
> +      if (Ver != ComponentVersion) {
unlikely

2023-12-14 03:24 UTC, q82419 commented on lib/loader/ast/comptype.cpp
> +  if (Label.size() != *RLen) {
unlikely

2023-12-14 03:24 UTC, q82419 commented on lib/loader/ast/comptype.cpp
> +    if (Ty.getTypes().size() == 0) {
unlikely

2023-12-14 03:24 UTC, q82419 commented on include/ast/component/type.h
> +  Bool,
Assign the value number into this enum class (maybe uint8_t?)

2023-12-14 03:24 UTC, q82419 commented on lib/loader/ast/comptype.cpp
> +  case 0x7f: // bool
We can use the value of  member of enum class to determine the malformed input.

2023-12-14 03:24 UTC, q82419 commented on lib/loader/ast/comptype.cpp
> +  if (auto RTag = FMgr.readByte(); !RTag) {
if (auto RTag =  .... ) {
} else {
  return Unexpect(RTag);
}

2023-12-14 03:24 UTC, q82419 commented on lib/loader/ast/comptype.cpp
> +  if (auto Res = loadType(Ty.getValType()); !Res) {
return loadType(...)

2023-12-14 03:24 UTC, q82419 commented on lib/loader/ast/comptype.cpp
> +  if (Res) {
if (auto Res = ...)

2023-12-14 03:24 UTC, q82419 commented on lib/loader/ast/comptype.cpp
> +    if (Ty.getLabels().size() == 0) {
unlikely

2023-12-14 03:24 UTC, q82419 commented on lib/loader/ast/instance.cpp
> +  if (auto Res = FMgr.readName(); !Res) {
Reverse the if-else statement.

2023-12-14 03:24 UTC, q82419 commented on lib/loader/ast/instance.cpp
> +  if (auto Res = FMgr.readName(); !Res) {
Reverse the if-else statement.

2023-12-14 03:24 UTC, q82419 commented on include/ast/component/sort.h
> +enum class CoreSort {
Assign the values.

2023-12-14 03:24 UTC, q82419 commented on include/ast/component/sort.h
> +enum class SortCase {
Assign the values.

2023-12-14 03:24 UTC, q82419 commented on lib/loader/ast/sort.cpp
> +  case 0x00: {
Use the assigned values in the enum class.

2024-01-02 06:43 UTC, q82419 requested changes
1. Add the component model proposal enum.
2. Add the proposal description in tools.
3. Add the warning message (experimental) when turn-on and detect a component model unit loaded.

2024-01-02 08:54 UTC, q82419 approved these changes

2024-01-02 09:02 UTC, dannypsnl commented
@hydai This is ready to merge.

2024-01-02 09:12 UTC, q82419 approved these changes

2024-01-02 09:16 UTC, merged