Proper  initialization of DLInfo
WasmEdge/WasmEdge pull request #3059
Opened 2023-11-28 00:22 UTC by khagankhan

Fixed https://github.com/WasmEdge/WasmEdge/issues/3014

2023-11-28 00:22 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2023-11-28 03:41 UTC, khagankhan commented on lib/plugin/plugin.cpp
> +    fprintf(stderr, "Error: dladdr failed to find the shared object or symbol.\n");
Gotcha!

2023-11-28 03:41 UTC, khagankhan commented on lib/plugin/plugin.cpp
> +    auto initialPath = std::filesystem::u8path(DLInfo.dli_fname);
Okay!

2023-11-28 03:42 UTC, khagankhan commented on lib/plugin/plugin.cpp
> +    exit(EXIT_FAILURE);
Got it!

2023-11-28 03:43 UTC, khagankhan commented on lib/plugin/plugin.cpp
> +    auto LibPath = parentPath.lexically_normal();
Oh! Probably forgot after debugging!

2023-11-28 03:44 UTC, khagankhan commented
I will address the comments asap and will update it! Thanks!

2023-12-11 15:19 UTC, dannypsnl commented
@khagankhan Do you have any updates?

2023-12-11 23:52 UTC, khagankhan commented
Hey! Sorry for that, it is end of the semester so I have been busy with the that of late. I will have done the necessary updates by the end of this week!

2023-12-13 23:55 UTC, khagankhan reviewed
Addressed the change requests. MSAN report does not appear for the `DLInfo.dli_fname` because it is now checked before used. The error message is used with `spdlog::error`. I may look at the usage of `parental_path()` and `lexically_normal()` down the road because I ran into something that may be interesting.

2023-12-14 06:00 UTC, dannypsnl requested changes

2023-12-14 06:00 UTC, dannypsnl commented on lib/plugin/plugin.cpp
> +    spdlog::error("Error: dladdr failed to find the shared object or symbol.");
You will need to abort the process, @hydai do you know how we usually do this?

2023-12-14 06:00 UTC, dannypsnl commented on lib/plugin/plugin.cpp
> +    spdlog::error("Error: dladdr failed to find the shared object or symbol.");
Except that I think the PR is ok

2023-12-14 06:01 UTC, dannypsnl commented
You will need to sign your commit, which means each commit message will have a email line, and you can use rebase master to squash the commits.

2023-12-19 22:34 UTC, khagankhan commented
Hey, if it needs to abort after the error message. I can commit and sign it subject to the approval!

Best, 

-Khan

2023-12-20 01:36 UTC, dannypsnl commented
Sure, please do so.

2023-12-24 15:01 UTC, hydai requested changes

2023-12-24 15:01 UTC, hydai commented on lib/plugin/plugin.cpp
> +  if (Status != 0 && DLInfo.dli_fname != nullptr) {
We should have this condition inside the `Status != 0`.
You can find that the `else` only handles the `DLInfo.dli_fname == nullptr` with the given error message. However, one possible failure is that the `dladdr` fails and returns 0.

2024-01-02 08:12 UTC, dannypsnl approved these changes

2024-01-02 08:13 UTC, dannypsnl commented
@khagankhan Please sign-off your commits, so @hydai can merge it.

2024-01-02 09:03 UTC, khagankhan commented
Hey! Thank you for the addressing the last comment! I will make it ready during the day. Thanks, guys! Appreciate it!

2024-01-02 10:10 UTC, khagankhan commented
rebased the branch to sign off the previously unsigned commits.

2024-01-02 10:21 UTC, khagankhan commented
I absolutely have no idea how these commits appeared. If needed to resolve the conflicts, I can close and make another PR with just one commit to resolve the bug.

2024-01-02 10:25 UTC, khagankhan commented
A new PR is made. This PR is hard to resolve and does not reflect the exact problem, solution, and the purpose.

2024-01-02 10:25 UTC, closed without merging

2024-01-02 10:26 UTC, hydai commented
If you are rebasing to the master, these commits should not happen because all of them are in the commits history of the master branch if you have no idea how to fix it. Please check out a new branch from the master branch and cherry-pick your commits into the new branch.

2024-01-02 10:42 UTC, khagankhan commented
Absolutely! It is about time to make a  new PR after carefully addressing each comment in a single commit. Sorry for inconvenience and thank you for the help!