[WASI-NN] ggml: handle prompt too long error
WasmEdge/WasmEdge pull request #3131
Opened 2024-01-02 09:44 UTC by dm4

- Related to https://github.com/WasmEdge/WasmEdge/issues/3130
- Also update ggml to b1743

2024-01-02 09:44 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-01-02 10:06 UTC, hydai requested changes
We would be better to use `int32_t` or `int64_t` instead of `int`.

2024-01-02 11:38 UTC, dm4 commented on plugins/wasi_nn/ggml.cpp
> +  if (static_cast<int>(CxtRef.LlamaInputs.size()) > MaxTokensListSize) {
Just add a commit to replace int to `uint64_t ` or `int32_t` for llama token calculation.

2024-01-03 02:44 UTC, hydai approved these changes

2024-01-03 05:37 UTC, merged