llvm JIT support
WasmEdge/WasmEdge pull request #3191
Opened 2024-02-01 07:08 UTC by ibmibmibm

* [AOT] Move LLVM-related code into separate directory
    * Rename cmake config WASMEDGE_BUILD_AOT_RUNTIME into WASMEDGE_USE_LLVM
    * Separate out `CodeGen` function from `Compiler` class
    * Add `LLVM::Data` class for transfer `LLVM::Context` and `LLVM::Module`
* [JIT] Add llvm orcjit as dependency
* [JIT] Use OrcThreadSafeContext and OrcThreadSafeModule
* [JIT] Create interface class `Executable` to hold shared library, AOT section and JIT library in `Symbol`
    * Move `Wrapper` and `IntrinsticsTable` into `Executable
    * Split `SharedLibrary` into two class
    * Remove LDMgr
    * Add `loadExecutable` in `Loader`
* [JIT] Add LLVM JIT Support
    * Add `LLVM::JITLibrary`
    * Add new command line option for enabling JIT

2024-02-01 07:08 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-02-07 10:47 UTC, hydai requested changes

2024-02-07 11:38 UTC, hydai approved these changes

2024-02-07 11:39 UTC, hydai requested changes
@ibmibmibm 
I found the CI failed due to the `lld` is not recognized.

2024-02-13 06:54 UTC, hydai submitted a review, later dismissed

2024-02-13 07:04 UTC, hydai commented
@ibmibmibm 
I found that the new way to detect LLD is not working on several CI jobs.

2024-02-14 09:08 UTC, hydai approved these changes

2024-02-14 09:09 UTC, merged