[Docker] manylinux_2_28 (#3188)
WasmEdge/WasmEdge pull request #3224
Opened 2024-02-16 10:53 UTC by 0yi0

2024-02-16 10:53 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-02-23 06:29 UTC, hydai requested changes

2024-02-23 06:29 UTC, hydai commented on utils/docker/Dockerfile.manylinux_2_28_x86_64
> +RUN cd && (yum check-update || true) && yum install -y openssl-devel rpm-build cmake && \
Do we need cmake here if we build from source at line 25

2024-02-23 17:44 UTC, hydai approved these changes

2024-02-24 01:53 UTC, merged