[Changelog] Update the changelog for the 0.14.0-alpha.2 pre-release.
WasmEdge/WasmEdge pull request #3227
Opened 2024-02-19 07:53 UTC by q82419

2024-02-19 07:53 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-02-23 06:25 UTC, hydai requested changes

2024-02-23 06:25 UTC, hydai commented on .CurrentChangelog.md
> +  * Bump llama.cpp to b2037.
2230 now.

2024-02-23 06:25 UTC, hydai commented on .CurrentChangelog.md
> +  * Support Llava inference.
One more model, `Gemma`, is supported after shipping Llava.

2024-02-23 07:58 UTC, hydai requested changes

2024-02-23 07:58 UTC, hydai commented on .CurrentChangelog.md
> +  * Support Llava and Gemma inference.
Gemma should be a standalone line. It will not use the following two options.

2024-02-23 09:58 UTC, hydai approved these changes

2024-02-23 10:43 UTC, merged