[WASI] Remove path checking when creating directory
WasmEdge/WasmEdge pull request #3246
Opened 2024-02-27 06:54 UTC by tannal

This patch attempt to fix #3231.

The resolvePath function uses fstatat for path resolution, which will return error when the relative path (foo) is not exist.

2024-02-27 06:54 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-02-27 13:13 UTC, hydai requested changes

2024-02-27 13:13 UTC, hydai commented on lib/host/wasi/vinode.cpp
> -  if (auto Res = resolvePath(Fd, Path); unlikely(!Res)) {
We should handle the special cases inside the `resolvePath` function. Removing the path checking is not the correct way to fix this issue.

2024-02-27 19:29 UTC, dannypsnl commented
Please check the failed tests and sign your commits by adding email line.

2024-03-01 12:36 UTC, tannal commented
For ubuntu machine, we might need to install liblld-14-dev(depends on the llvm version) here.

https://github.com/WasmEdge/WasmEdge/actions/runs/8111354854/workflow?pr=3246#L46

2024-03-04 09:32 UTC, ibmibmibm approved these changes

2024-03-04 18:10 UTC, ibmibmibm approved these changes

2024-03-04 18:11 UTC, hydai approved these changes

2024-03-04 18:11 UTC, merged