[Proposal] Exception-Handling proposal for interpreter
WasmEdge/WasmEdge pull request #3306
Opened 2024-03-25 21:42 UTC by q82419

2024-03-25 21:42 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-04-03 04:56 UTC, q82419 commented
Test data:

Function "br" - jump out the block and erase values on stack.
Function "iter" - for-loop with calling the function "br".

```wasm
(module
  (func $f1 (export "br")
    (block $b1
      (i32.const 1)
      (i32.const 2)
      (i32.const 3)
      (i32.const 4)
      (i32.const 5)
      (block $b2
        (i32.const 1)
        (i32.const 2)
        (i32.const 3)
        (i32.const 4)
        (i32.const 5)
        br $b1
      )
      unreachable
    )
  )
  (func (export "iter") (param $n i32)
    (loop $l
      local.get $n
      i32.const 1
      i32.sub
      local.tee $n
      i32.const 0
      i32.gt_u
      call $f1
      br_if $l
    )
  )
)
```

Test command (with CLI): iterate 2M times.

```bash
./wasmedge --reactor test.wasm iter 2000000
```

Time measurement:

- master: average `4.01s`
- this PR: average `4.44s`

2024-04-17 22:58 UTC, ibmibmibm requested changes

2024-04-17 22:58 UTC, ibmibmibm commented on lib/executor/helper.cpp
> +                                      Runtime::Instance::TagInstance *TagInst,
Change to `Runtime::Instance::TagInstance &TagInst`

2024-04-29 07:58 UTC, ibmibmibm approved these changes

2024-04-29 09:02 UTC, merged