[Installer] Support a pure bash script installer
WasmEdge/WasmEdge pull request #3313
Opened 2024-04-01 19:20 UTC by hydai

Fixes #3300

2024-04-01 19:20 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-04-01 19:28 UTC, SAtacker requested changes
At a glance, it seems to be alright, noice!  
We should have tests for this as well.

2024-04-02 08:29 UTC, hydai commented
Hi @SAtacker 
The CI workflow has been added. Please note that this installer is not designed for legacy systems such as CentOS 7 or any EOL OS. Manylinux2014 will also be deprecated in June.

2024-04-03 00:41 UTC, SAtacker approved these changes

2024-04-03 00:44 UTC, merged