Supported WASI-NN streaming extension for NNRPC.
WasmEdge/WasmEdge pull request #3386
Opened 2024-05-06 04:14 UTC by arvganesh

2024-05-06 04:14 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-05-20 14:35 UTC, hydai requested changes

2024-05-20 14:35 UTC, hydai commented on test/plugins/wasi_nn/wasi_nn.cpp
> +  // Get the function "get_output_single".
I got confused. Why do you add these tests to the OpenVINO backend? The OpenVINO backend does not implement these LLM-related extension functions. That's why the unit tests will fail when trying to get the non-existing functions.

2024-05-24 09:50 UTC, AkihiroSuda commented on plugins/wasi_nn/wasinnfunc.cpp
> +    auto Status = Stub->GetOutput(&ClientContext, Req, &Res);
```suggestion
    auto Status = Stub->GetOutputSingle(&ClientContext, Req, &Res);
```

2024-05-26 03:06 UTC, hydai commented
Hi @arvganesh 
Are you going to finish this PR?

2024-06-03 15:20 UTC, AkihiroSuda commented on plugins/wasi_nn/wasinnfunc.cpp
> +    auto Status = Stub->GetOutput(&ClientContext, Req, &Res);
ping @arvganesh

2024-06-26 09:24 UTC, hydai commented
Closing this due to inactive. Replace by #3506

2024-06-26 09:24 UTC, closed without merging