[CMake] Merge and move the simdjson fetching.
WasmEdge/WasmEdge pull request #3426
Opened 2024-05-24 10:45 UTC by q82419

2024-05-24 10:45 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/). Here are my reviews of code commits in this PR.

------

2024-05-24 10:51 UTC, hydai approved these changes

2024-05-24 11:17 UTC, hydai commented
@q82419 Windows failed.

2024-05-24 11:17 UTC, hydai requested changes
Windows failed

2024-05-27 09:36 UTC, hydai approved these changes

2024-05-27 10:23 UTC, merged