enables usage of parameter `--no-mmap` from llama.cpp
WasmEdge/WasmEdge pull request #3436
Opened 2024-05-28 15:30 UTC by Fusaaaann

This pull request integrates simple support on mmap by adding the parameter to `Graph`, `load()`, `parseMetadata()` of GGML plugin.

`UseMMap` is set to true by default, and will be set to false if `--no-mmap` is presented to the program calling `wasi-nn` SDK.

In upcoming updates of this PR, I will attach changes made to example of LlamaEdge that support `--no-mmap` since it is only adjustable through parameter passed to the end program.

Is mmap in [lib/system/mmap.cpp](https://github.com/WasmEdge/WasmEdge/blob/master/lib/system/mmap.cpp) more preferred than simply passing into llama.cpp using model parameter?

2024-05-28 15:30 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/). Here are my reviews of code commits in this PR.

------

2024-05-29 03:22 UTC, hydai requested changes

2024-05-29 03:23 UTC, hydai commented
@Fusaaaann 
Thanks for this; please don't use the `git merge` command to create a redundant merge node to avoid failing the DCO check. Also, you will need to sign your commits with DCO. Ref: https://www.secondstate.io/articles/dco/

2024-05-29 08:50 UTC, Fusaaaann commented on plugins/wasi_nn/ggml.h
> +  bool UseMMap = true;
according to [the latest version](https://github.com/ggerganov/llama.cpp/blob/0e8d8bfd6caf1d0a8cbdf9d3d5c06fbbb9dfced8/common/common.h#L167), use_mmap is set true by default

2024-05-30 13:31 UTC, Fusaaaann commented
> @Fusaaaann Thanks for this; please don't use the `git merge` command to create a redundant merge node to avoid failing the DCO check. Also, you will need to sign your commits with DCO. Ref: [secondstate.io/articles/dco](https://www.secondstate.io/articles/dco/)

I have done signing my commit and merge the changes using `git rebase`. DCO check has passed now.

2024-05-30 13:53 UTC, hydai approved these changes

2024-05-30 14:43 UTC, merged