[Plugin] Support stable diffusion.cpp
WasmEdge/WasmEdge pull request #3444
Opened 2024-06-02 08:36 UTC by grorge123

2024-06-02 08:36 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-06-07 09:27 UTC, hydai requested changes

2024-06-11 12:54 UTC, hydai requested changes

2024-06-18 07:03 UTC, hydai commented
Hi @grorge123 
Please fix the linter issue and rebase to the latest master, thanks.

2024-06-18 11:04 UTC, hydai commented
@q82419 
Will the test verify the number of the mock plugins?

2024-06-19 09:39 UTC, dannypsnl requested changes

2024-06-19 09:39 UTC, dannypsnl commented on test/plugins/wasmedge_stablediffusion/wasmedge_stablediffusion.cpp
> +        Errno));
I think a better approach is comment beside each argument, so ppl no need to compare.

2024-06-19 09:39 UTC, dannypsnl commented on test/plugins/wasmedge_stablediffusion/wasmedge_stablediffusion.cpp
> +                         // Schedule=DEFAULT, Other is false
same

2024-06-19 09:39 UTC, dannypsnl commented on plugins/CMakeLists.txt
> +endif()
Tests only run on Linux, maybe we need to exclude platforms here as well?

2024-06-25 07:53 UTC, hydai approved these changes
LGTM. @dannypsnl PTAL

2024-06-26 07:35 UTC, dannypsnl approved these changes

2024-06-26 08:19 UTC, merged