WASM C API Proposal
WasmEdge/WasmEdge pull request #346
Opened 2021-08-10 10:17 UTC by q82419

2026-08-03 09:11 UTC, q82419 commented on thirdparty/wasm/wasm.hh
> +  }
Don't modify thirdparty files

2026-08-03 09:11 UTC, q82419 commented on thirdparty/wasm/wasm.hh
> +  static auto make() -> vec {
Don't modify thirdparty files

2026-08-04 10:02 UTC, q82419 commented on test/api/APIWasmCExampleTest.cpp
> +}
false possitive

2026-08-27 04:40 UTC, hydai requested changes

2026-08-27 04:40 UTC, hydai commented on thirdparty/wasm/wasm.h
> +// WebAssembly C API
What is the license?

2026-08-27 06:53 UTC, hydai approved these changes

2026-08-27 12:56 UTC, merged