[Utils] Installer:  Deprecate 0.12.x
WasmEdge/WasmEdge pull request #3476
Opened 2024-06-16 04:42 UTC by SAtacker

- Ref- https://github.com/WasmEdge/WasmEdge/issues/3432

2024-06-17 04:55 UTC, q82419 requested changes

2024-06-17 04:55 UTC, q82419 commented on utils/install.py
> +EXTENSIONS = [TENSORFLOW]
You can remove all the extensions. We only reserve plugins.

2024-06-17 04:55 UTC, q82419 commented on utils/install.py
> +    "Linux" + "x86_64" + TENSORFLOW: VersionString("0.13.0"),
Ditto.

2024-06-18 05:28 UTC, hydai commented
@SAtacker Let's remove CentOS 8 Stream. It's EOL, so we are not able to install any packages from the package manager system.

2024-06-18 05:31 UTC, hydai commented
Also, please update `python3 utils/install.py -v 0.13.5 --plugins wasi_nn-ggml-b2781` to `python3 utils/install.py -v 0.13.5 --plugins wasi_nn-ggml-b3075`.

2024-06-18 07:27 UTC, q82419 requested changes
You can remove the download link from `"second-state/WasmEdge-tensorflow"` because it provides the extensions. Reserve the `"-deps"` only.

And also, `tf_deps_version` is fixed as `"TF-2.12.0-CC"` now because we use this version after `0.13.0`. And beware that from this version, `aarch64` is supported for the deps.

2024-06-18 07:27 UTC, q82419 commented on utils/install.py
> -    download_tf_tools_=False,
I think the `download_tf_` and `download_tf_lite_` can be removed, too?

2024-06-18 07:27 UTC, q82419 commented on utils/install.py
> -    download_tf_tools = download_tf_tools_
Ditto.

2024-06-18 07:27 UTC, q82419 commented on utils/install.py
> -        download_tf_tools,
Ditto.

2024-06-21 04:36 UTC, hydai commented
Hi @SAtacker 
Thanks for this PR. I found that `test-python-install-script / manylinux2014 aarch64 (pull_request)` failed due to some weird issue. This error should not related to your changes here. Maybe we can move forward to merge this PR first and figure out the above error later. WDYT?

2024-06-21 20:00 UTC, SAtacker commented
> Hi @SAtacker Thanks for this PR. I found that `test-python-install-script / manylinux2014 aarch64 (pull_request)` failed due to some weird issue. This error should not related to your changes here. Maybe we can move forward to merge this PR first and figure out the above error later. WDYT?

I see. Let's do it!

2024-06-24 04:23 UTC, hydai approved these changes
@q82419 PTAL

2024-06-24 05:18 UTC, q82419 requested changes

2024-06-24 05:18 UTC, q82419 commented on utils/install.py
> -        ),
Delete the `TENSORFLOW` and `TENSORFLOW_LITE` entries.

2024-06-25 14:59 UTC, hydai approved these changes
LGTM. @q82419 PTAL

2024-06-26 04:52 UTC, q82419 approved these changes
LGTM

2024-06-26 05:16 UTC, merged