[CI] Add the build and release CI of stable diffusion plugin.
WasmEdge/WasmEdge pull request #3557
Opened 2024-07-11 10:12 UTC by q82419

2024-07-11 10:38 UTC, hydai approved these changes

2024-07-11 12:05 UTC, hydai requested changes
CI failed.

2024-07-17 07:14 UTC, hydai commented
Hi @grorge123 
We are going to provide stable diffusion pre-built assets. However, the unit tests failed. Could you please help check this?

2024-07-17 07:59 UTC, grorge123 commented
Hi! I have fixed it with this [PR](https://github.com/WasmEdge/WasmEdge/pull/3568). Please check again, thank you.

2024-07-17 16:10 UTC, hydai approved these changes

2024-07-17 17:10 UTC, merged