translate doc/c_api_quick_start to simplified Chinese
WasmEdge/WasmEdge pull request #358
Opened 2021-08-14 14:11 UTC by kenvifire

translate doc/c_api_quick_start to simplified Chinese

2021-08-14 15:05 UTC, hydai commented
Hi @kenvifire,
中英文間應都以空格隔開會比較合適，如 `中文English中文` 應該改為 `中文 English 中文`

2021-08-14 15:18 UTC, kenvifire commented
@hydai 
Spaces added, please check again, thanks!

2021-08-16 22:48 UTC, kenvifire commented
Hi @hydai 
Any update on this MR?

2021-08-17 02:28 UTC, hydai requested changes

2021-08-17 02:28 UTC, hydai commented on docs/c_api_quick_start_zh.md
> +假设 WASM 文件[`fibonacci.wasm`](../tools/wasmedge/examples/fibonacci.wasm)已经被拷贝到当前目录，并且C文件`test_wasmedge.c`的源代码如下所示：
`并且C文件`test_wasmedge.c`的源代码如下所示`
->
`并且 C 文件 `test_wasmedge.c` 的源代码如下所示`

2021-08-17 02:28 UTC, hydai commented on docs/c_api_quick_start_zh.md
> +接下来你可以编译并且运行它：（索引从0开始的情况下，斐波那契数列的的第32个数值是5702887）
The number should also have a space between Chinese characters.

2021-08-17 02:28 UTC, hydai commented on docs/c_api_quick_start_zh.md
> +假设 WASM 文件 [`fibonacci.wasm`](../tools/wasmedge/examples/fibonacci.wasm) 已经被拷贝到当前目录，并且C文件`test_wasmedge_compiler.c`的代码如下所示：
Ditto.

2021-08-17 02:28 UTC, hydai commented on docs/c_api_quick_start_zh.md
> +接下来你可以编译和运行它（输出的文件是"fibonacci.wasm.so"）：
Ditto.

2021-08-17 14:04 UTC, hydai commented
Please do not use `create a merge commit` to sync with the latest master, this will make the DCO check fail.
To fix this, try to use `fast-forward merge` or `rebase` to correct the commit history. Thanks.

2021-08-17 15:11 UTC, hydai approved these changes

2021-08-17 15:11 UTC, merged