[Installer] v2: Allow users to disable WASI-Logging via --nowasilogging
WasmEdge/WasmEdge pull request #3587
Opened 2024-07-22 18:56 UTC by hydai

cc @L-jasmine 
This should prevent the installer v2 from installing a was-logging plugin for the toxin use cases.

We will remove the wasi-logging plugin from all installers after it is migrated into the built-in libwasmedge.

2024-07-22 18:56 UTC, juntao commented
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-07-22 21:37 UTC, SAtacker requested changes
@L-jasmine could you please also include a simple test case in the CI ? Something which checks if the plugin is not downloaded when the option is provided and downloaded when it is not provided by default.

Thanks!

2024-07-23 02:38 UTC, dannypsnl approved these changes

2024-07-23 04:03 UTC, hydai commented
@SAtacker 
Sure, I will add a test for it later; thanks for the reminder.

2024-07-23 15:06 UTC, SAtacker approved these changes

2024-07-23 15:06 UTC, merged