added linelint workflow
WasmEdge/WasmEdge pull request #3592
Opened 2024-07-24 07:42 UTC by arujjval

closes #3519

2024-07-24 07:42 UTC, juntao commented
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-07-24 08:29 UTC, dannypsnl commented
In the log we can see,
```
[EOF Rule] File ".clang-tidy" has lint errors
[EOF Rule] File ".clang-tidy" lint errors fixed
```
However, there are no changes are proposed to GitHub, you need to fill that gap.

2024-07-24 09:37 UTC, arujjval commented
@dannypsnl This is fixing eof errors in our repo as we have made a PR. This is what was requested in the issue #3592.

2024-07-24 11:16 UTC, hydai commented
@dannypsnl 
I changed my mind. Let's use this linelint workflow only for detection. I don't think using autofix is a good idea now if a malicious hacker hijacks the linelint workflow, and it will allow the workflow to inject or modify some code into our codebase directly.

@0yi0 WDYT?

2024-07-24 11:22 UTC, hydai commented
We should also add the following limitation to the workflow file to keep it safe:

```
permissions:
  contents: read
```

2024-07-24 11:25 UTC, 0yi0 requested changes

2024-07-24 11:25 UTC, 0yi0 commented on .github/workflows/linelint.yml
> +        uses: fernandrone/linelint@master
Already mentioned in the old PRs, please use a tag instead of master.

2024-07-24 11:25 UTC, 0yi0 commented on .github/workflows/linelint.yml
> +        uses: actions/checkout@v2
`actions/checkout@v2` is a very legacy version, please use `v4` or add a reason for it.

2024-07-24 11:29 UTC, 0yi0 commented
@hydai No autofix sounds good to me. But if we're not running autofix, should CI report failure on lint errors?

2024-07-24 11:31 UTC, hydai commented
Definitely, we should let CI fail if the changed files do not contain EOF. Just like what we did in the misc linter.

2024-07-24 11:37 UTC, 0yi0 commented
@arujjval dannypsnl means your workflows only fix it in the workflows **without** any modifications to the code base (the PR or the reporitory). So `autofix` being `true` or `false` didn't matter in the PR because no changes were committed.

2024-07-24 22:08 UTC, arujjval commented
So I have to remove autofix, and only check incoming changes for EOF error?

2024-07-27 05:24 UTC, 0yi0 commented
@arujjval I'm wondering if we can keep `autofix: true` in `.linelint`, and use `autofix: false` in `linelint.yml`, so that when `linelint.yml` reports error, user can use your `.linelint` config directly to fix their issues.

If this works, `.linelint` is already good and need no modifications. You only need to update `linelint.yml`, and then we can merge.

I hope I explained it well. Please let met know if you have questions about this.

2024-07-29 02:26 UTC, arujjval commented
I am not able to make this lint run only on changed modified files. Instead of running a command, I am "using" the repo of linelint. One thing we can do is install linelint in the repo and then running script in workflow. Can we that or is there any other way round?

2024-07-29 05:32 UTC, dannypsnl commented
> I am not able to make this lint run only on changed modified files.

I believe you can add
```sh
git diff <branch> --name-status
```
for example, this PR merge 2 commits into master, so
```sh
git diff master --name-status
```
let sed out the files.

2024-07-30 06:46 UTC, arujjval commented
I am able to get modified files and I am passing it while running linelint, but it is still running on all files. What can be the potential issues?
![Screenshot from 2024-07-30 12-14-47](https://github.com/user-attachments/assets/b4690491-4565-4037-a486-f1c76c1b15d8)

2024-07-30 10:30 UTC, 0yi0 commented
I checked the source code of this action, it doesn't seem to provide input fields.

It runs `linelint` like this
```
ENTRYPOINT ["/linelint", "."]
```

It's probably the same as the warning at the first line in your screenshot.

> Unexpected input(s) 'files', valid inputs are ['entryPoint', 'args']

I'm not sure if that means you can change `['entryPoint', 'args']` from input though.
If yes, you can try to set `args` to the list of files.

2024-07-30 11:01 UTC, arujjval commented
@0yi0 turns out we can change `args` from input. And it seems to work. But the issue is it is not ignoring other files. Here's the result after running with args and without args

![Screenshot from 2024-07-30 16-26-12](https://github.com/user-attachments/assets/5c093550-df15-4789-90bf-b553bee574c8)
with args

![Screenshot from 2024-07-30 16-25-41](https://github.com/user-attachments/assets/48f66082-a98a-4d6d-8e4d-7152268ec777)
without args

`args` seems to add files for lint check but it does not exclude other files. Or these files might be special case. Maybe we can correct lint error of these files (they are just 4) and then try.

2024-09-25 22:14 UTC, hydai commented
Hi @arujjval 
I'm sorry I missed this PR. Could you remind me of its current state? Is there any help you need to continue working on it?

2024-10-08 07:10 UTC, hydai commented
Closing due to inactive. Thanks.

2024-10-08 07:10 UTC, closed without merging