Fix fd_sync Error for Preopened Base Directory
WasmEdge/WasmEdge pull request #3613
Opened 2024-08-01 06:03 UTC by MeenuyD

Fix `fdSync` to Handle Directories in Linux Implementation.
I have updated the `fdSync` function in `inode-linux.cpp` to correctly handle synchronization requests for directories. The function now checks if the file descriptor is a directory and treats it as syncable, in addition to performing the `fsync` operation for regular files. This change ensures compatibility with other runtimes and aligns the behavior with the WASI specification.
#3039

2024-08-01 06:03 UTC, juntao commented
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-08-01 08:54 UTC, hydai requested changes
The coding style is not compatible with our standard, please fix it.

2024-08-01 09:03 UTC, MeenuyD commented
> The coding style is not compatible with our standard, please fix it.

How should I fix this to compatible with standard

2024-08-01 11:20 UTC, MeenuyD commented
Could you please help me in this

2024-08-13 01:50 UTC, dannypsnl requested changes

2024-08-13 01:50 UTC, dannypsnl commented on lib/host/wasi/inode-linux.cpp
> +  }
This logic is: if we get a directory, we ignore it. I don't think this is expected behaviour.

2024-10-08 07:09 UTC, hydai commented
Closing due to inactive.

2024-10-08 07:09 UTC, closed without merging