WIP: [Plugin] Make the wasi-logging as a built-in plugin.
WasmEdge/WasmEdge pull request #3617
Opened 2024-08-01 14:16 UTC by q82419

2024-08-01 14:16 UTC, juntao commented
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-08-01 16:49 UTC, hydai requested changes

2024-08-01 16:49 UTC, hydai commented on .github/workflows/matrix-extensions.json
> +}
EOF

2024-08-06 09:54 UTC, hydai requested changes

2024-08-06 09:54 UTC, hydai commented on lib/plugin/plugin.cpp
> +  parse(std::string_view Value) noexcept {
We should keep `std::string`. Ref: `include/po/parser.h`

2024-08-06 09:54 UTC, hydai commented on test/plugins/wasi_logging/wasi_logging.cpp
> +  WasmEdge::Plugin::Plugin::loadFromDefaultPaths();
We should add a comment to identify that `built-in plugin` is loaded in this function.

2024-08-06 09:54 UTC, hydai commented on test/plugins/wasi_logging/wasi_logging.cpp
> +  // Clear the memory[0, 64].
Number mismatched.

2024-08-06 09:54 UTC, hydai commented on test/plugins/wasi_logging/wasi_logging.cpp
> +  fillMemContent(MemInst, 224, std::string("Message 3 to file"));
Let's try `std::string_view`.

2024-08-06 20:16 UTC, hydai approved these changes
LGTM.

2024-08-06 20:17 UTC, hydai commented
Let's wait for CI pass.

2024-08-06 20:29 UTC, hydai approved these changes

2024-08-06 23:02 UTC, merged