Add forcely disable LTO option.
WasmEdge/WasmEdge pull request #362
Opened 2021-08-17 14:37 UTC by q82419

2021-08-18 13:57 UTC, hydai requested changes

2021-08-18 13:57 UTC, hydai commented on .CurrentChangelog.md
> +  * Added the option `WASMEDGE_FORCE_DISABLE_LTO` to forcibly disable link time optimization (`OFF` by default).
I prefer `WASMEDGE_DISABLE_LTO`

2021-08-18 13:57 UTC, hydai commented on cmake/Helper.cmake
> +if((CMAKE_BUILD_TYPE STREQUAL Release OR CMAKE_BUILD_TYPE STREQUAL RelWithDebInfo) AND NOT WASMEDGE_FORCE_DISABLE_LTO)
You SHOULD NOT combine these two conditions in one if statement. Instead, you should have another if statement to check `WASMEDGE_DISABLE_LTO` and then set the `WASMEDGE_INTERPROCEDURAL_OPTIMIZATION` to `OFF`.

2021-08-23 05:36 UTC, q82419 commented
Moved into the [PR359](https://github.com/WasmEdge/WasmEdge/pull/359).

2021-08-23 05:36 UTC, closed without merging