[Docs] Translate docs/build.md to simplified Chinese
WasmEdge/WasmEdge pull request #363
Opened 2021-08-18 14:51 UTC by kenvifire

Changes include:
- `build.md` remove duplicated sentence.
- `build_zh.md` translation for `build.md`.

2021-08-20 01:02 UTC, kenvifire commented
@hydai 
Please take a look at this MR when you're available, thanks!

2021-08-20 03:11 UTC, hydai requested changes

2021-08-20 03:11 UTC, hydai commented on docs/build.md
> -	* To disable building all tools, you can set the CMake option `WASMEDGE_BUILD_TOOLS` to `OFF`.
Why do you remove this line?

2021-08-20 07:01 UTC, kenvifire commented on docs/build.md
> -	* To disable building all tools, you can set the CMake option `WASMEDGE_BUILD_TOOLS` to `OFF`.
It's a duplicate of line 100.

2021-08-23 18:03 UTC, hydai approved these changes

2021-08-23 18:04 UTC, merged