[Docs] README, extensions, integrations, and use cases docs
WasmEdge/WasmEdge pull request #368
Opened 2021-08-26 19:00 UTC by juntao

Break the README into multiple documents for clarity. Update doc contents

2021-08-29 17:31 UTC, hydai approved these changes

2021-08-29 17:32 UTC, hydai requested changes
Seems like this branch should be rebased first

2021-08-30 18:59 UTC, juntao commented
> Seems like this branch should be rebased first

Please check if I did it correctly.

2021-08-31 10:27 UTC, hydai approved these changes

2021-08-31 10:28 UTC, merged