[CI][Docker] Add aarch64 for ubuntu 20.04
WasmEdge/WasmEdge pull request #3707
Opened 2024-08-29 08:24 UTC by 0yi0

2024-08-29 08:24 UTC, juntao commented
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-08-29 09:20 UTC, 0yi0 commented
Note: This check is not yet shown on the list https://github.com/WasmEdge/WasmEdge/actions/runs/10611454264

2024-08-30 07:12 UTC, hydai requested changes

2024-08-30 07:12 UTC, hydai commented on .github/workflows/build.yml
> +                {'name':'ubuntu-20.04','runner':'linux-arm-v2','compiler':'clang++','build_type':'Release','docker_tag':'ubuntu-20.04-build-clang-aarch64','tests':true},
It should be `linux-arm64-v2`. OAO

2024-08-30 09:26 UTC, 0yi0 commented on .github/workflows/build.yml
> +                {'name':'ubuntu-20.04','runner':'linux-arm-v2','compiler':'clang++','build_type':'Release','docker_tag':'ubuntu-20.04-build-clang-aarch64','tests':true},
QAQ

2024-08-30 10:31 UTC, hydai approved these changes

2024-08-30 11:32 UTC, merged