Add fast string hash
WasmEdge/WasmEdge pull request #3718
Opened 2024-09-02 08:49 UTC by ibmibmibm

2024-09-02 08:49 UTC, juntao commented
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-09-11 06:03 UTC, dannypsnl submitted a review, later dismissed

2024-09-19 19:33 UTC, hydai requested changes
Naming style issue

2024-09-19 19:33 UTC, hydai commented on lib/common/hash.cpp
> +  std::array<uint64_t, 4> secret;
`Secret`

2024-09-19 19:33 UTC, hydai commented on lib/common/hash.cpp
> +  const std::array<uint8_t, 70> c = {
`C`

2024-09-19 19:33 UTC, hydai commented on lib/common/hash.cpp
> +  for (size_t i = 0; i < 4; i++) {
`I`

2024-09-19 19:33 UTC, hydai commented on lib/common/hash.cpp
> +    bool ok;
`Ok`

2024-09-19 19:33 UTC, hydai commented on lib/common/hash.cpp
> +      for (size_t j = 0; j < 64; j += 8) {
`J`

2024-10-01 06:38 UTC, hydai requested changes
Fedora rawhide failed. It seems like the LLVM C API we used before is deprecated in the latest version

2024-10-01 07:53 UTC, ibmibmibm commented
> Fedora rawhide failed. It seems like the LLVM C API we used before is deprecated in the latest version

Fixing in #3809

2024-10-01 08:14 UTC, hydai approved these changes

2024-10-01 08:54 UTC, merged