[WIP][Wasi-nn] PyTorch AOTI
WasmEdge/WasmEdge pull request #3724
Opened 2024-09-03 07:59 UTC by LFsWang

https://pytorch.org/docs/stable/torch.compiler_aot_inductor.html

Add a support to load the AOTInductor for PyTorch.

- [ ] Merge this with origin PyTorch  plugin? 
- [ ] Add cuda support
- [ ] Check pytorch >= 2.2

2024-09-03 07:59 UTC, juntao commented
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-10-08 09:42 UTC, LFsWang commented
note: for manylinux_2_28_x86_64 , use  `add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)` and install pytorch with no c++11 abi will work

2024-10-08 10:05 UTC, hydai commented
> note: for manylinux_2_28_x86_64 , use `add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)` and install pytorch with no c++11 abi will work

I see, so there is still a compatible issue about the C++11 ABI in manylinux_2_28.

2024-10-22 06:53 UTC, hydai requested changes
Let's use the `[WASI-NN] Torch:` prefix for the logs.

2024-10-22 06:53 UTC, hydai commented on plugins/wasi_nn/wasinn_torch.cpp
> +          "[WASI-NN] CUDA Unavailable, platform Cannot support GPU target.");
```
"[WASI-NN] Torch: CUDA Unavailable. Please check if the installed Torch version or platform supports CUDA."sv
```

2024-10-22 06:53 UTC, hydai commented on plugins/wasi_nn/wasinn_torch.cpp
> +  spdlog::error("[WASI-NN] PyTorch Only support CPU and GPU target.");
```
"[WASI-NN] Torch: Unknown target device. We currently support only CPU and GPU targets."sv
```

2024-10-22 06:53 UTC, hydai commented on plugins/wasi_nn/wasinn_torch.cpp
> +    spdlog::error("[WASI-NN] PyTorch backend only supports output a tensor, "
```
"[WASI-NN] Torch: The output can only be one of the following tensor types: a tensor, a list of tensors, or a tuple of tensors."sv
```

2024-12-11 13:58 UTC, hydai requested changes

2024-12-11 13:58 UTC, hydai commented on plugins/wasi_nn/wasinn_torch.cpp
> +Expect<ErrNo> AOTInductor::loadFromBiary(std::istream &, Device) {
`Binary`

2024-12-11 13:58 UTC, hydai commented on plugins/wasi_nn/wasinn_torch.cpp
> +PyModelBackend GuessPyModelBackendType(const std::string_view &Model) {
`guessPyModelBackendType`

2024-12-11 13:58 UTC, hydai commented on plugins/wasi_nn/wasinn_torch.h
> +  Expect<ErrNo> loadFromBiary(std::istream &In, Device Device) override;
`Binary`

2024-12-11 13:58 UTC, hydai commented on plugins/wasi_nn/wasinn_torch.h
> +  Expect<ErrNo> loadFromBiary(std::istream &In, Device Device) override;
`Binary`

2024-12-24 19:28 UTC, hydai approved these changes

2024-12-29 18:01 UTC, merged