Rename `llm` and `ocr` plugins.
WasmEdge/WasmEdge pull request #3733
Opened 2024-09-04 12:41 UTC by q82419

2024-09-04 12:41 UTC, juntao commented
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-09-04 13:44 UTC, hydai requested changes

2024-09-04 13:44 UTC, hydai commented on CMakeLists.txt
> -if(WASMEDGE_BUILD_PLUGINS)
Do we no longer need this?

2024-09-05 04:24 UTC, hydai approved these changes

2024-09-05 04:43 UTC, hydai approved these changes

2024-09-05 07:46 UTC, merged