[Loader][Serializer]: Add tests for Typed Function References proposal's heap types
WasmEdge/WasmEdge pull request #3748
Opened 2024-09-08 21:17 UTC by elhewaty

2024-09-08 21:17 UTC, juntao commented
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-09-08 21:33 UTC, elhewaty commented
I think the type function reference proposal was implemented but there are no test cases that cover it, so I will start by adding tests for:
- [ ] Types.
- [ ] Instructions
that were added to the proposal.


I think I am declaring `ref $t` types the wrong way, can you help with this?
another problem is that I don't understand types or instructions with negative opcodes.
> T(FuncRef, 0x70, "func")           // -0x10 for heap type

why is it encoded using `0x70` but written in negative `-0x10` in the proposal?

2024-09-08 21:33 UTC, elhewaty commented
Oh, CC @hydai

2024-09-08 22:39 UTC, hydai commented
@q82419 PTAL

2024-09-09 01:23 UTC, dannypsnl commented
@elhewaty there are some commented code, do you need to convert this PR as draft?

2024-09-09 04:00 UTC, q82419 requested changes

2024-09-09 04:00 UTC, q82419 commented on test/loader/serializeTypeTest.cpp
> +  // Why does the following test give Segmentation fault
It's not segmentation fault. It ran into unreachable.
You should realize the constructors of `class ValType` first.

2024-09-09 04:02 UTC, q82419 commented
> I think the type function reference proposal was implemented but there are no test cases that cover it, so I will start by adding tests for:
> 
> * [ ]  Types.
> * [ ]  Instructions
>   that were added to the proposal.
> 
> I think I am declaring `ref $t` types the wrong way, can you help with this? another problem is that I don't understand types or instructions with negative opcodes.
> 
> > T(FuncRef, 0x70, "func")           // -0x10 for heap type
> 
> why is it encoded using `0x70` but written in negative `-0x10` in the proposal?

Please refer to this page: https://webassembly.github.io/function-references/core/appendix/index-types.html
Because the encoding of `s7`.

2024-09-10 19:32 UTC, elhewaty commented
@hydai @q82419 @dannypsnl 
what is wrong with this test?
```
// 4. test ref null
  GlobalType.setValType(WasmEdge::ValType(WasmEdge::TypeCode::RefNull, WasmEdge::TypeCode::ExternRef));
  Output = {};
  EXPECT_TRUE(Ser.serializeSection(createGlobalSec(GlobalType), Output));
  Expected = {
      0x06U,        // Global section
      0x05U,        // Content size = 5
      0x01U,        // Vector length = 1
      0x63U,        // RefNull type
      0x6FU,        // ExternRef heap type
      0x00U,        // Const mutation
      0x0BU         // Expression End
  };
  EXPECT_EQ(Output, Expected);
```

Error:
```
Output
    Which is: { '\x6' (6), '\x4' (4), '\x1' (1), 'o' (111, 0x6F), '\0', '\v' (11, 0xB) }
  Expected
    Which is: { '\x6' (6), '\x5' (5), '\x1' (1), 'c' (99, 0x63), 'o' (111, 0x6F), '\0', '\v' (11, 0xB) }
```

why did it ignored `RefNull` op code?

2024-09-11 02:24 UTC, dannypsnl commented
Don't ping everyone next time. From my understanding, you should check the implementation of `lib/loader/serialize/serial_type.cpp` to figure out how it runs into a problem.

2024-09-11 08:53 UTC, q82419 commented
> @hydai @q82419 @dannypsnl what is wrong with this test?
> 
> ```
> // 4. test ref null
>   GlobalType.setValType(WasmEdge::ValType(WasmEdge::TypeCode::RefNull, WasmEdge::TypeCode::ExternRef));
>   Output = {};
>   EXPECT_TRUE(Ser.serializeSection(createGlobalSec(GlobalType), Output));
>   Expected = {
>       0x06U,        // Global section
>       0x05U,        // Content size = 5
>       0x01U,        // Vector length = 1
>       0x63U,        // RefNull type
>       0x6FU,        // ExternRef heap type
>       0x00U,        // Const mutation
>       0x0BU         // Expression End
>   };
>   EXPECT_EQ(Output, Expected);
> ```
> 
> Error:
> 
> ```
> Output
>     Which is: { '\x6' (6), '\x4' (4), '\x1' (1), 'o' (111, 0x6F), '\0', '\v' (11, 0xB) }
>   Expected
>     Which is: { '\x6' (6), '\x5' (5), '\x1' (1), 'c' (99, 0x63), 'o' (111, 0x6F), '\0', '\v' (11, 0xB) }
> ```
> 
> why did it ignored `RefNull` op code?

As mentioned in the [ValType class](https://github.com/WasmEdge/WasmEdge/blob/master/include/common/types.h#L80-L85), WasmEdge migrated the `funcref` and `externref` types into `ref null funcref` and `ref null externref` respectively.
You can check the [binary format](https://webassembly.github.io/function-references/core/binary/types.html#reference-types) of reference types in the typed function reference proposal: to supporting old spec, the `funcref` reference type is equivilant to `ref null funcref`, which has a different binary encoding.
Therefore when serializing, we output the `funcref` and `externref` briefly when got the `ref null funcref` and `ref null externref` types.

2024-09-20 09:18 UTC, elhewaty commented
@q82419, Can you review this too?

2024-09-23 08:23 UTC, q82419 requested changes
Almost. Please help to add the fifth test, thanks!

2024-09-23 08:23 UTC, q82419 commented on test/loader/serializeTypeTest.cpp
> +  //   4. Test RefNull heap type.
Add 5.
Test Ref typeindex 5 heap type.

```
WasmEdge::ValType(WasmEdge::TypeCode::Ref, 5);
```

2024-09-24 14:21 UTC, elhewaty commented
@q82419 PTAL.

2024-09-24 14:40 UTC, q82419 approved these changes

2024-09-24 17:02 UTC, merged