[Loader][Serializer]: Add Function References Instructions and their tests
WasmEdge/WasmEdge pull request #3759
Opened 2024-09-12 20:25 UTC by elhewaty

Signed-off-by: Mohamed Atef <mohamedatef1698@gmail.com>

2024-09-12 20:25 UTC, juntao commented
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-09-13 09:29 UTC, elhewaty commented
CC @hydai

2024-09-19 12:09 UTC, q82419 requested changes
Well done. Please follow the requested changes. Thanks!

2024-09-19 12:09 UTC, q82419 commented on test/loader/serializeInstructionTest.cpp
> +  WasmEdge::AST::Instruction Br_on_null(WasmEdge::OpCode::Br_on_null);
Please follow the naming pattern above (i.e., `BrOnNull` for example).

2024-09-19 12:09 UTC, q82419 commented on test/loader/serializeInstructionTest.cpp
> +TEST(SerializeInstructionTest, SerializeFuncRefControlInstruction) {
The `br_on_null` and `br_on_non_null` instructions are both control instructions.
Move these into the `SerializeBrControlInstruction` test.

2024-09-19 12:09 UTC, q82419 commented on test/loader/serializeInstructionTest.cpp
> +  //   2.  Serialize br_on_non_null instruction.
In addition, you can add the fail case (`EXPECT_FALSE`) for testing these instructions without the typed function reference proposal config.

2024-09-19 12:09 UTC, q82419 commented on test/loader/serializeInstructionTest.cpp
> +TEST(SerializeInstructionTest, SerializeFuncRefCallInstruction) {
These are call instructions. Move them into the `SerializeCallInstruction` test.

2024-09-19 12:09 UTC, q82419 commented on test/loader/serializeInstructionTest.cpp
> +TEST(SerializeInstructionTest, SerializeRefAsNonNullInstruction) {
Move into `SerializeReferenceInstruction` test.

2024-09-20 09:18 UTC, elhewaty commented
@q82419, updated.

2024-09-23 07:55 UTC, q82419 requested changes

2024-09-23 07:55 UTC, q82419 commented on test/loader/serializeInstructionTest.cpp
> +  Conf.addProposal(WasmEdge::Proposal::FunctionReferences);
This line should be right before the 2. test.

2024-09-23 07:55 UTC, q82419 commented on test/loader/serializeInstructionTest.cpp
> +  //   2.  Serialize without Func-Ref proposal.
2. Serialize Br_on_null instruction with Func-Ref proposal.
3. Serialize Br_on_non_null instruction with Func-Ref proposal.
4. Serialize invalid Br_on_non_null instruction without Func-Ref proposal.

2024-09-23 07:55 UTC, q82419 commented on test/loader/serializeInstructionTest.cpp
> +  Conf.addProposal(WasmEdge::Proposal::FunctionReferences);
As above, add right before 4. test.

2024-09-24 13:05 UTC, q82419 approved these changes

2024-09-24 14:20 UTC, elhewaty commented
@q82419 when will you merge it?

2024-09-24 15:36 UTC, merged