[WASI-NN] Whisper: Reset whisper config when setting metadata each time.
WasmEdge/WasmEdge pull request #3766
Opened 2024-09-15 19:42 UTC by q82419

2024-09-15 19:42 UTC, juntao commented
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-09-23 08:12 UTC, q82419 commented
@apepkuss You can test new configs in metadata with this PR.
And also, this PR supports `unload` as the same in GGML backend.

2024-09-25 22:05 UTC, hydai requested changes

2024-09-25 22:05 UTC, hydai commented on plugins/wasi_nn/whispercpp.cpp
> +    spdlog::info("[WASI-NN][Debug] Whisper backend: Config: threads: {}",
Should we use the same way to handle the log like `PrintParsedOption`?

2024-09-27 19:35 UTC, hydai approved these changes

2024-09-30 08:11 UTC, merged