Support all log levels in the API and add user callback support
WasmEdge/WasmEdge pull request #3789
Opened 2024-09-21 12:19 UTC by vdimir

2024-09-21 12:19 UTC, juntao commented
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-09-21 14:14 UTC, hydai commented
Hi @vdimir 
Please sign your commits with DCO, thanks.
Ref: https://wasmedge.org/docs/contribute/#dco

2024-09-24 17:13 UTC, hydai commented
The Windows CI failed because of an extra `;` in the `callback_sink.h`.
A fix is merged by the upstream: https://github.com/gabime/spdlog/pull/3198
We are unsure when will have a new release from the spdlog side. 
However, it's fine to disable this warning here to avoid the failing CI.

2024-10-01 03:35 UTC, ibmibmibm requested changes

2024-10-01 03:35 UTC, ibmibmibm commented on lib/api/wasmedge.cpp
> +    assumingUnreachable();
This `Level` is provided by the user, so it cannot be assumed to always be valid.
You should check for invalid input here and decide whether to return an error or ignore it.

2024-10-14 16:43 UTC, hydai commented
@ibmibmibm 
PTAL. This PR should be ready to merge.

2024-10-16 06:06 UTC, ibmibmibm requested changes

2024-10-16 06:06 UTC, ibmibmibm commented on lib/api/wasmedge.cpp
> +  WasmEdge::Log::setLoggingCallback([Callback](
Check `nullptr` and choose to fail or deregister callbacks

2024-10-23 11:05 UTC, hydai commented
Hi, @ibmibmibm 
I believe these are minor issues, and it's totally fine to fix them later via another PR. I would like to merge this PR first. Could you please approve it?

And thanks, @vdimir, for this; it helps a lot.

2024-11-25 08:05 UTC, ibmibmibm approved these changes

2024-11-25 08:31 UTC, merged

2024-11-25 08:31 UTC, hydai commented
Thank you @vdimir