[WASI-NN] whisper: add metal and cuda option
WasmEdge/WasmEdge pull request #3815
Opened 2024-10-04 06:43 UTC by grorge123

2024-10-04 06:43 UTC, juntao commented
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-10-04 06:50 UTC, hydai approved these changes

2024-10-04 11:58 UTC, q82419 requested changes

2024-10-04 11:58 UTC, q82419 commented on plugins/wasi_nn/CMakeLists.txt
> +    if(APPLE AND WASMEDGE_PLUGIN_WASI_NN_WHISPER_METAL)
Remove this.
For embedding metal library, the extra header and metal file are not needed.

2024-10-05 08:21 UTC, hydai approved these changes

2024-10-05 08:22 UTC, merged