[WIP] [Executor] coredunmp: add coredump
WasmEdge/WasmEdge pull request #3860
Opened 2024-11-01 13:27 UTC by grorge123

2024-11-01 13:27 UTC, juntao commented
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-11-28 16:45 UTC, hydai commented
@q82419 This is ready to be reviewed. PTAL.

2024-12-04 02:24 UTC, q82419 requested changes

2024-12-04 02:24 UTC, q82419 commented on include/executor/coredump.h
> +AST::GlobalSection createGlobals(
Sorting these functions with the instance order. (i.e. Func, Table, Memory, Global ..)

2024-12-04 02:24 UTC, q82419 commented on lib/executor/coredump.cpp
> +#define ENCODE_LEB128(Content, Value)                                          \
You included the `serialize.h`.
Why not just use the `serializeUN()` or `serializeU32()`?

2024-12-09 08:30 UTC, q82419 commented on lib/executor/coredump.cpp
> +#define ENCODE_LEB128(Content, Value)                                          \
Yes, you can export them from the serializer.

2024-12-09 17:44 UTC, q82419 submitted a review, later dismissed

2024-12-13 21:10 UTC, hydai requested changes
@grorge123 
Please fix the windows issues.

2024-12-14 10:00 UTC, hydai approved these changes
LGTM

2024-12-14 10:04 UTC, merged