[WIP] Compile to buffer
WasmEdge/WasmEdge pull request #3862
Opened 2024-11-04 22:30 UTC by RichardAH

Hi guys!

We need this compile-to-buffer API for the Xahau blockchain (https://github.com/Xahau/xahaud ) which uses WasmEdge for smart contracts, specifically we want to use ahead of time compilation to cache execution of frequently used contracts.

I haven't had time to test, this is just a preliminary version of the PR. If someone else thinks this is a needed API change please feel free to assist.

2024-11-05 04:02 UTC, hydai requested changes

2024-11-05 04:02 UTC, hydai commented on lib/llvm/codegen.cpp
> +    // or if there's already a plan and scheme to do that...
Since we are having the new release for 0.15, it's fine to update the enum and add more `ErrCode` to show the real error value.

2024-11-05 04:02 UTC, hydai commented on lib/llvm/codegen.cpp
> +  memcpy(const_cast<uint8_t*>(OutByte.data()), buf.data(), buf.size());
Prefer to use `copy_n` instead of any `memcpy` series function.

2024-11-05 04:02 UTC, hydai commented on lib/llvm/codegen.cpp
> +  LLVM::MemoryBuffer& buf = *result;
Naming issue: `Buf`.

2024-11-05 04:02 UTC, hydai commented on lib/llvm/codegen.cpp
> +  auto result = codegen_osvec(WasmData, D);
Naming issue: `Result`.

2024-11-05 09:06 UTC, q82419 commented on include/llvm/codegen.h
> +  Expect<void> codegen_buffer(Span<const Byte> WasmData,
I think `codegenToBuffer` is better.

2024-11-05 09:09 UTC, q82419 commented on include/api/wasmedge/wasmedge.h
> +/// Compile the input WASM from a WasmEdge_Bytes, and output it to a WasmEdge_Bytes.///
And also lost a line.

2024-11-05 09:09 UTC, q82419 commented on include/api/wasmedge/wasmedge.h
> +/// Compile the input WASM from a WasmEdge_Bytes, and output it to a WasmEdge_Bytes.///
And also lost an empty line.

2024-11-09 05:06 UTC, RichardAH commented
Thanks for the reviews I'll get back to this hopefully in the coming week

2025-04-07 02:49 UTC, hydai commented
Hi @RichardAH 
Are you still working on this PR?

2025-04-16 00:49 UTC, hydai commented
Closing due to inactivity. Thank you for your PR. Please feel free to reopen it if you plan to work on it again.

2025-04-16 00:49 UTC, closed without merging