[Log] Allow to unregister the log callback function.
WasmEdge/WasmEdge pull request #3915
Opened 2024-12-12 22:52 UTC by ibmibmibm

2024-12-12 22:52 UTC, juntao commented
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-12-13 08:00 UTC, hydai submitted a review, later dismissed

2024-12-13 13:21 UTC, hydai requested changes

2024-12-13 13:21 UTC, hydai commented on test/api/APIUnitTest.cpp
> +  WasmEdge_LogSetCallback(nullptr);
Seems like this will break the CI.

2024-12-16 20:39 UTC, hydai approved these changes

2024-12-16 20:39 UTC, merged