[Docker] Update llvm, zstd, ninja, cmake in dockerfile
WasmEdge/WasmEdge pull request #3924
Opened 2024-12-18 11:29 UTC by ibmibmibm

* Remove unused zstd flags in manylinux_2_28

2024-12-18 11:29 UTC, juntao commented
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-12-20 13:59 UTC, hydai requested changes

2024-12-20 13:59 UTC, hydai commented on utils/docker/Dockerfile.manylinux2014_aarch64
> +        https://github.com/Kitware/CMake/releases/download/vv3.31.2/cmake-v3.31.2.tar.gz \
It should not be `vv3.31.2` in both x64 and aarch64.

2024-12-27 15:37 UTC, hydai approved these changes

2024-12-29 15:42 UTC, merged