[WASI] wasi-crypto proposal
WasmEdge/WasmEdge pull request #408
Opened 2021-09-13 15:10 UTC by sonder-joker

This is a long-term pull request that is still working, and will be constantly repair and commit for review. I think making this process public in early will work better.

2021-09-28 05:55 UTC, hydai commented on utils/wasi-cpp-header/crypto_generate.sh
> +target/release/wasi-cpp-header generate --output /home/younger/WasmEdge/thirdparty/wasi/crypto/api.hpp proposal_kx.witx proposal_asymmetric_common.witx  proposal_common.witx proposal_signatures.witx
Don't use your local path in a general script.

2021-09-28 05:58 UTC, hydai commented
Also, I think you will need a README file in the `docs/witx/crypto` which mentions that the version of `wasi-crypto`

2022-01-14 10:18 UTC, sonder-joker commented
Only left many linux- I need check build script

2022-02-18 07:32 UTC, hydai requested changes
There are some places which will need to fix first.

2022-02-18 07:32 UTC, hydai commented on include/common/enum_configure.h
> +#ifdef WASMEDGE_BUILD_WASI_CRYPTO
The HostRegistration should be a static one. So you should not use `ifdef` here to remove it. Instead, just keep it.

2022-02-18 07:32 UTC, hydai commented on include/common/enum_configure.h
> +#ifdef WASMEDGE_BUILD_WASI_CRYPTO
Ditto.

2022-02-18 07:32 UTC, hydai commented on include/host/wasi_crypto/asymmetric_common/func.h
> +                        __wasi_size_t AlgorithmLen, uint32_t Options,
In the top level, we should use `stdint` like `int32_t`, `int64_t`, `uint32_t`, or `uint64_t`. Then, cast this type inside the function body.

E.g. `const_uint8_t_ptr` -> `uint32_t`; `__wasi_size_t` -> `uint32_t`.

2022-02-18 07:32 UTC, hydai commented on include/host/wasi_crypto/asymmetric_common/func.h
> +                        uint8_t_ptr /* Out */ KeypairPtr);
Ditto.

2022-02-18 07:32 UTC, hydai commented on lib/host/wasi_crypto/asymmetric_common/func.cpp
> +  if (MemInst == nullptr) {
Please use `unlikely(MemInst == nullptr)`

2022-02-25 02:57 UTC, sonder-joker commented
Current this branch have a bad git log, so I make a new branch to refactor. This branch remain for reference.

2022-02-25 02:57 UTC, closed without merging