[Rust] Implement new APIs for Vm and ImportObj
WasmEdge/WasmEdge pull request #896
Opened 2021-12-13 09:34 UTC by apepkuss

The following C-APIs are involved in this PR:
- VM
  - Fix #773 
  - Fix #774 
  - Fix #775 
  - Fix #777 
  - Fix #601 
  - Fix #801 
  - Fix #800 
- ImportObj
  - WasmEdge_ImportObjectWASIGetExitCode
  - Fix #750 
  - Fix #751

2021-12-15 13:29 UTC, hydai requested changes

2021-12-15 13:29 UTC, hydai commented on bindings/rust/wasmedge-sys/src/types.rs
> +// pub type HostRegistration = wasmedge::WasmEdge_HostRegistration;
Why do you comment out this line?

2021-12-15 14:25 UTC, apepkuss commented on bindings/rust/wasmedge-sys/src/types.rs
> +// pub type HostRegistration = wasmedge::WasmEdge_HostRegistration;
I'll remove the code line. Thanks!

2021-12-15 14:49 UTC, hydai submitted a review, later dismissed

2021-12-15 14:50 UTC, hydai commented
Looks like there is a conflict in `types.rs`. @apepkuss Please resolve it and I am going to merge this PR. Thanks.

2021-12-15 14:58 UTC, apepkuss commented
@hydai I'll resolve the conflicts, thanks a lot!

2021-12-16 09:04 UTC, apepkuss commented
Hi @hydai, the conflicts have been resolved, please review the changes again, thanks a lot!

2021-12-16 09:05 UTC, hydai approved these changes

2021-12-16 09:08 UTC, hydai commented
Looks like GitHub broken again...
This PR is merged: https://github.com/WasmEdge/WasmEdge/commit/ebbb3684fb4932935b4f99c6cab7d4195c2d5897
However, it doesn't show this got merged. I am closing this manually.

2021-12-16 09:08 UTC, closed without merging