[Rust] Added doc comments for Global and GlobalType;
WasmEdge/WasmEdge pull request #905
Opened 2021-12-17 03:10 UTC by apepkuss

This PR is to add the necessary descriptions for Global and GlobalType.

2021-12-17 10:16 UTC, apepkuss commented
Hi @hydai, could you please help review this PR? Thanks a lot!

2021-12-17 11:41 UTC, hydai requested changes

2021-12-17 14:03 UTC, apepkuss commented
@hydai The issues have been fixed. Thanks a lot!

2021-12-21 02:22 UTC, apepkuss commented
Hi @hydai, could you please help review the latest changes? The review comments have been fixed. Thanks a lot!

2021-12-22 04:53 UTC, hydai requested changes

2021-12-22 04:53 UTC, hydai commented on bindings/rust/wasmedge-sys/src/types.rs
> +                Value: v as u128,
Why do we map `I32` to `u128`?

2021-12-22 04:53 UTC, hydai commented on bindings/rust/wasmedge-sys/src/types.rs
> +                Value: v as u128,
Why do we map `I64` to `u128`?

2021-12-22 04:53 UTC, hydai commented on bindings/rust/wasmedge-sys/src/types.rs
> +                Value: v.to_bits() as u128,
Why do we map `F32` to `u128`?

2021-12-22 04:53 UTC, hydai commented on bindings/rust/wasmedge-sys/src/types.rs
> +                Value: v.to_bits() as u128,
Why do we map `F64` to `u128`?

2021-12-22 04:53 UTC, hydai commented on bindings/rust/wasmedge-sys/src/lib.rs
> +// #[doc(hidden)]
Why do we comment this out?

2021-12-22 09:55 UTC, apepkuss commented
Hi @hydai, the review issues have been fixed, please help review the latest changes again. Thanks a lot!

2021-12-23 18:36 UTC, hydai commented
@apepkuss 
There are some issues are not resolved. Please take a look. Thanks.

2021-12-24 01:45 UTC, apepkuss commented
@hydai, thanks for your reminder. I've already resolved the comments. Thanks!

2021-12-24 07:11 UTC, hydai approved these changes

2021-12-24 09:43 UTC, merged