Reduce the Instruction class size.
WasmEdge/WasmEdge pull request #916
Opened 2021-12-21 21:24 UTC by q82419

2021-12-22 22:01 UTC, q82419 commented
As the step in #473 :

1. Build the `WasmEdge 0.9.0` in debug mode, and rename the tools into `./wasmedge-0.9.0` and `wasmedgec-0.9.0`.
2. Build the `WasmEdge` with the current branch in debug mode and get the output tool `./wasmedge` and `./wasmedgec`.
3. Prepare the AOT WASM:
  ```bash
  ./wasmedgec-0.9.0 wasmedge_quickjs.wasm out-0.9.0.wasm
  ./wasmedgec wasmedge_quickjs.wasm out.wasm
  ```
4. Performance checking:

```bash
$ time ./wasmedge-0.9.0 --dir=.:. out-0.9.0.wasm index.js
SystemTime(1640210055.904689792s)
SystemTime(1640210055.907324512s)
SystemTime(1640210055.907533087s)
SystemTime(1640210056.89416306s)
2i
SystemTime(1640210074.11342564s)

real	0m19.225s
user	0m19.166s
sys	0m0.056s
```

```bash
$ time ./wasmedge --dir=.:. out_new.wasm index.js
SystemTime(1640210163.123269641s)
SystemTime(1640210163.125043493s)
SystemTime(1640210163.125198254s)
SystemTime(1640210164.140102536s)
2i
SystemTime(1640210181.366647978s)

real	0m19.147s
user	0m19.091s
sys	0m0.025s
```

The performance not changes.

5. Memory profiling:

```bash
$ env LD_PRELOAD="/lib/x86_64-linux-gnu/libtcmalloc.so.4" HEAPPROFILE=./heap/wasmedge_AOT/1 HEAP_PROFILE_TIME_INTERVAL="50" ./wasmedge-0.9.0 --dir=.:. out-0.9.0.wasm index.js
# ...

$ pprof-symbolize --text ./wasmedge-0.9.0 ./heap/wasmedge_AOT/1.0002.heap
Using local file ./wasmedge-0.9.0.
Using local file ./heap/wasmedge_AOT/1.0002.heap.
/usr/bin/addr2line: DWARF error: could not find variable specification at offset 1360
Total: 72.5 MB
    72.1  99.4%  99.4%     72.1  99.4% __gnu_cxx::new_allocator::allocate
     0.1   0.2%  99.6%      0.1   0.2% std::__cxx11::basic_string::_M_construct
     0.1   0.2%  99.8%      0.2   0.3% std::make_unique
     0.1   0.2% 100.0%      0.1   0.2% std::basic_filebuf::_M_allocate_internal_buffer
     0.0   0.0% 100.0%      0.0   0.0% on_exit@@GLIBC_2.2.5
     0.0   0.0% 100.0%      0.0   0.0% std::__cxx11::basic_string::_M_mutate
     0.0   0.0% 100.0%      0.0   0.0% std::__cxx11::basic_string::basic_string
     0.0   0.0% 100.0%      0.0   0.0% std::filesystem::__cxx11::path::_M_split_cmpts@@GLIBCXX_3.4.26
     0.0   0.0% 100.0%      0.0   0.0% registry
     0.0   0.0% 100.0%      0.0   0.0% std::__cxx11::basic_string::reserve
     0.0   0.0% 100.0%      0.0   0.0% 0x00007fee141028af
# ...
```

```bash
$ env LD_PRELOAD="/lib/x86_64-linux-gnu/libtcmalloc.so.4" HEAPPROFILE=./heap/wasmedge_AOT/1 HEAP_PROFILE_TIME_INTERVAL="50" ./wasmedge --dir=.:. out.wasm index.js
# ...

$ pprof-symbolize --text ./wasmedge ./heap/wasmedge_AOT/2.0002.heap
Using local file ./wasmedge.
Using local file ./heap/wasmedge_AOT/2.0002.heap.
/usr/bin/addr2line: DWARF error: could not find variable specification at offset 1360
Total: 24.7 MB
    24.3  98.3%  98.3%     24.3  98.3% __gnu_cxx::new_allocator::allocate
     0.1   0.5%  98.8%      0.1   0.5% std::__cxx11::basic_string::_M_construct
     0.1   0.5%  99.3%      0.2   1.0% std::make_unique
     0.1   0.5%  99.8%      0.1   0.5% std::basic_filebuf::_M_allocate_internal_buffer
     0.0   0.1%  99.9%      0.0   0.1% Instruction
     0.0   0.1% 100.0%      0.0   0.1% on_exit@@GLIBC_2.2.5
     0.0   0.0% 100.0%      0.0   0.0% WasmEdge::AST::Instruction::setLabelListSize
     0.0   0.0% 100.0%      0.0   0.0% std::__cxx11::basic_string::_M_mutate
     0.0   0.0% 100.0%      0.0   0.0% std::__cxx11::basic_string::basic_string
     0.0   0.0% 100.0%      0.0   0.0% std::filesystem::__cxx11::path::_M_split_cmpts@@GLIBCXX_3.4.26
     0.0   0.0% 100.0%      0.0   0.0% registry
     0.0   0.0% 100.0%      0.0   0.0% std::__cxx11::basic_string::reserve
     0.0   0.0% 100.0%      0.0   0.0% 0x00007f07cc5668af
```

Memory usage from 72.5 MB reduced into 24.7 MB.

2021-12-23 11:06 UTC, ibmibmibm requested changes

2021-12-23 11:06 UTC, ibmibmibm commented on include/ast/instruction.h
> +  ~Instruction() { resetData(); }
`reset()`

2021-12-28 09:35 UTC, ibmibmibm approved these changes

2021-12-29 04:34 UTC, merged