[Tools] Enable --gas-limit for wasmedge cli
WasmEdge/WasmEdge pull request #928
Opened 2021-12-23 07:35 UTC by hydai

Signed-off-by: hydai <hydai@secondstate.io>

2021-12-23 07:55 UTC, juntao commented
Let's deprecate pages like `docs/run.md` and use the `book` as the single source of truth. Thanks.

https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/start/cli.md

2021-12-23 08:08 UTC, hydai commented
> Let's deprecate pages like `docs/run.md` and use the `book` as the single source of truth. Thanks.
> 
> https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/start/cli.md

Sure. Should I also redirect these pages to the new one?

2021-12-23 08:11 UTC, juntao commented
I do not think GitHub will do http redirect? Perhaps we can remove the content in the md file and put a link to the book's html page there for people to click on?

2021-12-23 08:13 UTC, hydai commented
That's what I want. Put a link.
However, I am not sure which one is better: put a link to the webpage or to the new markdown file?

2021-12-23 08:16 UTC, juntao commented
> That's what I want. Put a link. However, I am not sure which one is better: put a link to the webpage or to the new markdown file?

I think web page is better since the visitor is typically looking to read this content. The HTML page has an "edit" button that brings the reader directly to the MD source file.

2021-12-23 22:40 UTC, ibmibmibm requested changes

2021-12-23 22:40 UTC, ibmibmibm commented on include/common/statistics.h
> +    if (Conf.getStatisticsConfigure().isTimeMeasuring() ||
`const auto &StatConf = Conf.getStatisticsConfigure();`

2021-12-24 09:08 UTC, ibmibmibm approved these changes

2021-12-24 09:32 UTC, merged